// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignItemToTemplate = `-- name: AssignItemToTemplate :one
INSERT INTO auth.menu_template_items (template_id, menu_item_id, display_order, is_visible)
VALUES ($1, $2, $3, $4)
ON CONFLICT (template_id, menu_item_id) DO UPDATE
SET display_order = EXCLUDED.display_order,
    is_visible = EXCLUDED.is_visible
RETURNING id, template_id, menu_item_id, display_order, is_visible, created_at
`

// Asigna un item a un template (o actualiza si ya existe)
func (q *Queries) AssignItemToTemplate(ctx context.Context, templateID pgtype.UUID, menuItemID pgtype.UUID, displayOrder *int32, isVisible *bool) (AuthMenuTemplateItem, error) {
	row := q.db.QueryRow(ctx, assignItemToTemplate,
		templateID,
		menuItemID,
		displayOrder,
		isVisible,
	)
	var i AuthMenuTemplateItem
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.MenuItemID,
		&i.DisplayOrder,
		&i.IsVisible,
		&i.CreatedAt,
	)
	return i, err
}

const assignMenuTemplateToTenant = `-- name: AssignMenuTemplateToTenant :exec
INSERT INTO auth.tenant_menu_assignments (tenant_id, template_id)
VALUES ($1, $2) ON CONFLICT (tenant_id) DO
UPDATE
SET template_id = EXCLUDED.template_id
`

func (q *Queries) AssignMenuTemplateToTenant(ctx context.Context, tenantID pgtype.UUID, templateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, assignMenuTemplateToTenant, tenantID, templateID)
	return err
}

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO auth.role_permissions (role_id, permission_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

func (q *Queries) AssignPermissionToRole(ctx context.Context, roleID pgtype.UUID, permissionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, roleID, permissionID)
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO auth.user_roles (user_id, role_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

func (q *Queries) AssignRoleToUser(ctx context.Context, userID pgtype.UUID, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, userID, roleID)
	return err
}

const bulkAssignItemsToTemplate = `-- name: BulkAssignItemsToTemplate :exec
INSERT INTO auth.menu_template_items (template_id, menu_item_id, display_order, is_visible)
SELECT $1::uuid, unnest($2::uuid[]), generate_series(1, array_length($2::uuid[], 1)), true
ON CONFLICT (template_id, menu_item_id) DO NOTHING
`

// Asigna múltiples items a un template
func (q *Queries) BulkAssignItemsToTemplate(ctx context.Context, column1 pgtype.UUID, column2 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bulkAssignItemsToTemplate, column1, column2)
	return err
}

const createMenuTemplate = `-- name: CreateMenuTemplate :one
INSERT INTO auth.menu_templates (name, description, is_default)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_default, created_at, updated_at
`

func (q *Queries) CreateMenuTemplate(ctx context.Context, name string, description *string, isDefault *bool) (AuthMenuTemplate, error) {
	row := q.db.QueryRow(ctx, createMenuTemplate, name, description, isDefault)
	var i AuthMenuTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO auth.permissions (code, description, module, scope)
VALUES ($1, $2, $3, $4)
RETURNING id, code, description, module, created_at, scope
`

func (q *Queries) CreatePermission(ctx context.Context, code string, description *string, module *string, scope *string) (AuthPermission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		code,
		description,
		module,
		scope,
	)
	var i AuthPermission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
		&i.CreatedAt,
		&i.Scope,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO auth.roles (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, description, is_system, created_at
`

// Roles
func (q *Queries) CreateRole(ctx context.Context, tenantID pgtype.UUID, name string, description *string) (AuthRole, error) {
	row := q.db.QueryRow(ctx, createRole, tenantID, name, description)
	var i AuthRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth.sessions (
        user_id,
        tenant_id,
        token_hash,
        device_info,
        ip_address,
        expires_at
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, tenant_id, token_hash, device_info, ip_address, last_activity_at, expires_at, created_at
`

// Sessions
func (q *Queries) CreateSession(ctx context.Context, userID pgtype.UUID, tenantID pgtype.UUID, tokenHash string, deviceInfo []byte, ipAddress *netip.Addr, expiresAt pgtype.Timestamptz) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		userID,
		tenantID,
		tokenHash,
		deviceInfo,
		ipAddress,
		expiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.LastActivityAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSystemRole = `-- name: CreateSystemRole :one
INSERT INTO auth.roles (tenant_id, name, description, is_system)
VALUES (NULL, $1, $2, true)
RETURNING id, tenant_id, name, description, is_system, created_at
`

func (q *Queries) CreateSystemRole(ctx context.Context, name string, description *string) (AuthRole, error) {
	row := q.db.QueryRow(ctx, createSystemRole, name, description)
	var i AuthRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (
        tenant_id,
        email,
        password_hash,
        first_name,
        last_name,
        phone
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, email, password_hash, first_name, last_name, phone, avatar_url, is_active, email_verified, last_login_at, created_at, updated_at, created_by, updated_by
`

// internal/database/queries/auth.sql
// Queries para autenticación y usuarios
func (q *Queries) CreateUser(ctx context.Context, tenantID pgtype.UUID, email string, passwordHash string, firstName string, lastName string, phone *string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		tenantID,
		email,
		passwordHash,
		firstName,
		lastName,
		phone,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE auth.users
SET is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) DeactivateUser(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, iD, tenantID)
	return err
}

const deactivateUserGlobal = `-- name: DeactivateUserGlobal :exec
UPDATE auth.users
SET is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeactivateUserGlobal(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUserGlobal, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM auth.sessions
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth.sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getDefaultMenuTemplate = `-- name: GetDefaultMenuTemplate :one
SELECT id, name, description, is_default, created_at, updated_at
FROM auth.menu_templates
WHERE is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultMenuTemplate(ctx context.Context) (AuthMenuTemplate, error) {
	row := q.db.QueryRow(ctx, getDefaultMenuTemplate)
	var i AuthMenuTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMenuItemsByTemplate = `-- name: GetMenuItemsByTemplate :many
SELECT m.id, m.tenant_id, m.code, m.label, m.icon, m.route, m.parent_id, m.required_permission, m.display_order, m.is_active, m.is_visible, m.badge_text, m.badge_color, m.description, m.metadata, m.created_at, m.updated_at, m.created_by, m.template_id
FROM auth.menu_items m
    INNER JOIN auth.menu_template_items mti ON m.id = mti.menu_item_id
WHERE mti.template_id = $1
    AND m.is_active = true
    AND mti.is_visible = true
ORDER BY mti.display_order, m.display_order
`

// Usa la tabla N:N menu_template_items para obtener items de un template
func (q *Queries) GetMenuItemsByTemplate(ctx context.Context, templateID pgtype.UUID) ([]AuthMenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItemsByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthMenuItem{}
	for rows.Next() {
		var i AuthMenuItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Label,
			&i.Icon,
			&i.Route,
			&i.ParentID,
			&i.RequiredPermission,
			&i.DisplayOrder,
			&i.IsActive,
			&i.IsVisible,
			&i.BadgeText,
			&i.BadgeColor,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenuTemplateForTenant = `-- name: GetMenuTemplateForTenant :one
SELECT mt.id, mt.name, mt.description, mt.is_default, mt.created_at, mt.updated_at
FROM auth.menu_templates mt
    INNER JOIN auth.tenant_menu_assignments tma ON mt.id = tma.template_id
WHERE tma.tenant_id = $1
LIMIT 1
`

func (q *Queries) GetMenuTemplateForTenant(ctx context.Context, tenantID pgtype.UUID) (AuthMenuTemplate, error) {
	row := q.db.QueryRow(ctx, getMenuTemplateForTenant, tenantID)
	var i AuthMenuTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, code, description, module, created_at, scope
FROM auth.permissions
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (AuthPermission, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i AuthPermission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
		&i.CreatedAt,
		&i.Scope,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, name, description, is_system, created_at
FROM auth.roles
WHERE id = $1
    AND (
        tenant_id = $2
        OR tenant_id IS NULL
    )
LIMIT 1
`

func (q *Queries) GetRoleByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (AuthRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, iD, tenantID)
	var i AuthRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.code, p.description, p.module, p.created_at, p.scope
FROM auth.permissions p
    INNER JOIN auth.role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID pgtype.UUID) ([]AuthPermission, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPermission{}
	for rows.Next() {
		var i AuthPermission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, tenant_id, token_hash, device_info, ip_address, last_activity_at, expires_at, created_at
FROM auth.sessions
WHERE token_hash = $1
    AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.LastActivityAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTemplateItemAssignments = `-- name: GetTemplateItemAssignments :many

SELECT 
    mti.id,
    mti.template_id,
    mti.menu_item_id,
    mti.display_order,
    mti.is_visible,
    mti.created_at,
    m.code as item_code,
    m.label as item_label,
    m.icon as item_icon,
    m.route as item_route
FROM auth.menu_template_items mti
    INNER JOIN auth.menu_items m ON mti.menu_item_id = m.id
WHERE mti.template_id = $1
ORDER BY mti.display_order, m.label
`

type GetTemplateItemAssignmentsRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	TemplateID   pgtype.UUID        `db:"template_id" json:"template_id"`
	MenuItemID   pgtype.UUID        `db:"menu_item_id" json:"menu_item_id"`
	DisplayOrder *int32             `db:"display_order" json:"display_order"`
	IsVisible    *bool              `db:"is_visible" json:"is_visible"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ItemCode     string             `db:"item_code" json:"item_code"`
	ItemLabel    string             `db:"item_label" json:"item_label"`
	ItemIcon     *string            `db:"item_icon" json:"item_icon"`
	ItemRoute    *string            `db:"item_route" json:"item_route"`
}

// =====================================================
// Menu Template Items (N:N relationship)
// =====================================================
// Obtiene la asignación de items a un template con info del item
func (q *Queries) GetTemplateItemAssignments(ctx context.Context, templateID pgtype.UUID) ([]GetTemplateItemAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, getTemplateItemAssignments, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemplateItemAssignmentsRow{}
	for rows.Next() {
		var i GetTemplateItemAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.MenuItemID,
			&i.DisplayOrder,
			&i.IsVisible,
			&i.CreatedAt,
			&i.ItemCode,
			&i.ItemLabel,
			&i.ItemIcon,
			&i.ItemRoute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplatesForMenuItem = `-- name: GetTemplatesForMenuItem :many
SELECT 
    mt.id,
    mt.name,
    mt.description,
    mt.is_default,
    mti.display_order,
    mti.is_visible
FROM auth.menu_templates mt
    INNER JOIN auth.menu_template_items mti ON mt.id = mti.template_id
WHERE mti.menu_item_id = $1
ORDER BY mt.name
`

type GetTemplatesForMenuItemRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Description  *string     `db:"description" json:"description"`
	IsDefault    *bool       `db:"is_default" json:"is_default"`
	DisplayOrder *int32      `db:"display_order" json:"display_order"`
	IsVisible    *bool       `db:"is_visible" json:"is_visible"`
}

// Obtiene todos los templates que tienen asignado un item específico
func (q *Queries) GetTemplatesForMenuItem(ctx context.Context, menuItemID pgtype.UUID) ([]GetTemplatesForMenuItemRow, error) {
	rows, err := q.db.Query(ctx, getTemplatesForMenuItem, menuItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemplatesForMenuItemRow{}
	for rows.Next() {
		var i GetTemplatesForMenuItemRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.DisplayOrder,
			&i.IsVisible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantsForTemplate = `-- name: GetTenantsForTemplate :many
SELECT t.id,
    t.name,
    t.slug,
    t.logo_url
FROM public.tenants t
    INNER JOIN auth.tenant_menu_assignments tma ON t.id = tma.tenant_id
WHERE tma.template_id = $1
ORDER BY t.name
`

type GetTenantsForTemplateRow struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	Name    string      `db:"name" json:"name"`
	Slug    string      `db:"slug" json:"slug"`
	LogoUrl *string     `db:"logo_url" json:"logo_url"`
}

func (q *Queries) GetTenantsForTemplate(ctx context.Context, templateID pgtype.UUID) ([]GetTenantsForTemplateRow, error) {
	rows, err := q.db.Query(ctx, getTenantsForTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTenantsForTemplateRow{}
	for rows.Next() {
		var i GetTenantsForTemplateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnassignedItemsForTemplate = `-- name: GetUnassignedItemsForTemplate :many
SELECT m.id, m.tenant_id, m.code, m.label, m.icon, m.route, m.parent_id, m.required_permission, m.display_order, m.is_active, m.is_visible, m.badge_text, m.badge_color, m.description, m.metadata, m.created_at, m.updated_at, m.created_by, m.template_id
FROM auth.menu_items m
WHERE m.id NOT IN (
    SELECT mti.menu_item_id 
    FROM auth.menu_template_items mti
    WHERE mti.template_id = $1
)
AND m.is_active = true
ORDER BY m.label
`

// Obtiene items que NO están asignados a un template específico
func (q *Queries) GetUnassignedItemsForTemplate(ctx context.Context, templateID pgtype.UUID) ([]AuthMenuItem, error) {
	rows, err := q.db.Query(ctx, getUnassignedItemsForTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthMenuItem{}
	for rows.Next() {
		var i AuthMenuItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Label,
			&i.Icon,
			&i.Route,
			&i.ParentID,
			&i.RequiredPermission,
			&i.DisplayOrder,
			&i.IsActive,
			&i.IsVisible,
			&i.BadgeText,
			&i.BadgeColor,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, first_name, last_name, phone, avatar_url, is_active, email_verified, last_login_at, created_at, updated_at, created_by, updated_by
FROM auth.users
WHERE tenant_id = $1
    AND email = $2
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, tenantID pgtype.UUID, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, tenantID, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.tenant_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.email_verified, u.last_login_at, u.created_at, u.updated_at, u.created_by, u.updated_by,
    t.name AS tenant_name,
    (
        SELECT COALESCE(
                json_agg(
                    json_build_object(
                        'id',
                        r.id,
                        'name',
                        r.name,
                        'description',
                        r.description
                    )
                    ORDER BY r.name
                ),
                '[]'::json
            )
        FROM auth.user_roles ur
            INNER JOIN auth.roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
    ) AS roles
FROM auth.users u
    LEFT JOIN public.tenants t ON u.tenant_id = t.id
WHERE u.id = $1
    AND u.tenant_id = $2
LIMIT 1
`

type GetUserByIDRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	TenantID      pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Email         string             `db:"email" json:"email"`
	PasswordHash  string             `db:"password_hash" json:"password_hash"`
	FirstName     string             `db:"first_name" json:"first_name"`
	LastName      string             `db:"last_name" json:"last_name"`
	Phone         *string            `db:"phone" json:"phone"`
	AvatarUrl     *string            `db:"avatar_url" json:"avatar_url"`
	IsActive      *bool              `db:"is_active" json:"is_active"`
	EmailVerified *bool              `db:"email_verified" json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy     pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedBy     pgtype.UUID        `db:"updated_by" json:"updated_by"`
	TenantName    *string            `db:"tenant_name" json:"tenant_name"`
	Roles         interface{}        `db:"roles" json:"roles"`
}

func (q *Queries) GetUserByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, iD, tenantID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TenantName,
		&i.Roles,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.id, p.code, p.description, p.module, p.created_at, p.scope
FROM auth.permissions p
    INNER JOIN auth.role_permissions rp ON p.id = rp.permission_id
    INNER JOIN auth.user_roles ur ON rp.role_id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]AuthPermission, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPermission{}
	for rows.Next() {
		var i AuthPermission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.tenant_id, r.name, r.description, r.is_system, r.created_at
FROM auth.roles r
    INNER JOIN auth.user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]AuthRole, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthRole{}
	for rows.Next() {
		var i AuthRole
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByEmailGlobal = `-- name: GetUsersByEmailGlobal :many
SELECT u.id, u.tenant_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.email_verified, u.last_login_at, u.created_at, u.updated_at, u.created_by, u.updated_by,
    t.name as tenant_name,
    t.slug as tenant_slug,
    t.logo_url as tenant_logo_url,
    t.primary_color as tenant_primary_color,
    t.secondary_color as tenant_secondary_color,
    t.tertiary_color as tenant_tertiary_color,
    t.settings as tenant_settings
FROM auth.users u
    JOIN public.tenants t ON u.tenant_id = t.id
WHERE u.email = $1
    AND u.is_active = true
    AND t.is_active = true
`

type GetUsersByEmailGlobalRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	TenantID             pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Email                string             `db:"email" json:"email"`
	PasswordHash         string             `db:"password_hash" json:"password_hash"`
	FirstName            string             `db:"first_name" json:"first_name"`
	LastName             string             `db:"last_name" json:"last_name"`
	Phone                *string            `db:"phone" json:"phone"`
	AvatarUrl            *string            `db:"avatar_url" json:"avatar_url"`
	IsActive             *bool              `db:"is_active" json:"is_active"`
	EmailVerified        *bool              `db:"email_verified" json:"email_verified"`
	LastLoginAt          pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy            pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedBy            pgtype.UUID        `db:"updated_by" json:"updated_by"`
	TenantName           string             `db:"tenant_name" json:"tenant_name"`
	TenantSlug           string             `db:"tenant_slug" json:"tenant_slug"`
	TenantLogoUrl        *string            `db:"tenant_logo_url" json:"tenant_logo_url"`
	TenantPrimaryColor   *string            `db:"tenant_primary_color" json:"tenant_primary_color"`
	TenantSecondaryColor *string            `db:"tenant_secondary_color" json:"tenant_secondary_color"`
	TenantTertiaryColor  *string            `db:"tenant_tertiary_color" json:"tenant_tertiary_color"`
	TenantSettings       []byte             `db:"tenant_settings" json:"tenant_settings"`
}

func (q *Queries) GetUsersByEmailGlobal(ctx context.Context, email string) ([]GetUsersByEmailGlobalRow, error) {
	rows, err := q.db.Query(ctx, getUsersByEmailGlobal, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByEmailGlobalRow{}
	for rows.Next() {
		var i GetUsersByEmailGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.IsActive,
			&i.EmailVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TenantName,
			&i.TenantSlug,
			&i.TenantLogoUrl,
			&i.TenantPrimaryColor,
			&i.TenantSecondaryColor,
			&i.TenantTertiaryColor,
			&i.TenantSettings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMenuItemsForAdmin = `-- name: ListAllMenuItemsForAdmin :many
SELECT 
    m.id, m.tenant_id, m.code, m.label, m.icon, m.route, m.parent_id, m.required_permission, m.display_order, m.is_active, m.is_visible, m.badge_text, m.badge_color, m.description, m.metadata, m.created_at, m.updated_at, m.created_by, m.template_id,
    (SELECT COUNT(*) FROM auth.menu_template_items WHERE menu_item_id = m.id) as template_count
FROM auth.menu_items m
ORDER BY m.label
`

type ListAllMenuItemsForAdminRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	TenantID           pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Code               string             `db:"code" json:"code"`
	Label              string             `db:"label" json:"label"`
	Icon               *string            `db:"icon" json:"icon"`
	Route              *string            `db:"route" json:"route"`
	ParentID           pgtype.UUID        `db:"parent_id" json:"parent_id"`
	RequiredPermission *string            `db:"required_permission" json:"required_permission"`
	DisplayOrder       *int32             `db:"display_order" json:"display_order"`
	IsActive           *bool              `db:"is_active" json:"is_active"`
	IsVisible          *bool              `db:"is_visible" json:"is_visible"`
	BadgeText          *string            `db:"badge_text" json:"badge_text"`
	BadgeColor         *string            `db:"badge_color" json:"badge_color"`
	Description        *string            `db:"description" json:"description"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	TemplateID         pgtype.UUID        `db:"template_id" json:"template_id"`
	TemplateCount      int64              `db:"template_count" json:"template_count"`
}

// Lista todos los items de menú para administración (sin filtrar por template)
func (q *Queries) ListAllMenuItemsForAdmin(ctx context.Context) ([]ListAllMenuItemsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllMenuItemsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllMenuItemsForAdminRow{}
	for rows.Next() {
		var i ListAllMenuItemsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Label,
			&i.Icon,
			&i.Route,
			&i.ParentID,
			&i.RequiredPermission,
			&i.DisplayOrder,
			&i.IsActive,
			&i.IsVisible,
			&i.BadgeText,
			&i.BadgeColor,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.TemplateID,
			&i.TemplateCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPermissions = `-- name: ListAllPermissions :many
SELECT id, code, description, module, created_at, scope
FROM auth.permissions
ORDER BY module,
    code
`

// Permissions
func (q *Queries) ListAllPermissions(ctx context.Context) ([]AuthPermission, error) {
	rows, err := q.db.Query(ctx, listAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPermission{}
	for rows.Next() {
		var i AuthPermission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTenants = `-- name: ListAllTenants :many
SELECT id,
    name,
    slug,
    logo_url
FROM public.tenants
WHERE is_active = true
ORDER BY name
`

type ListAllTenantsRow struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	Name    string      `db:"name" json:"name"`
	Slug    string      `db:"slug" json:"slug"`
	LogoUrl *string     `db:"logo_url" json:"logo_url"`
}

func (q *Queries) ListAllTenants(ctx context.Context) ([]ListAllTenantsRow, error) {
	rows, err := q.db.Query(ctx, listAllTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTenantsRow{}
	for rows.Next() {
		var i ListAllTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsersGlobal = `-- name: ListAllUsersGlobal :many
SELECT u.id, u.tenant_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.email_verified, u.last_login_at, u.created_at, u.updated_at, u.created_by, u.updated_by,
    t.name AS tenant_name,
    (
        SELECT COALESCE(
                json_agg(
                    json_build_object(
                        'id',
                        r.id,
                        'name',
                        r.name,
                        'description',
                        r.description
                    )
                    ORDER BY r.name
                ),
                '[]'::json
            )
        FROM auth.user_roles ur
            INNER JOIN auth.roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
    ) AS roles
FROM auth.users u
    LEFT JOIN public.tenants t ON u.tenant_id = t.id
ORDER BY t.name,
    u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllUsersGlobalRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	TenantID      pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Email         string             `db:"email" json:"email"`
	PasswordHash  string             `db:"password_hash" json:"password_hash"`
	FirstName     string             `db:"first_name" json:"first_name"`
	LastName      string             `db:"last_name" json:"last_name"`
	Phone         *string            `db:"phone" json:"phone"`
	AvatarUrl     *string            `db:"avatar_url" json:"avatar_url"`
	IsActive      *bool              `db:"is_active" json:"is_active"`
	EmailVerified *bool              `db:"email_verified" json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy     pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedBy     pgtype.UUID        `db:"updated_by" json:"updated_by"`
	TenantName    *string            `db:"tenant_name" json:"tenant_name"`
	Roles         interface{}        `db:"roles" json:"roles"`
}

// Query for super admin to list all users across all tenants
func (q *Queries) ListAllUsersGlobal(ctx context.Context, limit int32, offset int32) ([]ListAllUsersGlobalRow, error) {
	rows, err := q.db.Query(ctx, listAllUsersGlobal, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUsersGlobalRow{}
	for rows.Next() {
		var i ListAllUsersGlobalRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.IsActive,
			&i.EmailVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TenantName,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuTemplates = `-- name: ListMenuTemplates :many
SELECT id, name, description, is_default, created_at, updated_at
FROM auth.menu_templates
ORDER BY is_default DESC,
    name
`

// Menu Templates
func (q *Queries) ListMenuTemplates(ctx context.Context) ([]AuthMenuTemplate, error) {
	rows, err := q.db.Query(ctx, listMenuTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthMenuTemplate{}
	for rows.Next() {
		var i AuthMenuTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByModule = `-- name: ListPermissionsByModule :many
SELECT id, code, description, module, created_at, scope
FROM auth.permissions
WHERE module = $1
ORDER BY code
`

func (q *Queries) ListPermissionsByModule(ctx context.Context, module *string) ([]AuthPermission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByModule, module)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPermission{}
	for rows.Next() {
		var i AuthPermission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByScope = `-- name: ListPermissionsByScope :many
SELECT id, code, description, module, created_at, scope
FROM auth.permissions
WHERE scope = $1
ORDER BY module,
    code
`

func (q *Queries) ListPermissionsByScope(ctx context.Context, scope *string) ([]AuthPermission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByScope, scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPermission{}
	for rows.Next() {
		var i AuthPermission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, tenant_id, name, description, is_system, created_at
FROM auth.roles
WHERE tenant_id = $1
    OR tenant_id IS NULL
ORDER BY is_system DESC,
    name
`

func (q *Queries) ListRolesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]AuthRole, error) {
	rows, err := q.db.Query(ctx, listRolesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthRole{}
	for rows.Next() {
		var i AuthRole
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT u.id, u.tenant_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.email_verified, u.last_login_at, u.created_at, u.updated_at, u.created_by, u.updated_by,
    t.name AS tenant_name,
    (
        SELECT COALESCE(
                json_agg(
                    json_build_object(
                        'id',
                        r.id,
                        'name',
                        r.name,
                        'description',
                        r.description
                    )
                    ORDER BY r.name
                ),
                '[]'::json
            )
        FROM auth.user_roles ur
            INNER JOIN auth.roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
    ) AS roles
FROM auth.users u
    LEFT JOIN public.tenants t ON u.tenant_id = t.id
WHERE u.tenant_id = $1
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByTenantRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	TenantID      pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Email         string             `db:"email" json:"email"`
	PasswordHash  string             `db:"password_hash" json:"password_hash"`
	FirstName     string             `db:"first_name" json:"first_name"`
	LastName      string             `db:"last_name" json:"last_name"`
	Phone         *string            `db:"phone" json:"phone"`
	AvatarUrl     *string            `db:"avatar_url" json:"avatar_url"`
	IsActive      *bool              `db:"is_active" json:"is_active"`
	EmailVerified *bool              `db:"email_verified" json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy     pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedBy     pgtype.UUID        `db:"updated_by" json:"updated_by"`
	TenantName    *string            `db:"tenant_name" json:"tenant_name"`
	Roles         interface{}        `db:"roles" json:"roles"`
}

func (q *Queries) ListUsersByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]ListUsersByTenantRow, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, tenantID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByTenantRow{}
	for rows.Next() {
		var i ListUsersByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.IsActive,
			&i.EmailVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TenantName,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenantAdmin = `-- name: ListUsersByTenantAdmin :many
SELECT u.id, u.tenant_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.email_verified, u.last_login_at, u.created_at, u.updated_at, u.created_by, u.updated_by,
    t.name AS tenant_name,
    (
        SELECT COALESCE(
                json_agg(
                    json_build_object(
                        'id',
                        r.id,
                        'name',
                        r.name,
                        'description',
                        r.description
                    )
                    ORDER BY r.name
                ),
                '[]'::json
            )
        FROM auth.user_roles ur
            INNER JOIN auth.roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id
    ) AS roles
FROM auth.users u
    LEFT JOIN public.tenants t ON u.tenant_id = t.id
WHERE u.tenant_id = $1
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByTenantAdminRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	TenantID      pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Email         string             `db:"email" json:"email"`
	PasswordHash  string             `db:"password_hash" json:"password_hash"`
	FirstName     string             `db:"first_name" json:"first_name"`
	LastName      string             `db:"last_name" json:"last_name"`
	Phone         *string            `db:"phone" json:"phone"`
	AvatarUrl     *string            `db:"avatar_url" json:"avatar_url"`
	IsActive      *bool              `db:"is_active" json:"is_active"`
	EmailVerified *bool              `db:"email_verified" json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy     pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedBy     pgtype.UUID        `db:"updated_by" json:"updated_by"`
	TenantName    *string            `db:"tenant_name" json:"tenant_name"`
	Roles         interface{}        `db:"roles" json:"roles"`
}

// Query for super admin to list users of a specific tenant
func (q *Queries) ListUsersByTenantAdmin(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]ListUsersByTenantAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersByTenantAdmin, tenantID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByTenantAdminRow{}
	for rows.Next() {
		var i ListUsersByTenantAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.IsActive,
			&i.EmailVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TenantName,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllItemsFromTemplate = `-- name: RemoveAllItemsFromTemplate :exec
DELETE FROM auth.menu_template_items
WHERE template_id = $1
`

// Elimina todos los items de un template
func (q *Queries) RemoveAllItemsFromTemplate(ctx context.Context, templateID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAllItemsFromTemplate, templateID)
	return err
}

const removeItemFromTemplate = `-- name: RemoveItemFromTemplate :exec
DELETE FROM auth.menu_template_items
WHERE template_id = $1 AND menu_item_id = $2
`

// Elimina un item de un template
func (q *Queries) RemoveItemFromTemplate(ctx context.Context, templateID pgtype.UUID, menuItemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeItemFromTemplate, templateID, menuItemID)
	return err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM auth.user_roles
WHERE user_id = $1
    AND role_id = $2
`

func (q *Queries) RemoveRoleFromUser(ctx context.Context, userID pgtype.UUID, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, userID, roleID)
	return err
}

const removeTemplateFromTenant = `-- name: RemoveTemplateFromTenant :exec
DELETE FROM auth.tenant_menu_assignments
WHERE tenant_id = $1
`

func (q *Queries) RemoveTemplateFromTenant(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTemplateFromTenant, tenantID)
	return err
}

const toggleItemVisibilityInTemplate = `-- name: ToggleItemVisibilityInTemplate :one
UPDATE auth.menu_template_items
SET is_visible = $3
WHERE template_id = $1 AND menu_item_id = $2
RETURNING id, template_id, menu_item_id, display_order, is_visible, created_at
`

// Cambia la visibilidad de un item en un template
func (q *Queries) ToggleItemVisibilityInTemplate(ctx context.Context, templateID pgtype.UUID, menuItemID pgtype.UUID, isVisible *bool) (AuthMenuTemplateItem, error) {
	row := q.db.QueryRow(ctx, toggleItemVisibilityInTemplate, templateID, menuItemID, isVisible)
	var i AuthMenuTemplateItem
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.MenuItemID,
		&i.DisplayOrder,
		&i.IsVisible,
		&i.CreatedAt,
	)
	return i, err
}

const updateItemOrderInTemplate = `-- name: UpdateItemOrderInTemplate :exec
UPDATE auth.menu_template_items
SET display_order = $3
WHERE template_id = $1 AND menu_item_id = $2
`

// Actualiza el orden de un item en un template
func (q *Queries) UpdateItemOrderInTemplate(ctx context.Context, templateID pgtype.UUID, menuItemID pgtype.UUID, displayOrder *int32) error {
	_, err := q.db.Exec(ctx, updateItemOrderInTemplate, templateID, menuItemID, displayOrder)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE auth.users
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE auth.roles
SET name = $3,
    description = $4
WHERE id = $1
    AND tenant_id = $2
    AND is_system = false
RETURNING id, tenant_id, name, description, is_system, created_at
`

func (q *Queries) UpdateRole(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, name string, description *string) (AuthRole, error) {
	row := q.db.QueryRow(ctx, updateRole,
		iD,
		tenantID,
		name,
		description,
	)
	var i AuthRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const updateRoleGlobal = `-- name: UpdateRoleGlobal :one
UPDATE auth.roles
SET name = $2,
    description = $3
WHERE id = $1
RETURNING id, tenant_id, name, description, is_system, created_at
`

func (q *Queries) UpdateRoleGlobal(ctx context.Context, iD pgtype.UUID, name string, description *string) (AuthRole, error) {
	row := q.db.QueryRow(ctx, updateRoleGlobal, iD, name, description)
	var i AuthRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE auth.users
SET first_name = $3,
    last_name = $4,
    phone = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
RETURNING id, tenant_id, email, password_hash, first_name, last_name, phone, avatar_url, is_active, email_verified, last_login_at, created_at, updated_at, created_by, updated_by
`

func (q *Queries) UpdateUser(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, firstName string, lastName string, phone *string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		iD,
		tenantID,
		firstName,
		lastName,
		phone,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE auth.users
SET avatar_url = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
RETURNING id, tenant_id, email, password_hash, first_name, last_name, phone, avatar_url, is_active, email_verified, last_login_at, created_at, updated_at, created_by, updated_by
`

func (q *Queries) UpdateUserAvatar(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, avatarUrl *string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, iD, tenantID, avatarUrl)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE auth.users
SET password_hash = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) UpdateUserPassword(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, passwordHash string) error {
	_, err := q.db.Exec(ctx, updateUserPassword, iD, tenantID, passwordHash)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE auth.users
SET email_verified = true,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) VerifyUserEmail(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, iD, tenantID)
	return err
}
