// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO policies.clients (
        tenant_id,
        company_name,
        legal_name,
        rfc,
        address,
        city,
        state,
        postal_code,
        email,
        phone
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, company_name, legal_name, rfc, address, city, state, postal_code, country, email, phone, is_active, metadata, created_at, updated_at
`

// internal/database/queries/clients.sql
// Queries para clientes y sitios
func (q *Queries) CreateClient(ctx context.Context, tenantID pgtype.UUID, companyName string, legalName *string, rfc *string, address *string, city *string, state *string, postalCode *string, email *string, phone *string) (PoliciesClient, error) {
	row := q.db.QueryRow(ctx, createClient,
		tenantID,
		companyName,
		legalName,
		rfc,
		address,
		city,
		state,
		postalCode,
		email,
		phone,
	)
	var i PoliciesClient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyName,
		&i.LegalName,
		&i.Rfc,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClientContact = `-- name: CreateClientContact :one
INSERT INTO policies.client_contacts (
        tenant_id,
        client_id,
        name,
        position,
        email,
        phone,
        is_primary
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, client_id, name, position, email, phone, mobile, is_primary, notes, created_at
`

// Client Contacts
func (q *Queries) CreateClientContact(ctx context.Context, tenantID pgtype.UUID, clientID pgtype.UUID, name string, position *string, email *string, phone *string, isPrimary *bool) (PoliciesClientContact, error) {
	row := q.db.QueryRow(ctx, createClientContact,
		tenantID,
		clientID,
		name,
		position,
		email,
		phone,
		isPrimary,
	)
	var i PoliciesClientContact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.Position,
		&i.Email,
		&i.Phone,
		&i.Mobile,
		&i.IsPrimary,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createSite = `-- name: CreateSite :one
INSERT INTO policies.sites (
        tenant_id,
        client_id,
        name,
        address,
        city,
        state,
        postal_code,
        latitude,
        longitude,
        contact_name,
        contact_phone
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11
    )
RETURNING id, tenant_id, client_id, name, address, city, state, postal_code, latitude, longitude, contact_name, contact_phone, is_active, metadata, created_at, updated_at
`

type CreateSiteParams struct {
	TenantID     pgtype.UUID    `db:"tenant_id" json:"tenant_id"`
	ClientID     pgtype.UUID    `db:"client_id" json:"client_id"`
	Name         string         `db:"name" json:"name"`
	Address      *string        `db:"address" json:"address"`
	City         *string        `db:"city" json:"city"`
	State        *string        `db:"state" json:"state"`
	PostalCode   *string        `db:"postal_code" json:"postal_code"`
	Latitude     pgtype.Numeric `db:"latitude" json:"latitude"`
	Longitude    pgtype.Numeric `db:"longitude" json:"longitude"`
	ContactName  *string        `db:"contact_name" json:"contact_name"`
	ContactPhone *string        `db:"contact_phone" json:"contact_phone"`
}

// Sites
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (PoliciesSite, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.TenantID,
		arg.ClientID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Latitude,
		arg.Longitude,
		arg.ContactName,
		arg.ContactPhone,
	)
	var i PoliciesSite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.ContactName,
		&i.ContactPhone,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateClient = `-- name: DeactivateClient :exec
UPDATE policies.clients
SET is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) DeactivateClient(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateClient, iD, tenantID)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, tenant_id, company_name, legal_name, rfc, address, city, state, postal_code, country, email, phone, is_active, metadata, created_at, updated_at
FROM policies.clients
WHERE id = $1
    AND tenant_id = $2
LIMIT 1
`

func (q *Queries) GetClientByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (PoliciesClient, error) {
	row := q.db.QueryRow(ctx, getClientByID, iD, tenantID)
	var i PoliciesClient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyName,
		&i.LegalName,
		&i.Rfc,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, tenant_id, client_id, name, address, city, state, postal_code, latitude, longitude, contact_name, contact_phone, is_active, metadata, created_at, updated_at
FROM policies.sites
WHERE id = $1
    AND tenant_id = $2
LIMIT 1
`

func (q *Queries) GetSiteByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (PoliciesSite, error) {
	row := q.db.QueryRow(ctx, getSiteByID, iD, tenantID)
	var i PoliciesSite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.ContactName,
		&i.ContactPhone,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClientContacts = `-- name: ListClientContacts :many
SELECT id, tenant_id, client_id, name, position, email, phone, mobile, is_primary, notes, created_at
FROM policies.client_contacts
WHERE client_id = $1
    AND tenant_id = $2
ORDER BY is_primary DESC,
    name
`

func (q *Queries) ListClientContacts(ctx context.Context, clientID pgtype.UUID, tenantID pgtype.UUID) ([]PoliciesClientContact, error) {
	rows, err := q.db.Query(ctx, listClientContacts, clientID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoliciesClientContact{}
	for rows.Next() {
		var i PoliciesClientContact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.Name,
			&i.Position,
			&i.Email,
			&i.Phone,
			&i.Mobile,
			&i.IsPrimary,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsByTenant = `-- name: ListClientsByTenant :many
SELECT id, tenant_id, company_name, legal_name, rfc, address, city, state, postal_code, country, email, phone, is_active, metadata, created_at, updated_at
FROM policies.clients
WHERE tenant_id = $1
    AND is_active = true
ORDER BY company_name
LIMIT $2 OFFSET $3
`

func (q *Queries) ListClientsByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]PoliciesClient, error) {
	rows, err := q.db.Query(ctx, listClientsByTenant, tenantID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoliciesClient{}
	for rows.Next() {
		var i PoliciesClient
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyName,
			&i.LegalName,
			&i.Rfc,
			&i.Address,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Email,
			&i.Phone,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesByClient = `-- name: ListSitesByClient :many
SELECT id, tenant_id, client_id, name, address, city, state, postal_code, latitude, longitude, contact_name, contact_phone, is_active, metadata, created_at, updated_at
FROM policies.sites
WHERE client_id = $1
    AND tenant_id = $2
    AND is_active = true
ORDER BY name
`

func (q *Queries) ListSitesByClient(ctx context.Context, clientID pgtype.UUID, tenantID pgtype.UUID) ([]PoliciesSite, error) {
	rows, err := q.db.Query(ctx, listSitesByClient, clientID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoliciesSite{}
	for rows.Next() {
		var i PoliciesSite
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Latitude,
			&i.Longitude,
			&i.ContactName,
			&i.ContactPhone,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT id, tenant_id, company_name, legal_name, rfc, address, city, state, postal_code, country, email, phone, is_active, metadata, created_at, updated_at
FROM policies.clients
WHERE tenant_id = $1
    AND is_active = true
    AND (
        company_name ILIKE $2
        OR rfc ILIKE $2
    )
ORDER BY company_name
LIMIT $3
`

func (q *Queries) SearchClients(ctx context.Context, tenantID pgtype.UUID, companyName string, limit int32) ([]PoliciesClient, error) {
	rows, err := q.db.Query(ctx, searchClients, tenantID, companyName, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoliciesClient{}
	for rows.Next() {
		var i PoliciesClient
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyName,
			&i.LegalName,
			&i.Rfc,
			&i.Address,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Email,
			&i.Phone,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE policies.clients
SET company_name = $3,
    legal_name = $4,
    rfc = $5,
    address = $6,
    city = $7,
    state = $8,
    postal_code = $9,
    email = $10,
    phone = $11,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
RETURNING id, tenant_id, company_name, legal_name, rfc, address, city, state, postal_code, country, email, phone, is_active, metadata, created_at, updated_at
`

type UpdateClientParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	TenantID    pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	CompanyName string      `db:"company_name" json:"company_name"`
	LegalName   *string     `db:"legal_name" json:"legal_name"`
	Rfc         *string     `db:"rfc" json:"rfc"`
	Address     *string     `db:"address" json:"address"`
	City        *string     `db:"city" json:"city"`
	State       *string     `db:"state" json:"state"`
	PostalCode  *string     `db:"postal_code" json:"postal_code"`
	Email       *string     `db:"email" json:"email"`
	Phone       *string     `db:"phone" json:"phone"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (PoliciesClient, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.TenantID,
		arg.CompanyName,
		arg.LegalName,
		arg.Rfc,
		arg.Address,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Email,
		arg.Phone,
	)
	var i PoliciesClient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyName,
		&i.LegalName,
		&i.Rfc,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Email,
		&i.Phone,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSite = `-- name: UpdateSite :one
UPDATE policies.sites
SET name = $3,
    address = $4,
    city = $5,
    state = $6,
    latitude = $7,
    longitude = $8,
    contact_name = $9,
    contact_phone = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
RETURNING id, tenant_id, client_id, name, address, city, state, postal_code, latitude, longitude, contact_name, contact_phone, is_active, metadata, created_at, updated_at
`

func (q *Queries) UpdateSite(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, name string, address *string, city *string, state *string, latitude pgtype.Numeric, longitude pgtype.Numeric, contactName *string, contactPhone *string) (PoliciesSite, error) {
	row := q.db.QueryRow(ctx, updateSite,
		iD,
		tenantID,
		name,
		address,
		city,
		state,
		latitude,
		longitude,
		contactName,
		contactPhone,
	)
	var i PoliciesSite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.ContactName,
		&i.ContactPhone,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
