// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForCreateImportBatchItemsBulk implements pgx.CopyFromSource.
type iteratorForCreateImportBatchItemsBulk struct {
	rows                 []CreateImportBatchItemsBulkParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateImportBatchItemsBulk) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateImportBatchItemsBulk) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TenantID,
		r.rows[0].BatchID,
		r.rows[0].RowNumber,
		r.rows[0].RawData,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForCreateImportBatchItemsBulk) Err() error {
	return nil
}

func (q *Queries) CreateImportBatchItemsBulk(ctx context.Context, arg []CreateImportBatchItemsBulkParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"inventory", "import_batch_items"}, []string{"tenant_id", "batch_id", "row_number", "raw_data", "status"}, &iteratorForCreateImportBatchItemsBulk{rows: arg})
}
