// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClientStats = `-- name: GetClientStats :one

SELECT 
    COUNT(*) as total_clients,
    COUNT(*) FILTER (WHERE is_active = true) as active_clients,
    COUNT(*) FILTER (WHERE is_active = false) as inactive_clients
FROM policies.clients
WHERE tenant_id = $1
`

type GetClientStatsRow struct {
	TotalClients    int64 `db:"total_clients" json:"total_clients"`
	ActiveClients   int64 `db:"active_clients" json:"active_clients"`
	InactiveClients int64 `db:"inactive_clients" json:"inactive_clients"`
}

// ==================== ESTADÍSTICAS DE CLIENTES ====================
// Estadísticas de clientes
func (q *Queries) GetClientStats(ctx context.Context, tenantID pgtype.UUID) (GetClientStatsRow, error) {
	row := q.db.QueryRow(ctx, getClientStats, tenantID)
	var i GetClientStatsRow
	err := row.Scan(&i.TotalClients, &i.ActiveClients, &i.InactiveClients)
	return i, err
}

const getDashboardSlaMetrics = `-- name: GetDashboardSlaMetrics :one
SELECT
    COUNT(*) FILTER (WHERE tsi.status = 'ok') AS ok_count,
    COUNT(*) FILTER (WHERE tsi.status = 'at_risk') AS at_risk_count,
    COUNT(*) FILTER (WHERE tsi.status = 'breached') AS breached_count,
    COUNT(*) FILTER (WHERE tsi.status = 'unknown') AS unknown_count,
    COUNT(*) AS total_count
FROM tickets.ticket_sla_instances tsi
WHERE tsi.tenant_id = $1
`

type GetDashboardSlaMetricsRow struct {
	OkCount       int64 `db:"ok_count" json:"ok_count"`
	AtRiskCount   int64 `db:"at_risk_count" json:"at_risk_count"`
	BreachedCount int64 `db:"breached_count" json:"breached_count"`
	UnknownCount  int64 `db:"unknown_count" json:"unknown_count"`
	TotalCount    int64 `db:"total_count" json:"total_count"`
}

func (q *Queries) GetDashboardSlaMetrics(ctx context.Context, tenantID pgtype.UUID) (GetDashboardSlaMetricsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSlaMetrics, tenantID)
	var i GetDashboardSlaMetricsRow
	err := row.Scan(
		&i.OkCount,
		&i.AtRiskCount,
		&i.BreachedCount,
		&i.UnknownCount,
		&i.TotalCount,
	)
	return i, err
}

const getDashboardSummary = `-- name: GetDashboardSummary :one

SELECT 
    -- Tickets
    (SELECT COUNT(*) FROM tickets.tickets t WHERE t.tenant_id = $1 AND t.status IN ('open', 'assigned', 'in_progress')) as open_tickets,
    (SELECT COUNT(*) FROM tickets.tickets t WHERE t.tenant_id = $1 AND t.priority = 'critical' AND t.status NOT IN ('completed', 'cancelled')) as critical_tickets,
    (SELECT COALESCE(
        ROUND(100.0 * COUNT(*) FILTER (WHERE t.sla_met = true) / NULLIF(COUNT(*) FILTER (WHERE t.sla_met IS NOT NULL), 0), 1),
        100
    ) FROM tickets.tickets t WHERE t.tenant_id = $1 AND t.created_at >= CURRENT_DATE - 30) as sla_compliance_pct,
    (SELECT COUNT(*) FROM tickets.ticket_sla_instances tsi WHERE tsi.tenant_id = $1 AND tsi.status = 'ok') as sla_ok_tickets,
    (SELECT COUNT(*) FROM tickets.ticket_sla_instances tsi WHERE tsi.tenant_id = $1 AND tsi.status = 'at_risk') as sla_at_risk_tickets,
    (SELECT COUNT(*) FROM tickets.ticket_sla_instances tsi WHERE tsi.tenant_id = $1 AND tsi.status = 'breached') as sla_breached_tickets,
    
    -- Clientes
    (SELECT COUNT(*) FROM policies.clients c WHERE c.tenant_id = $1 AND c.is_active = true) as active_clients,
    
    -- Pólizas
    (SELECT COUNT(*) FROM policies.policies p WHERE p.tenant_id = $1 AND p.status = 'active') as active_policies,
    (SELECT COUNT(*) FROM policies.policies p WHERE p.tenant_id = $1 AND p.status = 'active' AND p.end_date BETWEEN CURRENT_DATE AND CURRENT_DATE + 30) as policies_expiring_soon,
    
    -- Facturación
    (SELECT COALESCE(SUM(i.balance), 0) FROM billing.invoices i WHERE i.tenant_id = $1 AND i.status = 'overdue') as overdue_amount,
    (SELECT COALESCE(SUM(i.total), 0) FROM billing.invoices i WHERE i.tenant_id = $1 AND DATE_TRUNC('month', i.issue_date) = DATE_TRUNC('month', CURRENT_DATE)) as current_month_revenue,
    
    -- Usuarios
    (SELECT COUNT(*) FROM auth.users u WHERE u.tenant_id = $1 AND u.is_active = true) as active_users,
    (SELECT COUNT(*) FROM auth.users u WHERE u.tenant_id = $1 AND u.last_login_at >= CURRENT_DATE) as users_online_today,
    
    -- Inventario
    (SELECT COUNT(*) FROM inventory.nvr_servers n WHERE n.tenant_id = $1 AND n.status = 'active') as active_nvrs,
    (SELECT COUNT(*) FROM inventory.cameras c WHERE c.tenant_id = $1 AND c.status = 'active') as active_cameras,
    (SELECT COALESCE(SUM(n.total_storage_tb), 0) FROM inventory.nvr_servers n WHERE n.tenant_id = $1) as total_storage_tb,
    
    -- Storage
    (SELECT COALESCE(SUM(f.file_size), 0) FROM storage.files f WHERE f.tenant_id = $1) as total_file_size_bytes
`

type GetDashboardSummaryRow struct {
	OpenTickets          int64       `db:"open_tickets" json:"open_tickets"`
	CriticalTickets      int64       `db:"critical_tickets" json:"critical_tickets"`
	SlaCompliancePct     interface{} `db:"sla_compliance_pct" json:"sla_compliance_pct"`
	SlaOkTickets         int64       `db:"sla_ok_tickets" json:"sla_ok_tickets"`
	SlaAtRiskTickets     int64       `db:"sla_at_risk_tickets" json:"sla_at_risk_tickets"`
	SlaBreachedTickets   int64       `db:"sla_breached_tickets" json:"sla_breached_tickets"`
	ActiveClients        int64       `db:"active_clients" json:"active_clients"`
	ActivePolicies       int64       `db:"active_policies" json:"active_policies"`
	PoliciesExpiringSoon int64       `db:"policies_expiring_soon" json:"policies_expiring_soon"`
	OverdueAmount        interface{} `db:"overdue_amount" json:"overdue_amount"`
	CurrentMonthRevenue  interface{} `db:"current_month_revenue" json:"current_month_revenue"`
	ActiveUsers          int64       `db:"active_users" json:"active_users"`
	UsersOnlineToday     int64       `db:"users_online_today" json:"users_online_today"`
	ActiveNvrs           int64       `db:"active_nvrs" json:"active_nvrs"`
	ActiveCameras        int64       `db:"active_cameras" json:"active_cameras"`
	TotalStorageTb       interface{} `db:"total_storage_tb" json:"total_storage_tb"`
	TotalFileSizeBytes   interface{} `db:"total_file_size_bytes" json:"total_file_size_bytes"`
}

// ==================== RESUMEN EJECUTIVO (DASHBOARD PRINCIPAL) ====================
// Resumen ejecutivo para el dashboard principal
func (q *Queries) GetDashboardSummary(ctx context.Context, tenantID pgtype.UUID) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary, tenantID)
	var i GetDashboardSummaryRow
	err := row.Scan(
		&i.OpenTickets,
		&i.CriticalTickets,
		&i.SlaCompliancePct,
		&i.SlaOkTickets,
		&i.SlaAtRiskTickets,
		&i.SlaBreachedTickets,
		&i.ActiveClients,
		&i.ActivePolicies,
		&i.PoliciesExpiringSoon,
		&i.OverdueAmount,
		&i.CurrentMonthRevenue,
		&i.ActiveUsers,
		&i.UsersOnlineToday,
		&i.ActiveNvrs,
		&i.ActiveCameras,
		&i.TotalStorageTb,
		&i.TotalFileSizeBytes,
	)
	return i, err
}

const getDashboardTicketStats = `-- name: GetDashboardTicketStats :one


SELECT 
    COUNT(*) FILTER (WHERE status = 'open') as open_count,
    COUNT(*) FILTER (WHERE status = 'assigned') as assigned_count,
    COUNT(*) FILTER (WHERE status = 'in_progress') as in_progress_count,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_count,
    COUNT(*) FILTER (WHERE status = 'cancelled') as cancelled_count,
    COUNT(*) FILTER (WHERE priority = 'critical') as critical_count,
    COUNT(*) FILTER (WHERE priority = 'high') as high_priority_count,
    COUNT(*) FILTER (WHERE type = 'preventive') as preventive_count,
    COUNT(*) FILTER (WHERE type = 'corrective') as corrective_count,
    COUNT(*) FILTER (WHERE type = 'emergency') as emergency_count,
    COUNT(*) as total_count,
    COUNT(*) FILTER (WHERE sla_met = true) as sla_met_count,
    COUNT(*) FILTER (WHERE sla_met = false) as sla_missed_count
FROM tickets.tickets
WHERE tenant_id = $1
`

type GetDashboardTicketStatsRow struct {
	OpenCount         int64 `db:"open_count" json:"open_count"`
	AssignedCount     int64 `db:"assigned_count" json:"assigned_count"`
	InProgressCount   int64 `db:"in_progress_count" json:"in_progress_count"`
	CompletedCount    int64 `db:"completed_count" json:"completed_count"`
	CancelledCount    int64 `db:"cancelled_count" json:"cancelled_count"`
	CriticalCount     int64 `db:"critical_count" json:"critical_count"`
	HighPriorityCount int64 `db:"high_priority_count" json:"high_priority_count"`
	PreventiveCount   int64 `db:"preventive_count" json:"preventive_count"`
	CorrectiveCount   int64 `db:"corrective_count" json:"corrective_count"`
	EmergencyCount    int64 `db:"emergency_count" json:"emergency_count"`
	TotalCount        int64 `db:"total_count" json:"total_count"`
	SlaMetCount       int64 `db:"sla_met_count" json:"sla_met_count"`
	SlaMissedCount    int64 `db:"sla_missed_count" json:"sla_missed_count"`
}

// internal/database/queries/dashboard.sql
// Queries para el dashboard principal y estadísticas
// ==================== ESTADÍSTICAS DE TICKETS ====================
// Obtiene estadísticas generales de tickets por tenant
func (q *Queries) GetDashboardTicketStats(ctx context.Context, tenantID pgtype.UUID) (GetDashboardTicketStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardTicketStats, tenantID)
	var i GetDashboardTicketStatsRow
	err := row.Scan(
		&i.OpenCount,
		&i.AssignedCount,
		&i.InProgressCount,
		&i.CompletedCount,
		&i.CancelledCount,
		&i.CriticalCount,
		&i.HighPriorityCount,
		&i.PreventiveCount,
		&i.CorrectiveCount,
		&i.EmergencyCount,
		&i.TotalCount,
		&i.SlaMetCount,
		&i.SlaMissedCount,
	)
	return i, err
}

const getDashboardUsersByRole = `-- name: GetDashboardUsersByRole :many
SELECT 
    r.name as role_name,
    COUNT(ur.user_id) as user_count
FROM auth.roles r
LEFT JOIN auth.user_roles ur ON r.id = ur.role_id
LEFT JOIN auth.users u ON ur.user_id = u.id AND u.is_active = true
WHERE (r.tenant_id = $1 OR r.is_system = true)
GROUP BY r.id, r.name
ORDER BY user_count DESC
`

type GetDashboardUsersByRoleRow struct {
	RoleName  string `db:"role_name" json:"role_name"`
	UserCount int64  `db:"user_count" json:"user_count"`
}

// Usuarios por rol (para dashboard)
func (q *Queries) GetDashboardUsersByRole(ctx context.Context, tenantID pgtype.UUID) ([]GetDashboardUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, getDashboardUsersByRole, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDashboardUsersByRoleRow{}
	for rows.Next() {
		var i GetDashboardUsersByRoleRow
		if err := rows.Scan(&i.RoleName, &i.UserCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryStats = `-- name: GetInventoryStats :one

SELECT 
    (SELECT COUNT(*) FROM inventory.nvr_servers n WHERE n.tenant_id = $1) as total_nvrs,
    (SELECT COUNT(*) FROM inventory.nvr_servers n WHERE n.tenant_id = $1 AND n.status = 'active') as active_nvrs,
    (SELECT COUNT(*) FROM inventory.cameras c WHERE c.tenant_id = $1) as total_cameras,
    (SELECT COUNT(*) FROM inventory.cameras c WHERE c.tenant_id = $1 AND c.status = 'active') as active_cameras,
    (SELECT COALESCE(SUM(n.total_storage_tb), 0) FROM inventory.nvr_servers n WHERE n.tenant_id = $1) as total_storage_tb
`

type GetInventoryStatsRow struct {
	TotalNvrs      int64       `db:"total_nvrs" json:"total_nvrs"`
	ActiveNvrs     int64       `db:"active_nvrs" json:"active_nvrs"`
	TotalCameras   int64       `db:"total_cameras" json:"total_cameras"`
	ActiveCameras  int64       `db:"active_cameras" json:"active_cameras"`
	TotalStorageTb interface{} `db:"total_storage_tb" json:"total_storage_tb"`
}

// ==================== ESTADÍSTICAS DE INVENTARIO ====================
// Estadísticas de inventario
func (q *Queries) GetInventoryStats(ctx context.Context, tenantID pgtype.UUID) (GetInventoryStatsRow, error) {
	row := q.db.QueryRow(ctx, getInventoryStats, tenantID)
	var i GetInventoryStatsRow
	err := row.Scan(
		&i.TotalNvrs,
		&i.ActiveNvrs,
		&i.TotalCameras,
		&i.ActiveCameras,
		&i.TotalStorageTb,
	)
	return i, err
}

const getInvoiceStats = `-- name: GetInvoiceStats :one

SELECT 
    COUNT(*) as total_invoices,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_count,
    COUNT(*) FILTER (WHERE status = 'paid') as paid_count,
    COUNT(*) FILTER (WHERE status = 'overdue') as overdue_count,
    COALESCE(SUM(total) FILTER (WHERE status = 'pending'), 0) as pending_amount,
    COALESCE(SUM(total) FILTER (WHERE status = 'paid'), 0) as paid_amount,
    COALESCE(SUM(balance) FILTER (WHERE status = 'overdue'), 0) as overdue_amount,
    COALESCE(SUM(total) FILTER (WHERE DATE_TRUNC('month', issue_date) = DATE_TRUNC('month', CURRENT_DATE)), 0) as current_month_total,
    COALESCE(SUM(total) FILTER (WHERE DATE_TRUNC('month', issue_date) = DATE_TRUNC('month', CURRENT_DATE - INTERVAL '1 month')), 0) as last_month_total
FROM billing.invoices
WHERE tenant_id = $1
`

type GetInvoiceStatsRow struct {
	TotalInvoices     int64       `db:"total_invoices" json:"total_invoices"`
	PendingCount      int64       `db:"pending_count" json:"pending_count"`
	PaidCount         int64       `db:"paid_count" json:"paid_count"`
	OverdueCount      int64       `db:"overdue_count" json:"overdue_count"`
	PendingAmount     interface{} `db:"pending_amount" json:"pending_amount"`
	PaidAmount        interface{} `db:"paid_amount" json:"paid_amount"`
	OverdueAmount     interface{} `db:"overdue_amount" json:"overdue_amount"`
	CurrentMonthTotal interface{} `db:"current_month_total" json:"current_month_total"`
	LastMonthTotal    interface{} `db:"last_month_total" json:"last_month_total"`
}

// ==================== ESTADÍSTICAS DE FACTURACIÓN ====================
// Estadísticas de facturación
func (q *Queries) GetInvoiceStats(ctx context.Context, tenantID pgtype.UUID) (GetInvoiceStatsRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceStats, tenantID)
	var i GetInvoiceStatsRow
	err := row.Scan(
		&i.TotalInvoices,
		&i.PendingCount,
		&i.PaidCount,
		&i.OverdueCount,
		&i.PendingAmount,
		&i.PaidAmount,
		&i.OverdueAmount,
		&i.CurrentMonthTotal,
		&i.LastMonthTotal,
	)
	return i, err
}

const getPolicyStats = `-- name: GetPolicyStats :one

SELECT 
    COUNT(*) as total_policies,
    COUNT(*) FILTER (WHERE status = 'active') as active_policies,
    COUNT(*) FILTER (WHERE status = 'expired') as expired_policies,
    COUNT(*) FILTER (WHERE status = 'suspended') as suspended_policies,
    COUNT(*) FILTER (WHERE end_date BETWEEN CURRENT_DATE AND CURRENT_DATE + 30) as expiring_soon,
    COALESCE(SUM(monthly_payment), 0) as total_monthly_revenue
FROM policies.policies
WHERE tenant_id = $1
`

type GetPolicyStatsRow struct {
	TotalPolicies       int64       `db:"total_policies" json:"total_policies"`
	ActivePolicies      int64       `db:"active_policies" json:"active_policies"`
	ExpiredPolicies     int64       `db:"expired_policies" json:"expired_policies"`
	SuspendedPolicies   int64       `db:"suspended_policies" json:"suspended_policies"`
	ExpiringSoon        int64       `db:"expiring_soon" json:"expiring_soon"`
	TotalMonthlyRevenue interface{} `db:"total_monthly_revenue" json:"total_monthly_revenue"`
}

// ==================== ESTADÍSTICAS DE PÓLIZAS ====================
// Estadísticas de pólizas
func (q *Queries) GetPolicyStats(ctx context.Context, tenantID pgtype.UUID) (GetPolicyStatsRow, error) {
	row := q.db.QueryRow(ctx, getPolicyStats, tenantID)
	var i GetPolicyStatsRow
	err := row.Scan(
		&i.TotalPolicies,
		&i.ActivePolicies,
		&i.ExpiredPolicies,
		&i.SuspendedPolicies,
		&i.ExpiringSoon,
		&i.TotalMonthlyRevenue,
	)
	return i, err
}

const getTicketsByTechnician = `-- name: GetTicketsByTechnician :many
SELECT 
    u.id as technician_id,
    u.first_name || ' ' || u.last_name as technician_name,
    COUNT(*) FILTER (WHERE t.status IN ('open', 'assigned', 'in_progress')) as active_tickets,
    COUNT(*) FILTER (WHERE t.status = 'completed') as completed_tickets,
    COUNT(*) as total_tickets,
    COALESCE(AVG(t.rating)::numeric, 0) as avg_rating
FROM auth.users u
LEFT JOIN tickets.tickets t ON t.assigned_to = u.id
WHERE u.tenant_id = $1
GROUP BY u.id, u.first_name, u.last_name
HAVING COUNT(t.id) > 0
ORDER BY active_tickets DESC
`

type GetTicketsByTechnicianRow struct {
	TechnicianID     pgtype.UUID `db:"technician_id" json:"technician_id"`
	TechnicianName   interface{} `db:"technician_name" json:"technician_name"`
	ActiveTickets    int64       `db:"active_tickets" json:"active_tickets"`
	CompletedTickets int64       `db:"completed_tickets" json:"completed_tickets"`
	TotalTickets     int64       `db:"total_tickets" json:"total_tickets"`
	AvgRating        interface{} `db:"avg_rating" json:"avg_rating"`
}

// Tickets asignados por técnico
func (q *Queries) GetTicketsByTechnician(ctx context.Context, tenantID pgtype.UUID) ([]GetTicketsByTechnicianRow, error) {
	rows, err := q.db.Query(ctx, getTicketsByTechnician, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketsByTechnicianRow{}
	for rows.Next() {
		var i GetTicketsByTechnicianRow
		if err := rows.Scan(
			&i.TechnicianID,
			&i.TechnicianName,
			&i.ActiveTickets,
			&i.CompletedTickets,
			&i.TotalTickets,
			&i.AvgRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsTrend = `-- name: GetTicketsTrend :many
SELECT 
    DATE(created_at) as date,
    COUNT(*) FILTER (WHERE status IN ('open', 'assigned', 'in_progress')) as opened,
    COUNT(*) FILTER (WHERE status = 'completed') as completed,
    COUNT(*) as total
FROM tickets.tickets
WHERE tenant_id = $1 
    AND created_at >= CURRENT_DATE - $2::int
GROUP BY DATE(created_at)
ORDER BY date
`

type GetTicketsTrendRow struct {
	Date      pgtype.Date `db:"date" json:"date"`
	Opened    int64       `db:"opened" json:"opened"`
	Completed int64       `db:"completed" json:"completed"`
	Total     int64       `db:"total" json:"total"`
}

// Obtiene tendencia de tickets de los últimos N días
func (q *Queries) GetTicketsTrend(ctx context.Context, tenantID pgtype.UUID, column2 int32) ([]GetTicketsTrendRow, error) {
	rows, err := q.db.Query(ctx, getTicketsTrend, tenantID, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketsTrendRow{}
	for rows.Next() {
		var i GetTicketsTrendRow
		if err := rows.Scan(
			&i.Date,
			&i.Opened,
			&i.Completed,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one

SELECT 
    COUNT(*) as total_users,
    COUNT(*) FILTER (WHERE is_active = true) as active_users,
    COUNT(*) FILTER (WHERE is_active = false) as inactive_users,
    COUNT(*) FILTER (WHERE last_login_at >= CURRENT_DATE) as logged_in_today,
    COUNT(*) FILTER (WHERE last_login_at >= CURRENT_DATE - 7) as logged_in_week,
    COUNT(*) FILTER (WHERE last_login_at >= CURRENT_DATE - 30) as logged_in_month
FROM auth.users
WHERE tenant_id = $1
`

type GetUserStatsRow struct {
	TotalUsers    int64 `db:"total_users" json:"total_users"`
	ActiveUsers   int64 `db:"active_users" json:"active_users"`
	InactiveUsers int64 `db:"inactive_users" json:"inactive_users"`
	LoggedInToday int64 `db:"logged_in_today" json:"logged_in_today"`
	LoggedInWeek  int64 `db:"logged_in_week" json:"logged_in_week"`
	LoggedInMonth int64 `db:"logged_in_month" json:"logged_in_month"`
}

// ==================== ESTADÍSTICAS DE USUARIOS ====================
// Estadísticas de usuarios
func (q *Queries) GetUserStats(ctx context.Context, tenantID pgtype.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, tenantID)
	var i GetUserStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.InactiveUsers,
		&i.LoggedInToday,
		&i.LoggedInWeek,
		&i.LoggedInMonth,
	)
	return i, err
}
