// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_nvr.sql

package database

import (
	"context"
	"net"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNvrLicense = `-- name: CreateNvrLicense :one

INSERT INTO inventory.nvr_licenses (
    tenant_id, nvr_server_id, license_key, license_type, edition,
    total_licenses, used_licenses, issue_date, expiry_date, is_perpetual,
    is_active, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, tenant_id, nvr_server_id, license_key, license_type, edition, total_licenses, used_licenses, issue_date, expiry_date, is_perpetual, is_active, metadata, created_at, updated_at
`

type CreateNvrLicenseParams struct {
	TenantID      pgtype.UUID          `db:"tenant_id" json:"tenant_id"`
	NvrServerID   pgtype.UUID          `db:"nvr_server_id" json:"nvr_server_id"`
	LicenseKey    *string              `db:"license_key" json:"license_key"`
	LicenseType   InventoryLicenseType `db:"license_type" json:"license_type"`
	Edition       *string              `db:"edition" json:"edition"`
	TotalLicenses int32                `db:"total_licenses" json:"total_licenses"`
	UsedLicenses  int32                `db:"used_licenses" json:"used_licenses"`
	IssueDate     pgtype.Date          `db:"issue_date" json:"issue_date"`
	ExpiryDate    pgtype.Date          `db:"expiry_date" json:"expiry_date"`
	IsPerpetual   *bool                `db:"is_perpetual" json:"is_perpetual"`
	IsActive      *bool                `db:"is_active" json:"is_active"`
	Metadata      []byte               `db:"metadata" json:"metadata"`
}

// =============================================
// NVR LICENSES
// =============================================
func (q *Queries) CreateNvrLicense(ctx context.Context, arg CreateNvrLicenseParams) (InventoryNvrLicense, error) {
	row := q.db.QueryRow(ctx, createNvrLicense,
		arg.TenantID,
		arg.NvrServerID,
		arg.LicenseKey,
		arg.LicenseType,
		arg.Edition,
		arg.TotalLicenses,
		arg.UsedLicenses,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.IsPerpetual,
		arg.IsActive,
		arg.Metadata,
	)
	var i InventoryNvrLicense
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NvrServerID,
		&i.LicenseKey,
		&i.LicenseType,
		&i.Edition,
		&i.TotalLicenses,
		&i.UsedLicenses,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.IsPerpetual,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNvrServer = `-- name: CreateNvrServer :one


INSERT INTO inventory.nvr_servers (
    tenant_id, site_id, brand_id, name, code, vms_server_id,
    edition, vms_version, camera_channels, tpv_channels, lpr_channels,
    integration_connections, model, service_tag, service_code, processor,
    ram_gb, os_name, system_type, ip_address, subnet_mask, gateway,
    mac_address, total_storage_tb, recording_days, launch_date,
    warranty_expiry_date, installation_date, status, hardware_specs,
    network_config, metadata, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28,
    $29, $30, $31, $32, $33, $34
)
RETURNING id, tenant_id, site_id, brand_id, name, code, vms_server_id, edition, vms_version, camera_channels, tpv_channels, lpr_channels, integration_connections, model, service_tag, service_code, processor, ram_gb, os_name, system_type, ip_address, subnet_mask, gateway, mac_address, total_storage_tb, recording_days, launch_date, warranty_expiry_date, installation_date, status, admin_username, admin_password_encrypted, hardware_specs, network_config, metadata, notes, created_at, updated_at, created_by, updated_by
`

type CreateNvrServerParams struct {
	TenantID               pgtype.UUID                  `db:"tenant_id" json:"tenant_id"`
	SiteID                 pgtype.UUID                  `db:"site_id" json:"site_id"`
	BrandID                pgtype.UUID                  `db:"brand_id" json:"brand_id"`
	Name                   string                       `db:"name" json:"name"`
	Code                   *string                      `db:"code" json:"code"`
	VmsServerID            *string                      `db:"vms_server_id" json:"vms_server_id"`
	Edition                *string                      `db:"edition" json:"edition"`
	VmsVersion             *string                      `db:"vms_version" json:"vms_version"`
	CameraChannels         *int32                       `db:"camera_channels" json:"camera_channels"`
	TpvChannels            *int32                       `db:"tpv_channels" json:"tpv_channels"`
	LprChannels            *int32                       `db:"lpr_channels" json:"lpr_channels"`
	IntegrationConnections *int32                       `db:"integration_connections" json:"integration_connections"`
	Model                  *string                      `db:"model" json:"model"`
	ServiceTag             *string                      `db:"service_tag" json:"service_tag"`
	ServiceCode            *string                      `db:"service_code" json:"service_code"`
	Processor              *string                      `db:"processor" json:"processor"`
	RamGb                  *int32                       `db:"ram_gb" json:"ram_gb"`
	OsName                 *string                      `db:"os_name" json:"os_name"`
	SystemType             *string                      `db:"system_type" json:"system_type"`
	IpAddress              *netip.Addr                  `db:"ip_address" json:"ip_address"`
	SubnetMask             *netip.Addr                  `db:"subnet_mask" json:"subnet_mask"`
	Gateway                *netip.Addr                  `db:"gateway" json:"gateway"`
	MacAddress             net.HardwareAddr             `db:"mac_address" json:"mac_address"`
	TotalStorageTb         pgtype.Numeric               `db:"total_storage_tb" json:"total_storage_tb"`
	RecordingDays          *int32                       `db:"recording_days" json:"recording_days"`
	LaunchDate             pgtype.Date                  `db:"launch_date" json:"launch_date"`
	WarrantyExpiryDate     pgtype.Date                  `db:"warranty_expiry_date" json:"warranty_expiry_date"`
	InstallationDate       pgtype.Date                  `db:"installation_date" json:"installation_date"`
	Status                 NullInventoryEquipmentStatus `db:"status" json:"status"`
	HardwareSpecs          []byte                       `db:"hardware_specs" json:"hardware_specs"`
	NetworkConfig          []byte                       `db:"network_config" json:"network_config"`
	Metadata               []byte                       `db:"metadata" json:"metadata"`
	Notes                  *string                      `db:"notes" json:"notes"`
	CreatedBy              pgtype.UUID                  `db:"created_by" json:"created_by"`
}

// internal/database/queries/inventory_nvr.sql
// Queries SQLC para servidores NVR y licencias
// =============================================
// NVR SERVERS
// =============================================
func (q *Queries) CreateNvrServer(ctx context.Context, arg CreateNvrServerParams) (InventoryNvrServer, error) {
	row := q.db.QueryRow(ctx, createNvrServer,
		arg.TenantID,
		arg.SiteID,
		arg.BrandID,
		arg.Name,
		arg.Code,
		arg.VmsServerID,
		arg.Edition,
		arg.VmsVersion,
		arg.CameraChannels,
		arg.TpvChannels,
		arg.LprChannels,
		arg.IntegrationConnections,
		arg.Model,
		arg.ServiceTag,
		arg.ServiceCode,
		arg.Processor,
		arg.RamGb,
		arg.OsName,
		arg.SystemType,
		arg.IpAddress,
		arg.SubnetMask,
		arg.Gateway,
		arg.MacAddress,
		arg.TotalStorageTb,
		arg.RecordingDays,
		arg.LaunchDate,
		arg.WarrantyExpiryDate,
		arg.InstallationDate,
		arg.Status,
		arg.HardwareSpecs,
		arg.NetworkConfig,
		arg.Metadata,
		arg.Notes,
		arg.CreatedBy,
	)
	var i InventoryNvrServer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.BrandID,
		&i.Name,
		&i.Code,
		&i.VmsServerID,
		&i.Edition,
		&i.VmsVersion,
		&i.CameraChannels,
		&i.TpvChannels,
		&i.LprChannels,
		&i.IntegrationConnections,
		&i.Model,
		&i.ServiceTag,
		&i.ServiceCode,
		&i.Processor,
		&i.RamGb,
		&i.OsName,
		&i.SystemType,
		&i.IpAddress,
		&i.SubnetMask,
		&i.Gateway,
		&i.MacAddress,
		&i.TotalStorageTb,
		&i.RecordingDays,
		&i.LaunchDate,
		&i.WarrantyExpiryDate,
		&i.InstallationDate,
		&i.Status,
		&i.AdminUsername,
		&i.AdminPasswordEncrypted,
		&i.HardwareSpecs,
		&i.NetworkConfig,
		&i.Metadata,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const createNvrStorageUnit = `-- name: CreateNvrStorageUnit :one

INSERT INTO inventory.nvr_storage_units (
    tenant_id, nvr_server_id, slot_number, disk_type, brand, model,
    serial_number, capacity_tb, status, health_percentage, installation_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, tenant_id, nvr_server_id, slot_number, disk_type, brand, model, serial_number, capacity_tb, status, health_percentage, installation_date, created_at, updated_at
`

type CreateNvrStorageUnitParams struct {
	TenantID         pgtype.UUID    `db:"tenant_id" json:"tenant_id"`
	NvrServerID      pgtype.UUID    `db:"nvr_server_id" json:"nvr_server_id"`
	SlotNumber       *int32         `db:"slot_number" json:"slot_number"`
	DiskType         *string        `db:"disk_type" json:"disk_type"`
	Brand            *string        `db:"brand" json:"brand"`
	Model            *string        `db:"model" json:"model"`
	SerialNumber     *string        `db:"serial_number" json:"serial_number"`
	CapacityTb       pgtype.Numeric `db:"capacity_tb" json:"capacity_tb"`
	Status           *string        `db:"status" json:"status"`
	HealthPercentage *int32         `db:"health_percentage" json:"health_percentage"`
	InstallationDate pgtype.Date    `db:"installation_date" json:"installation_date"`
}

// =============================================
// NVR STORAGE UNITS
// =============================================
func (q *Queries) CreateNvrStorageUnit(ctx context.Context, arg CreateNvrStorageUnitParams) (InventoryNvrStorageUnit, error) {
	row := q.db.QueryRow(ctx, createNvrStorageUnit,
		arg.TenantID,
		arg.NvrServerID,
		arg.SlotNumber,
		arg.DiskType,
		arg.Brand,
		arg.Model,
		arg.SerialNumber,
		arg.CapacityTb,
		arg.Status,
		arg.HealthPercentage,
		arg.InstallationDate,
	)
	var i InventoryNvrStorageUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NvrServerID,
		&i.SlotNumber,
		&i.DiskType,
		&i.Brand,
		&i.Model,
		&i.SerialNumber,
		&i.CapacityTb,
		&i.Status,
		&i.HealthPercentage,
		&i.InstallationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNvrLicense = `-- name: DeleteNvrLicense :exec
DELETE FROM inventory.nvr_licenses
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) DeleteNvrLicense(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNvrLicense, iD, tenantID)
	return err
}

const deleteNvrServer = `-- name: DeleteNvrServer :exec
DELETE FROM inventory.nvr_servers
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) DeleteNvrServer(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNvrServer, iD, tenantID)
	return err
}

const deleteNvrStorageUnit = `-- name: DeleteNvrStorageUnit :exec
DELETE FROM inventory.nvr_storage_units
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) DeleteNvrStorageUnit(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNvrStorageUnit, iD, tenantID)
	return err
}

const getLicenseStats = `-- name: GetLicenseStats :one
SELECT 
    COUNT(*) as total_licenses,
    COUNT(*) FILTER (WHERE is_active = true) as active_licenses,
    COUNT(*) FILTER (WHERE is_perpetual = true) as perpetual_licenses,
    COUNT(*) FILTER (WHERE is_perpetual = false AND expiry_date < CURRENT_DATE) as expired_licenses,
    COALESCE(SUM(total_licenses), 0) as total_license_count,
    COALESCE(SUM(used_licenses), 0) as used_license_count
FROM inventory.nvr_licenses
WHERE tenant_id = $1
`

type GetLicenseStatsRow struct {
	TotalLicenses     int64       `db:"total_licenses" json:"total_licenses"`
	ActiveLicenses    int64       `db:"active_licenses" json:"active_licenses"`
	PerpetualLicenses int64       `db:"perpetual_licenses" json:"perpetual_licenses"`
	ExpiredLicenses   int64       `db:"expired_licenses" json:"expired_licenses"`
	TotalLicenseCount interface{} `db:"total_license_count" json:"total_license_count"`
	UsedLicenseCount  interface{} `db:"used_license_count" json:"used_license_count"`
}

func (q *Queries) GetLicenseStats(ctx context.Context, tenantID pgtype.UUID) (GetLicenseStatsRow, error) {
	row := q.db.QueryRow(ctx, getLicenseStats, tenantID)
	var i GetLicenseStatsRow
	err := row.Scan(
		&i.TotalLicenses,
		&i.ActiveLicenses,
		&i.PerpetualLicenses,
		&i.ExpiredLicenses,
		&i.TotalLicenseCount,
		&i.UsedLicenseCount,
	)
	return i, err
}

const getNvrLicenseByID = `-- name: GetNvrLicenseByID :one
SELECT 
    nl.id, nl.tenant_id, nl.nvr_server_id, nl.license_key, nl.license_type, nl.edition, nl.total_licenses, nl.used_licenses, nl.issue_date, nl.expiry_date, nl.is_perpetual, nl.is_active, nl.metadata, nl.created_at, nl.updated_at,
    nvr.name as nvr_name
FROM inventory.nvr_licenses nl
    LEFT JOIN inventory.nvr_servers nvr ON nl.nvr_server_id = nvr.id
WHERE nl.id = $1 AND nl.tenant_id = $2
LIMIT 1
`

type GetNvrLicenseByIDRow struct {
	ID            pgtype.UUID          `db:"id" json:"id"`
	TenantID      pgtype.UUID          `db:"tenant_id" json:"tenant_id"`
	NvrServerID   pgtype.UUID          `db:"nvr_server_id" json:"nvr_server_id"`
	LicenseKey    *string              `db:"license_key" json:"license_key"`
	LicenseType   InventoryLicenseType `db:"license_type" json:"license_type"`
	Edition       *string              `db:"edition" json:"edition"`
	TotalLicenses int32                `db:"total_licenses" json:"total_licenses"`
	UsedLicenses  int32                `db:"used_licenses" json:"used_licenses"`
	IssueDate     pgtype.Date          `db:"issue_date" json:"issue_date"`
	ExpiryDate    pgtype.Date          `db:"expiry_date" json:"expiry_date"`
	IsPerpetual   *bool                `db:"is_perpetual" json:"is_perpetual"`
	IsActive      *bool                `db:"is_active" json:"is_active"`
	Metadata      []byte               `db:"metadata" json:"metadata"`
	CreatedAt     pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz   `db:"updated_at" json:"updated_at"`
	NvrName       *string              `db:"nvr_name" json:"nvr_name"`
}

func (q *Queries) GetNvrLicenseByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetNvrLicenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getNvrLicenseByID, iD, tenantID)
	var i GetNvrLicenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NvrServerID,
		&i.LicenseKey,
		&i.LicenseType,
		&i.Edition,
		&i.TotalLicenses,
		&i.UsedLicenses,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.IsPerpetual,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NvrName,
	)
	return i, err
}

const getNvrServerByID = `-- name: GetNvrServerByID :one
SELECT 
    nvr.id, nvr.tenant_id, nvr.site_id, nvr.brand_id, nvr.name, nvr.code, nvr.vms_server_id, nvr.edition, nvr.vms_version, nvr.camera_channels, nvr.tpv_channels, nvr.lpr_channels, nvr.integration_connections, nvr.model, nvr.service_tag, nvr.service_code, nvr.processor, nvr.ram_gb, nvr.os_name, nvr.system_type, nvr.ip_address, nvr.subnet_mask, nvr.gateway, nvr.mac_address, nvr.total_storage_tb, nvr.recording_days, nvr.launch_date, nvr.warranty_expiry_date, nvr.installation_date, nvr.status, nvr.admin_username, nvr.admin_password_encrypted, nvr.hardware_specs, nvr.network_config, nvr.metadata, nvr.notes, nvr.created_at, nvr.updated_at, nvr.created_by, nvr.updated_by,
    b.name as brand_name,
    b.logo_url as brand_logo,
    s.name as site_name,
    s.address as site_address,
    (SELECT COUNT(*) FROM inventory.cameras c WHERE c.nvr_server_id = nvr.id) as camera_count,
    (SELECT COALESCE(SUM(nl.total_licenses), 0) FROM inventory.nvr_licenses nl WHERE nl.nvr_server_id = nvr.id AND nl.is_active = true) as total_licenses,
    (SELECT COALESCE(SUM(nl.used_licenses), 0) FROM inventory.nvr_licenses nl WHERE nl.nvr_server_id = nvr.id AND nl.is_active = true) as used_licenses
FROM inventory.nvr_servers nvr
    LEFT JOIN inventory.brands b ON nvr.brand_id = b.id
    LEFT JOIN policies.sites s ON nvr.site_id = s.id
WHERE nvr.id = $1 AND nvr.tenant_id = $2
LIMIT 1
`

type GetNvrServerByIDRow struct {
	ID                     pgtype.UUID                  `db:"id" json:"id"`
	TenantID               pgtype.UUID                  `db:"tenant_id" json:"tenant_id"`
	SiteID                 pgtype.UUID                  `db:"site_id" json:"site_id"`
	BrandID                pgtype.UUID                  `db:"brand_id" json:"brand_id"`
	Name                   string                       `db:"name" json:"name"`
	Code                   *string                      `db:"code" json:"code"`
	VmsServerID            *string                      `db:"vms_server_id" json:"vms_server_id"`
	Edition                *string                      `db:"edition" json:"edition"`
	VmsVersion             *string                      `db:"vms_version" json:"vms_version"`
	CameraChannels         *int32                       `db:"camera_channels" json:"camera_channels"`
	TpvChannels            *int32                       `db:"tpv_channels" json:"tpv_channels"`
	LprChannels            *int32                       `db:"lpr_channels" json:"lpr_channels"`
	IntegrationConnections *int32                       `db:"integration_connections" json:"integration_connections"`
	Model                  *string                      `db:"model" json:"model"`
	ServiceTag             *string                      `db:"service_tag" json:"service_tag"`
	ServiceCode            *string                      `db:"service_code" json:"service_code"`
	Processor              *string                      `db:"processor" json:"processor"`
	RamGb                  *int32                       `db:"ram_gb" json:"ram_gb"`
	OsName                 *string                      `db:"os_name" json:"os_name"`
	SystemType             *string                      `db:"system_type" json:"system_type"`
	IpAddress              *netip.Addr                  `db:"ip_address" json:"ip_address"`
	SubnetMask             *netip.Addr                  `db:"subnet_mask" json:"subnet_mask"`
	Gateway                *netip.Addr                  `db:"gateway" json:"gateway"`
	MacAddress             net.HardwareAddr             `db:"mac_address" json:"mac_address"`
	TotalStorageTb         pgtype.Numeric               `db:"total_storage_tb" json:"total_storage_tb"`
	RecordingDays          *int32                       `db:"recording_days" json:"recording_days"`
	LaunchDate             pgtype.Date                  `db:"launch_date" json:"launch_date"`
	WarrantyExpiryDate     pgtype.Date                  `db:"warranty_expiry_date" json:"warranty_expiry_date"`
	InstallationDate       pgtype.Date                  `db:"installation_date" json:"installation_date"`
	Status                 NullInventoryEquipmentStatus `db:"status" json:"status"`
	AdminUsername          *string                      `db:"admin_username" json:"admin_username"`
	AdminPasswordEncrypted *string                      `db:"admin_password_encrypted" json:"admin_password_encrypted"`
	HardwareSpecs          []byte                       `db:"hardware_specs" json:"hardware_specs"`
	NetworkConfig          []byte                       `db:"network_config" json:"network_config"`
	Metadata               []byte                       `db:"metadata" json:"metadata"`
	Notes                  *string                      `db:"notes" json:"notes"`
	CreatedAt              pgtype.Timestamptz           `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz           `db:"updated_at" json:"updated_at"`
	CreatedBy              pgtype.UUID                  `db:"created_by" json:"created_by"`
	UpdatedBy              pgtype.UUID                  `db:"updated_by" json:"updated_by"`
	BrandName              *string                      `db:"brand_name" json:"brand_name"`
	BrandLogo              *string                      `db:"brand_logo" json:"brand_logo"`
	SiteName               *string                      `db:"site_name" json:"site_name"`
	SiteAddress            *string                      `db:"site_address" json:"site_address"`
	CameraCount            int64                        `db:"camera_count" json:"camera_count"`
	TotalLicenses          interface{}                  `db:"total_licenses" json:"total_licenses"`
	UsedLicenses           interface{}                  `db:"used_licenses" json:"used_licenses"`
}

func (q *Queries) GetNvrServerByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetNvrServerByIDRow, error) {
	row := q.db.QueryRow(ctx, getNvrServerByID, iD, tenantID)
	var i GetNvrServerByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.BrandID,
		&i.Name,
		&i.Code,
		&i.VmsServerID,
		&i.Edition,
		&i.VmsVersion,
		&i.CameraChannels,
		&i.TpvChannels,
		&i.LprChannels,
		&i.IntegrationConnections,
		&i.Model,
		&i.ServiceTag,
		&i.ServiceCode,
		&i.Processor,
		&i.RamGb,
		&i.OsName,
		&i.SystemType,
		&i.IpAddress,
		&i.SubnetMask,
		&i.Gateway,
		&i.MacAddress,
		&i.TotalStorageTb,
		&i.RecordingDays,
		&i.LaunchDate,
		&i.WarrantyExpiryDate,
		&i.InstallationDate,
		&i.Status,
		&i.AdminUsername,
		&i.AdminPasswordEncrypted,
		&i.HardwareSpecs,
		&i.NetworkConfig,
		&i.Metadata,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.BrandName,
		&i.BrandLogo,
		&i.SiteName,
		&i.SiteAddress,
		&i.CameraCount,
		&i.TotalLicenses,
		&i.UsedLicenses,
	)
	return i, err
}

const getNvrServerStats = `-- name: GetNvrServerStats :one
SELECT 
    COUNT(*) as total_servers,
    COUNT(*) FILTER (WHERE status = 'active') as active_servers,
    COUNT(*) FILTER (WHERE status = 'inactive') as inactive_servers,
    COUNT(*) FILTER (WHERE status = 'under_maintenance') as maintenance_servers,
    COALESCE(SUM(camera_channels), 0) as total_camera_channels,
    COALESCE(SUM(total_storage_tb), 0) as total_storage_tb,
    COALESCE(SUM(ram_gb), 0) as total_ram_gb
FROM inventory.nvr_servers
WHERE tenant_id = $1
`

type GetNvrServerStatsRow struct {
	TotalServers        int64       `db:"total_servers" json:"total_servers"`
	ActiveServers       int64       `db:"active_servers" json:"active_servers"`
	InactiveServers     int64       `db:"inactive_servers" json:"inactive_servers"`
	MaintenanceServers  int64       `db:"maintenance_servers" json:"maintenance_servers"`
	TotalCameraChannels interface{} `db:"total_camera_channels" json:"total_camera_channels"`
	TotalStorageTb      interface{} `db:"total_storage_tb" json:"total_storage_tb"`
	TotalRamGb          interface{} `db:"total_ram_gb" json:"total_ram_gb"`
}

func (q *Queries) GetNvrServerStats(ctx context.Context, tenantID pgtype.UUID) (GetNvrServerStatsRow, error) {
	row := q.db.QueryRow(ctx, getNvrServerStats, tenantID)
	var i GetNvrServerStatsRow
	err := row.Scan(
		&i.TotalServers,
		&i.ActiveServers,
		&i.InactiveServers,
		&i.MaintenanceServers,
		&i.TotalCameraChannels,
		&i.TotalStorageTb,
		&i.TotalRamGb,
	)
	return i, err
}

const getStorageStatsByServer = `-- name: GetStorageStatsByServer :one
SELECT 
    COUNT(*) as total_disks,
    COUNT(*) FILTER (WHERE status = 'healthy') as healthy_disks,
    COUNT(*) FILTER (WHERE status = 'warning') as warning_disks,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_disks,
    COALESCE(SUM(capacity_tb), 0) as total_capacity_tb,
    AVG(health_percentage)::INT as avg_health
FROM inventory.nvr_storage_units
WHERE nvr_server_id = $1 AND tenant_id = $2
`

type GetStorageStatsByServerRow struct {
	TotalDisks      int64       `db:"total_disks" json:"total_disks"`
	HealthyDisks    int64       `db:"healthy_disks" json:"healthy_disks"`
	WarningDisks    int64       `db:"warning_disks" json:"warning_disks"`
	FailedDisks     int64       `db:"failed_disks" json:"failed_disks"`
	TotalCapacityTb interface{} `db:"total_capacity_tb" json:"total_capacity_tb"`
	AvgHealth       int32       `db:"avg_health" json:"avg_health"`
}

func (q *Queries) GetStorageStatsByServer(ctx context.Context, nvrServerID pgtype.UUID, tenantID pgtype.UUID) (GetStorageStatsByServerRow, error) {
	row := q.db.QueryRow(ctx, getStorageStatsByServer, nvrServerID, tenantID)
	var i GetStorageStatsByServerRow
	err := row.Scan(
		&i.TotalDisks,
		&i.HealthyDisks,
		&i.WarningDisks,
		&i.FailedDisks,
		&i.TotalCapacityTb,
		&i.AvgHealth,
	)
	return i, err
}

const listActiveLicensesByTenant = `-- name: ListActiveLicensesByTenant :many
SELECT 
    nl.id, nl.tenant_id, nl.nvr_server_id, nl.license_key, nl.license_type, nl.edition, nl.total_licenses, nl.used_licenses, nl.issue_date, nl.expiry_date, nl.is_perpetual, nl.is_active, nl.metadata, nl.created_at, nl.updated_at,
    nvr.name as nvr_name,
    nvr.ip_address as nvr_ip
FROM inventory.nvr_licenses nl
    LEFT JOIN inventory.nvr_servers nvr ON nl.nvr_server_id = nvr.id
WHERE nl.tenant_id = $1 AND nl.is_active = true
ORDER BY nl.expiry_date ASC NULLS LAST
`

type ListActiveLicensesByTenantRow struct {
	ID            pgtype.UUID          `db:"id" json:"id"`
	TenantID      pgtype.UUID          `db:"tenant_id" json:"tenant_id"`
	NvrServerID   pgtype.UUID          `db:"nvr_server_id" json:"nvr_server_id"`
	LicenseKey    *string              `db:"license_key" json:"license_key"`
	LicenseType   InventoryLicenseType `db:"license_type" json:"license_type"`
	Edition       *string              `db:"edition" json:"edition"`
	TotalLicenses int32                `db:"total_licenses" json:"total_licenses"`
	UsedLicenses  int32                `db:"used_licenses" json:"used_licenses"`
	IssueDate     pgtype.Date          `db:"issue_date" json:"issue_date"`
	ExpiryDate    pgtype.Date          `db:"expiry_date" json:"expiry_date"`
	IsPerpetual   *bool                `db:"is_perpetual" json:"is_perpetual"`
	IsActive      *bool                `db:"is_active" json:"is_active"`
	Metadata      []byte               `db:"metadata" json:"metadata"`
	CreatedAt     pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz   `db:"updated_at" json:"updated_at"`
	NvrName       *string              `db:"nvr_name" json:"nvr_name"`
	NvrIp         *netip.Addr          `db:"nvr_ip" json:"nvr_ip"`
}

func (q *Queries) ListActiveLicensesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListActiveLicensesByTenantRow, error) {
	rows, err := q.db.Query(ctx, listActiveLicensesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveLicensesByTenantRow{}
	for rows.Next() {
		var i ListActiveLicensesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NvrServerID,
			&i.LicenseKey,
			&i.LicenseType,
			&i.Edition,
			&i.TotalLicenses,
			&i.UsedLicenses,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.IsPerpetual,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NvrName,
			&i.NvrIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringLicenses = `-- name: ListExpiringLicenses :many
SELECT 
    nl.id, nl.tenant_id, nl.nvr_server_id, nl.license_key, nl.license_type, nl.edition, nl.total_licenses, nl.used_licenses, nl.issue_date, nl.expiry_date, nl.is_perpetual, nl.is_active, nl.metadata, nl.created_at, nl.updated_at,
    nvr.name as nvr_name,
    nvr.ip_address as nvr_ip
FROM inventory.nvr_licenses nl
    LEFT JOIN inventory.nvr_servers nvr ON nl.nvr_server_id = nvr.id
WHERE nl.tenant_id = $1 
    AND nl.is_active = true 
    AND nl.is_perpetual = false
    AND nl.expiry_date <= $2
ORDER BY nl.expiry_date ASC
`

type ListExpiringLicensesRow struct {
	ID            pgtype.UUID          `db:"id" json:"id"`
	TenantID      pgtype.UUID          `db:"tenant_id" json:"tenant_id"`
	NvrServerID   pgtype.UUID          `db:"nvr_server_id" json:"nvr_server_id"`
	LicenseKey    *string              `db:"license_key" json:"license_key"`
	LicenseType   InventoryLicenseType `db:"license_type" json:"license_type"`
	Edition       *string              `db:"edition" json:"edition"`
	TotalLicenses int32                `db:"total_licenses" json:"total_licenses"`
	UsedLicenses  int32                `db:"used_licenses" json:"used_licenses"`
	IssueDate     pgtype.Date          `db:"issue_date" json:"issue_date"`
	ExpiryDate    pgtype.Date          `db:"expiry_date" json:"expiry_date"`
	IsPerpetual   *bool                `db:"is_perpetual" json:"is_perpetual"`
	IsActive      *bool                `db:"is_active" json:"is_active"`
	Metadata      []byte               `db:"metadata" json:"metadata"`
	CreatedAt     pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz   `db:"updated_at" json:"updated_at"`
	NvrName       *string              `db:"nvr_name" json:"nvr_name"`
	NvrIp         *netip.Addr          `db:"nvr_ip" json:"nvr_ip"`
}

func (q *Queries) ListExpiringLicenses(ctx context.Context, tenantID pgtype.UUID, expiryDate pgtype.Date) ([]ListExpiringLicensesRow, error) {
	rows, err := q.db.Query(ctx, listExpiringLicenses, tenantID, expiryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringLicensesRow{}
	for rows.Next() {
		var i ListExpiringLicensesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NvrServerID,
			&i.LicenseKey,
			&i.LicenseType,
			&i.Edition,
			&i.TotalLicenses,
			&i.UsedLicenses,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.IsPerpetual,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NvrName,
			&i.NvrIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLicenseHistoryByLicense = `-- name: ListLicenseHistoryByLicense :many

SELECT 
    lh.id, lh.tenant_id, lh.nvr_license_id, lh.nvr_server_id, lh.change_type, lh.field_changed, lh.old_value, lh.new_value, lh.description, lh.changed_at, lh.changed_by,
    u.first_name || ' ' || u.last_name as changed_by_name
FROM inventory.nvr_license_history lh
    LEFT JOIN auth.users u ON lh.changed_by = u.id
WHERE lh.nvr_license_id = $1 AND lh.tenant_id = $2
ORDER BY lh.changed_at DESC
LIMIT $3 OFFSET $4
`

type ListLicenseHistoryByLicenseRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	TenantID      pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	NvrLicenseID  pgtype.UUID        `db:"nvr_license_id" json:"nvr_license_id"`
	NvrServerID   pgtype.UUID        `db:"nvr_server_id" json:"nvr_server_id"`
	ChangeType    string             `db:"change_type" json:"change_type"`
	FieldChanged  *string            `db:"field_changed" json:"field_changed"`
	OldValue      *string            `db:"old_value" json:"old_value"`
	NewValue      *string            `db:"new_value" json:"new_value"`
	Description   *string            `db:"description" json:"description"`
	ChangedAt     pgtype.Timestamptz `db:"changed_at" json:"changed_at"`
	ChangedBy     pgtype.UUID        `db:"changed_by" json:"changed_by"`
	ChangedByName interface{}        `db:"changed_by_name" json:"changed_by_name"`
}

// =============================================
// NVR LICENSE HISTORY
// =============================================
func (q *Queries) ListLicenseHistoryByLicense(ctx context.Context, nvrLicenseID pgtype.UUID, tenantID pgtype.UUID, limit int32, offset int32) ([]ListLicenseHistoryByLicenseRow, error) {
	rows, err := q.db.Query(ctx, listLicenseHistoryByLicense,
		nvrLicenseID,
		tenantID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLicenseHistoryByLicenseRow{}
	for rows.Next() {
		var i ListLicenseHistoryByLicenseRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NvrLicenseID,
			&i.NvrServerID,
			&i.ChangeType,
			&i.FieldChanged,
			&i.OldValue,
			&i.NewValue,
			&i.Description,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLicenseHistoryByServer = `-- name: ListLicenseHistoryByServer :many
SELECT 
    lh.id, lh.tenant_id, lh.nvr_license_id, lh.nvr_server_id, lh.change_type, lh.field_changed, lh.old_value, lh.new_value, lh.description, lh.changed_at, lh.changed_by,
    nl.license_type,
    u.first_name || ' ' || u.last_name as changed_by_name
FROM inventory.nvr_license_history lh
    LEFT JOIN inventory.nvr_licenses nl ON lh.nvr_license_id = nl.id
    LEFT JOIN auth.users u ON lh.changed_by = u.id
WHERE lh.nvr_server_id = $1 AND lh.tenant_id = $2
ORDER BY lh.changed_at DESC
LIMIT $3 OFFSET $4
`

type ListLicenseHistoryByServerRow struct {
	ID            pgtype.UUID              `db:"id" json:"id"`
	TenantID      pgtype.UUID              `db:"tenant_id" json:"tenant_id"`
	NvrLicenseID  pgtype.UUID              `db:"nvr_license_id" json:"nvr_license_id"`
	NvrServerID   pgtype.UUID              `db:"nvr_server_id" json:"nvr_server_id"`
	ChangeType    string                   `db:"change_type" json:"change_type"`
	FieldChanged  *string                  `db:"field_changed" json:"field_changed"`
	OldValue      *string                  `db:"old_value" json:"old_value"`
	NewValue      *string                  `db:"new_value" json:"new_value"`
	Description   *string                  `db:"description" json:"description"`
	ChangedAt     pgtype.Timestamptz       `db:"changed_at" json:"changed_at"`
	ChangedBy     pgtype.UUID              `db:"changed_by" json:"changed_by"`
	LicenseType   NullInventoryLicenseType `db:"license_type" json:"license_type"`
	ChangedByName interface{}              `db:"changed_by_name" json:"changed_by_name"`
}

func (q *Queries) ListLicenseHistoryByServer(ctx context.Context, nvrServerID pgtype.UUID, tenantID pgtype.UUID, limit int32, offset int32) ([]ListLicenseHistoryByServerRow, error) {
	rows, err := q.db.Query(ctx, listLicenseHistoryByServer,
		nvrServerID,
		tenantID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLicenseHistoryByServerRow{}
	for rows.Next() {
		var i ListLicenseHistoryByServerRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NvrLicenseID,
			&i.NvrServerID,
			&i.ChangeType,
			&i.FieldChanged,
			&i.OldValue,
			&i.NewValue,
			&i.Description,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.LicenseType,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNvrLicensesByServer = `-- name: ListNvrLicensesByServer :many
SELECT id, tenant_id, nvr_server_id, license_key, license_type, edition, total_licenses, used_licenses, issue_date, expiry_date, is_perpetual, is_active, metadata, created_at, updated_at
FROM inventory.nvr_licenses
WHERE nvr_server_id = $1 AND tenant_id = $2
ORDER BY license_type ASC
`

func (q *Queries) ListNvrLicensesByServer(ctx context.Context, nvrServerID pgtype.UUID, tenantID pgtype.UUID) ([]InventoryNvrLicense, error) {
	rows, err := q.db.Query(ctx, listNvrLicensesByServer, nvrServerID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryNvrLicense{}
	for rows.Next() {
		var i InventoryNvrLicense
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NvrServerID,
			&i.LicenseKey,
			&i.LicenseType,
			&i.Edition,
			&i.TotalLicenses,
			&i.UsedLicenses,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.IsPerpetual,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNvrServersBySite = `-- name: ListNvrServersBySite :many
SELECT 
    nvr.id, nvr.tenant_id, nvr.site_id, nvr.brand_id, nvr.name, nvr.code, nvr.vms_server_id, nvr.edition, nvr.vms_version, nvr.camera_channels, nvr.tpv_channels, nvr.lpr_channels, nvr.integration_connections, nvr.model, nvr.service_tag, nvr.service_code, nvr.processor, nvr.ram_gb, nvr.os_name, nvr.system_type, nvr.ip_address, nvr.subnet_mask, nvr.gateway, nvr.mac_address, nvr.total_storage_tb, nvr.recording_days, nvr.launch_date, nvr.warranty_expiry_date, nvr.installation_date, nvr.status, nvr.admin_username, nvr.admin_password_encrypted, nvr.hardware_specs, nvr.network_config, nvr.metadata, nvr.notes, nvr.created_at, nvr.updated_at, nvr.created_by, nvr.updated_by,
    b.name as brand_name,
    (SELECT COUNT(*) FROM inventory.cameras c WHERE c.nvr_server_id = nvr.id) as camera_count
FROM inventory.nvr_servers nvr
    LEFT JOIN inventory.brands b ON nvr.brand_id = b.id
WHERE nvr.site_id = $1 AND nvr.tenant_id = $2
ORDER BY nvr.name ASC
`

type ListNvrServersBySiteRow struct {
	ID                     pgtype.UUID                  `db:"id" json:"id"`
	TenantID               pgtype.UUID                  `db:"tenant_id" json:"tenant_id"`
	SiteID                 pgtype.UUID                  `db:"site_id" json:"site_id"`
	BrandID                pgtype.UUID                  `db:"brand_id" json:"brand_id"`
	Name                   string                       `db:"name" json:"name"`
	Code                   *string                      `db:"code" json:"code"`
	VmsServerID            *string                      `db:"vms_server_id" json:"vms_server_id"`
	Edition                *string                      `db:"edition" json:"edition"`
	VmsVersion             *string                      `db:"vms_version" json:"vms_version"`
	CameraChannels         *int32                       `db:"camera_channels" json:"camera_channels"`
	TpvChannels            *int32                       `db:"tpv_channels" json:"tpv_channels"`
	LprChannels            *int32                       `db:"lpr_channels" json:"lpr_channels"`
	IntegrationConnections *int32                       `db:"integration_connections" json:"integration_connections"`
	Model                  *string                      `db:"model" json:"model"`
	ServiceTag             *string                      `db:"service_tag" json:"service_tag"`
	ServiceCode            *string                      `db:"service_code" json:"service_code"`
	Processor              *string                      `db:"processor" json:"processor"`
	RamGb                  *int32                       `db:"ram_gb" json:"ram_gb"`
	OsName                 *string                      `db:"os_name" json:"os_name"`
	SystemType             *string                      `db:"system_type" json:"system_type"`
	IpAddress              *netip.Addr                  `db:"ip_address" json:"ip_address"`
	SubnetMask             *netip.Addr                  `db:"subnet_mask" json:"subnet_mask"`
	Gateway                *netip.Addr                  `db:"gateway" json:"gateway"`
	MacAddress             net.HardwareAddr             `db:"mac_address" json:"mac_address"`
	TotalStorageTb         pgtype.Numeric               `db:"total_storage_tb" json:"total_storage_tb"`
	RecordingDays          *int32                       `db:"recording_days" json:"recording_days"`
	LaunchDate             pgtype.Date                  `db:"launch_date" json:"launch_date"`
	WarrantyExpiryDate     pgtype.Date                  `db:"warranty_expiry_date" json:"warranty_expiry_date"`
	InstallationDate       pgtype.Date                  `db:"installation_date" json:"installation_date"`
	Status                 NullInventoryEquipmentStatus `db:"status" json:"status"`
	AdminUsername          *string                      `db:"admin_username" json:"admin_username"`
	AdminPasswordEncrypted *string                      `db:"admin_password_encrypted" json:"admin_password_encrypted"`
	HardwareSpecs          []byte                       `db:"hardware_specs" json:"hardware_specs"`
	NetworkConfig          []byte                       `db:"network_config" json:"network_config"`
	Metadata               []byte                       `db:"metadata" json:"metadata"`
	Notes                  *string                      `db:"notes" json:"notes"`
	CreatedAt              pgtype.Timestamptz           `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz           `db:"updated_at" json:"updated_at"`
	CreatedBy              pgtype.UUID                  `db:"created_by" json:"created_by"`
	UpdatedBy              pgtype.UUID                  `db:"updated_by" json:"updated_by"`
	BrandName              *string                      `db:"brand_name" json:"brand_name"`
	CameraCount            int64                        `db:"camera_count" json:"camera_count"`
}

func (q *Queries) ListNvrServersBySite(ctx context.Context, siteID pgtype.UUID, tenantID pgtype.UUID) ([]ListNvrServersBySiteRow, error) {
	rows, err := q.db.Query(ctx, listNvrServersBySite, siteID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNvrServersBySiteRow{}
	for rows.Next() {
		var i ListNvrServersBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.BrandID,
			&i.Name,
			&i.Code,
			&i.VmsServerID,
			&i.Edition,
			&i.VmsVersion,
			&i.CameraChannels,
			&i.TpvChannels,
			&i.LprChannels,
			&i.IntegrationConnections,
			&i.Model,
			&i.ServiceTag,
			&i.ServiceCode,
			&i.Processor,
			&i.RamGb,
			&i.OsName,
			&i.SystemType,
			&i.IpAddress,
			&i.SubnetMask,
			&i.Gateway,
			&i.MacAddress,
			&i.TotalStorageTb,
			&i.RecordingDays,
			&i.LaunchDate,
			&i.WarrantyExpiryDate,
			&i.InstallationDate,
			&i.Status,
			&i.AdminUsername,
			&i.AdminPasswordEncrypted,
			&i.HardwareSpecs,
			&i.NetworkConfig,
			&i.Metadata,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.BrandName,
			&i.CameraCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNvrServersByStatus = `-- name: ListNvrServersByStatus :many
SELECT 
    nvr.id, nvr.tenant_id, nvr.site_id, nvr.brand_id, nvr.name, nvr.code, nvr.vms_server_id, nvr.edition, nvr.vms_version, nvr.camera_channels, nvr.tpv_channels, nvr.lpr_channels, nvr.integration_connections, nvr.model, nvr.service_tag, nvr.service_code, nvr.processor, nvr.ram_gb, nvr.os_name, nvr.system_type, nvr.ip_address, nvr.subnet_mask, nvr.gateway, nvr.mac_address, nvr.total_storage_tb, nvr.recording_days, nvr.launch_date, nvr.warranty_expiry_date, nvr.installation_date, nvr.status, nvr.admin_username, nvr.admin_password_encrypted, nvr.hardware_specs, nvr.network_config, nvr.metadata, nvr.notes, nvr.created_at, nvr.updated_at, nvr.created_by, nvr.updated_by,
    b.name as brand_name,
    s.name as site_name
FROM inventory.nvr_servers nvr
    LEFT JOIN inventory.brands b ON nvr.brand_id = b.id
    LEFT JOIN policies.sites s ON nvr.site_id = s.id
WHERE nvr.tenant_id = $1 AND nvr.status = $2
ORDER BY nvr.name ASC
`

type ListNvrServersByStatusRow struct {
	ID                     pgtype.UUID                  `db:"id" json:"id"`
	TenantID               pgtype.UUID                  `db:"tenant_id" json:"tenant_id"`
	SiteID                 pgtype.UUID                  `db:"site_id" json:"site_id"`
	BrandID                pgtype.UUID                  `db:"brand_id" json:"brand_id"`
	Name                   string                       `db:"name" json:"name"`
	Code                   *string                      `db:"code" json:"code"`
	VmsServerID            *string                      `db:"vms_server_id" json:"vms_server_id"`
	Edition                *string                      `db:"edition" json:"edition"`
	VmsVersion             *string                      `db:"vms_version" json:"vms_version"`
	CameraChannels         *int32                       `db:"camera_channels" json:"camera_channels"`
	TpvChannels            *int32                       `db:"tpv_channels" json:"tpv_channels"`
	LprChannels            *int32                       `db:"lpr_channels" json:"lpr_channels"`
	IntegrationConnections *int32                       `db:"integration_connections" json:"integration_connections"`
	Model                  *string                      `db:"model" json:"model"`
	ServiceTag             *string                      `db:"service_tag" json:"service_tag"`
	ServiceCode            *string                      `db:"service_code" json:"service_code"`
	Processor              *string                      `db:"processor" json:"processor"`
	RamGb                  *int32                       `db:"ram_gb" json:"ram_gb"`
	OsName                 *string                      `db:"os_name" json:"os_name"`
	SystemType             *string                      `db:"system_type" json:"system_type"`
	IpAddress              *netip.Addr                  `db:"ip_address" json:"ip_address"`
	SubnetMask             *netip.Addr                  `db:"subnet_mask" json:"subnet_mask"`
	Gateway                *netip.Addr                  `db:"gateway" json:"gateway"`
	MacAddress             net.HardwareAddr             `db:"mac_address" json:"mac_address"`
	TotalStorageTb         pgtype.Numeric               `db:"total_storage_tb" json:"total_storage_tb"`
	RecordingDays          *int32                       `db:"recording_days" json:"recording_days"`
	LaunchDate             pgtype.Date                  `db:"launch_date" json:"launch_date"`
	WarrantyExpiryDate     pgtype.Date                  `db:"warranty_expiry_date" json:"warranty_expiry_date"`
	InstallationDate       pgtype.Date                  `db:"installation_date" json:"installation_date"`
	Status                 NullInventoryEquipmentStatus `db:"status" json:"status"`
	AdminUsername          *string                      `db:"admin_username" json:"admin_username"`
	AdminPasswordEncrypted *string                      `db:"admin_password_encrypted" json:"admin_password_encrypted"`
	HardwareSpecs          []byte                       `db:"hardware_specs" json:"hardware_specs"`
	NetworkConfig          []byte                       `db:"network_config" json:"network_config"`
	Metadata               []byte                       `db:"metadata" json:"metadata"`
	Notes                  *string                      `db:"notes" json:"notes"`
	CreatedAt              pgtype.Timestamptz           `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz           `db:"updated_at" json:"updated_at"`
	CreatedBy              pgtype.UUID                  `db:"created_by" json:"created_by"`
	UpdatedBy              pgtype.UUID                  `db:"updated_by" json:"updated_by"`
	BrandName              *string                      `db:"brand_name" json:"brand_name"`
	SiteName               *string                      `db:"site_name" json:"site_name"`
}

func (q *Queries) ListNvrServersByStatus(ctx context.Context, tenantID pgtype.UUID, status NullInventoryEquipmentStatus) ([]ListNvrServersByStatusRow, error) {
	rows, err := q.db.Query(ctx, listNvrServersByStatus, tenantID, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNvrServersByStatusRow{}
	for rows.Next() {
		var i ListNvrServersByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.BrandID,
			&i.Name,
			&i.Code,
			&i.VmsServerID,
			&i.Edition,
			&i.VmsVersion,
			&i.CameraChannels,
			&i.TpvChannels,
			&i.LprChannels,
			&i.IntegrationConnections,
			&i.Model,
			&i.ServiceTag,
			&i.ServiceCode,
			&i.Processor,
			&i.RamGb,
			&i.OsName,
			&i.SystemType,
			&i.IpAddress,
			&i.SubnetMask,
			&i.Gateway,
			&i.MacAddress,
			&i.TotalStorageTb,
			&i.RecordingDays,
			&i.LaunchDate,
			&i.WarrantyExpiryDate,
			&i.InstallationDate,
			&i.Status,
			&i.AdminUsername,
			&i.AdminPasswordEncrypted,
			&i.HardwareSpecs,
			&i.NetworkConfig,
			&i.Metadata,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.BrandName,
			&i.SiteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNvrServersByTenant = `-- name: ListNvrServersByTenant :many
SELECT 
    nvr.id, nvr.tenant_id, nvr.site_id, nvr.brand_id, nvr.name, nvr.code, nvr.vms_server_id, nvr.edition, nvr.vms_version, nvr.camera_channels, nvr.tpv_channels, nvr.lpr_channels, nvr.integration_connections, nvr.model, nvr.service_tag, nvr.service_code, nvr.processor, nvr.ram_gb, nvr.os_name, nvr.system_type, nvr.ip_address, nvr.subnet_mask, nvr.gateway, nvr.mac_address, nvr.total_storage_tb, nvr.recording_days, nvr.launch_date, nvr.warranty_expiry_date, nvr.installation_date, nvr.status, nvr.admin_username, nvr.admin_password_encrypted, nvr.hardware_specs, nvr.network_config, nvr.metadata, nvr.notes, nvr.created_at, nvr.updated_at, nvr.created_by, nvr.updated_by,
    b.name as brand_name,
    s.name as site_name,
    (SELECT COUNT(*) FROM inventory.cameras c WHERE c.nvr_server_id = nvr.id) as camera_count
FROM inventory.nvr_servers nvr
    LEFT JOIN inventory.brands b ON nvr.brand_id = b.id
    LEFT JOIN policies.sites s ON nvr.site_id = s.id
WHERE nvr.tenant_id = $1
ORDER BY nvr.name ASC
`

type ListNvrServersByTenantRow struct {
	ID                     pgtype.UUID                  `db:"id" json:"id"`
	TenantID               pgtype.UUID                  `db:"tenant_id" json:"tenant_id"`
	SiteID                 pgtype.UUID                  `db:"site_id" json:"site_id"`
	BrandID                pgtype.UUID                  `db:"brand_id" json:"brand_id"`
	Name                   string                       `db:"name" json:"name"`
	Code                   *string                      `db:"code" json:"code"`
	VmsServerID            *string                      `db:"vms_server_id" json:"vms_server_id"`
	Edition                *string                      `db:"edition" json:"edition"`
	VmsVersion             *string                      `db:"vms_version" json:"vms_version"`
	CameraChannels         *int32                       `db:"camera_channels" json:"camera_channels"`
	TpvChannels            *int32                       `db:"tpv_channels" json:"tpv_channels"`
	LprChannels            *int32                       `db:"lpr_channels" json:"lpr_channels"`
	IntegrationConnections *int32                       `db:"integration_connections" json:"integration_connections"`
	Model                  *string                      `db:"model" json:"model"`
	ServiceTag             *string                      `db:"service_tag" json:"service_tag"`
	ServiceCode            *string                      `db:"service_code" json:"service_code"`
	Processor              *string                      `db:"processor" json:"processor"`
	RamGb                  *int32                       `db:"ram_gb" json:"ram_gb"`
	OsName                 *string                      `db:"os_name" json:"os_name"`
	SystemType             *string                      `db:"system_type" json:"system_type"`
	IpAddress              *netip.Addr                  `db:"ip_address" json:"ip_address"`
	SubnetMask             *netip.Addr                  `db:"subnet_mask" json:"subnet_mask"`
	Gateway                *netip.Addr                  `db:"gateway" json:"gateway"`
	MacAddress             net.HardwareAddr             `db:"mac_address" json:"mac_address"`
	TotalStorageTb         pgtype.Numeric               `db:"total_storage_tb" json:"total_storage_tb"`
	RecordingDays          *int32                       `db:"recording_days" json:"recording_days"`
	LaunchDate             pgtype.Date                  `db:"launch_date" json:"launch_date"`
	WarrantyExpiryDate     pgtype.Date                  `db:"warranty_expiry_date" json:"warranty_expiry_date"`
	InstallationDate       pgtype.Date                  `db:"installation_date" json:"installation_date"`
	Status                 NullInventoryEquipmentStatus `db:"status" json:"status"`
	AdminUsername          *string                      `db:"admin_username" json:"admin_username"`
	AdminPasswordEncrypted *string                      `db:"admin_password_encrypted" json:"admin_password_encrypted"`
	HardwareSpecs          []byte                       `db:"hardware_specs" json:"hardware_specs"`
	NetworkConfig          []byte                       `db:"network_config" json:"network_config"`
	Metadata               []byte                       `db:"metadata" json:"metadata"`
	Notes                  *string                      `db:"notes" json:"notes"`
	CreatedAt              pgtype.Timestamptz           `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz           `db:"updated_at" json:"updated_at"`
	CreatedBy              pgtype.UUID                  `db:"created_by" json:"created_by"`
	UpdatedBy              pgtype.UUID                  `db:"updated_by" json:"updated_by"`
	BrandName              *string                      `db:"brand_name" json:"brand_name"`
	SiteName               *string                      `db:"site_name" json:"site_name"`
	CameraCount            int64                        `db:"camera_count" json:"camera_count"`
}

func (q *Queries) ListNvrServersByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListNvrServersByTenantRow, error) {
	rows, err := q.db.Query(ctx, listNvrServersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNvrServersByTenantRow{}
	for rows.Next() {
		var i ListNvrServersByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.BrandID,
			&i.Name,
			&i.Code,
			&i.VmsServerID,
			&i.Edition,
			&i.VmsVersion,
			&i.CameraChannels,
			&i.TpvChannels,
			&i.LprChannels,
			&i.IntegrationConnections,
			&i.Model,
			&i.ServiceTag,
			&i.ServiceCode,
			&i.Processor,
			&i.RamGb,
			&i.OsName,
			&i.SystemType,
			&i.IpAddress,
			&i.SubnetMask,
			&i.Gateway,
			&i.MacAddress,
			&i.TotalStorageTb,
			&i.RecordingDays,
			&i.LaunchDate,
			&i.WarrantyExpiryDate,
			&i.InstallationDate,
			&i.Status,
			&i.AdminUsername,
			&i.AdminPasswordEncrypted,
			&i.HardwareSpecs,
			&i.NetworkConfig,
			&i.Metadata,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.BrandName,
			&i.SiteName,
			&i.CameraCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageUnitsByServer = `-- name: ListStorageUnitsByServer :many
SELECT id, tenant_id, nvr_server_id, slot_number, disk_type, brand, model, serial_number, capacity_tb, status, health_percentage, installation_date, created_at, updated_at
FROM inventory.nvr_storage_units
WHERE nvr_server_id = $1 AND tenant_id = $2
ORDER BY slot_number ASC
`

func (q *Queries) ListStorageUnitsByServer(ctx context.Context, nvrServerID pgtype.UUID, tenantID pgtype.UUID) ([]InventoryNvrStorageUnit, error) {
	rows, err := q.db.Query(ctx, listStorageUnitsByServer, nvrServerID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryNvrStorageUnit{}
	for rows.Next() {
		var i InventoryNvrStorageUnit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NvrServerID,
			&i.SlotNumber,
			&i.DiskType,
			&i.Brand,
			&i.Model,
			&i.SerialNumber,
			&i.CapacityTb,
			&i.Status,
			&i.HealthPercentage,
			&i.InstallationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLicenseUsage = `-- name: UpdateLicenseUsage :exec
UPDATE inventory.nvr_licenses
SET 
    used_licenses = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) UpdateLicenseUsage(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, usedLicenses int32) error {
	_, err := q.db.Exec(ctx, updateLicenseUsage, iD, tenantID, usedLicenses)
	return err
}

const updateNvrLicense = `-- name: UpdateNvrLicense :one
UPDATE inventory.nvr_licenses
SET 
    license_key = COALESCE($3, license_key),
    license_type = COALESCE($4, license_type),
    edition = COALESCE($5, edition),
    total_licenses = COALESCE($6, total_licenses),
    used_licenses = COALESCE($7, used_licenses),
    expiry_date = COALESCE($8, expiry_date),
    is_perpetual = COALESCE($9, is_perpetual),
    is_active = COALESCE($10, is_active),
    metadata = COALESCE($11, metadata),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, nvr_server_id, license_key, license_type, edition, total_licenses, used_licenses, issue_date, expiry_date, is_perpetual, is_active, metadata, created_at, updated_at
`

type UpdateNvrLicenseParams struct {
	ID            pgtype.UUID          `db:"id" json:"id"`
	TenantID      pgtype.UUID          `db:"tenant_id" json:"tenant_id"`
	LicenseKey    *string              `db:"license_key" json:"license_key"`
	LicenseType   InventoryLicenseType `db:"license_type" json:"license_type"`
	Edition       *string              `db:"edition" json:"edition"`
	TotalLicenses int32                `db:"total_licenses" json:"total_licenses"`
	UsedLicenses  int32                `db:"used_licenses" json:"used_licenses"`
	ExpiryDate    pgtype.Date          `db:"expiry_date" json:"expiry_date"`
	IsPerpetual   *bool                `db:"is_perpetual" json:"is_perpetual"`
	IsActive      *bool                `db:"is_active" json:"is_active"`
	Metadata      []byte               `db:"metadata" json:"metadata"`
}

func (q *Queries) UpdateNvrLicense(ctx context.Context, arg UpdateNvrLicenseParams) (InventoryNvrLicense, error) {
	row := q.db.QueryRow(ctx, updateNvrLicense,
		arg.ID,
		arg.TenantID,
		arg.LicenseKey,
		arg.LicenseType,
		arg.Edition,
		arg.TotalLicenses,
		arg.UsedLicenses,
		arg.ExpiryDate,
		arg.IsPerpetual,
		arg.IsActive,
		arg.Metadata,
	)
	var i InventoryNvrLicense
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NvrServerID,
		&i.LicenseKey,
		&i.LicenseType,
		&i.Edition,
		&i.TotalLicenses,
		&i.UsedLicenses,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.IsPerpetual,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNvrServer = `-- name: UpdateNvrServer :one
UPDATE inventory.nvr_servers
SET 
    site_id = COALESCE($3, site_id),
    brand_id = COALESCE($4, brand_id),
    name = COALESCE($5, name),
    code = COALESCE($6, code),
    vms_server_id = COALESCE($7, vms_server_id),
    edition = COALESCE($8, edition),
    vms_version = COALESCE($9, vms_version),
    camera_channels = COALESCE($10, camera_channels),
    tpv_channels = COALESCE($11, tpv_channels),
    lpr_channels = COALESCE($12, lpr_channels),
    model = COALESCE($13, model),
    service_tag = COALESCE($14, service_tag),
    processor = COALESCE($15, processor),
    ram_gb = COALESCE($16, ram_gb),
    os_name = COALESCE($17, os_name),
    ip_address = COALESCE($18, ip_address),
    mac_address = COALESCE($19, mac_address),
    total_storage_tb = COALESCE($20, total_storage_tb),
    recording_days = COALESCE($21, recording_days),
    status = COALESCE($22, status),
    hardware_specs = COALESCE($23, hardware_specs),
    network_config = COALESCE($24, network_config),
    metadata = COALESCE($25, metadata),
    notes = COALESCE($26, notes),
    updated_by = $27,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, site_id, brand_id, name, code, vms_server_id, edition, vms_version, camera_channels, tpv_channels, lpr_channels, integration_connections, model, service_tag, service_code, processor, ram_gb, os_name, system_type, ip_address, subnet_mask, gateway, mac_address, total_storage_tb, recording_days, launch_date, warranty_expiry_date, installation_date, status, admin_username, admin_password_encrypted, hardware_specs, network_config, metadata, notes, created_at, updated_at, created_by, updated_by
`

type UpdateNvrServerParams struct {
	ID             pgtype.UUID                  `db:"id" json:"id"`
	TenantID       pgtype.UUID                  `db:"tenant_id" json:"tenant_id"`
	SiteID         pgtype.UUID                  `db:"site_id" json:"site_id"`
	BrandID        pgtype.UUID                  `db:"brand_id" json:"brand_id"`
	Name           string                       `db:"name" json:"name"`
	Code           *string                      `db:"code" json:"code"`
	VmsServerID    *string                      `db:"vms_server_id" json:"vms_server_id"`
	Edition        *string                      `db:"edition" json:"edition"`
	VmsVersion     *string                      `db:"vms_version" json:"vms_version"`
	CameraChannels *int32                       `db:"camera_channels" json:"camera_channels"`
	TpvChannels    *int32                       `db:"tpv_channels" json:"tpv_channels"`
	LprChannels    *int32                       `db:"lpr_channels" json:"lpr_channels"`
	Model          *string                      `db:"model" json:"model"`
	ServiceTag     *string                      `db:"service_tag" json:"service_tag"`
	Processor      *string                      `db:"processor" json:"processor"`
	RamGb          *int32                       `db:"ram_gb" json:"ram_gb"`
	OsName         *string                      `db:"os_name" json:"os_name"`
	IpAddress      *netip.Addr                  `db:"ip_address" json:"ip_address"`
	MacAddress     net.HardwareAddr             `db:"mac_address" json:"mac_address"`
	TotalStorageTb pgtype.Numeric               `db:"total_storage_tb" json:"total_storage_tb"`
	RecordingDays  *int32                       `db:"recording_days" json:"recording_days"`
	Status         NullInventoryEquipmentStatus `db:"status" json:"status"`
	HardwareSpecs  []byte                       `db:"hardware_specs" json:"hardware_specs"`
	NetworkConfig  []byte                       `db:"network_config" json:"network_config"`
	Metadata       []byte                       `db:"metadata" json:"metadata"`
	Notes          *string                      `db:"notes" json:"notes"`
	UpdatedBy      pgtype.UUID                  `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateNvrServer(ctx context.Context, arg UpdateNvrServerParams) (InventoryNvrServer, error) {
	row := q.db.QueryRow(ctx, updateNvrServer,
		arg.ID,
		arg.TenantID,
		arg.SiteID,
		arg.BrandID,
		arg.Name,
		arg.Code,
		arg.VmsServerID,
		arg.Edition,
		arg.VmsVersion,
		arg.CameraChannels,
		arg.TpvChannels,
		arg.LprChannels,
		arg.Model,
		arg.ServiceTag,
		arg.Processor,
		arg.RamGb,
		arg.OsName,
		arg.IpAddress,
		arg.MacAddress,
		arg.TotalStorageTb,
		arg.RecordingDays,
		arg.Status,
		arg.HardwareSpecs,
		arg.NetworkConfig,
		arg.Metadata,
		arg.Notes,
		arg.UpdatedBy,
	)
	var i InventoryNvrServer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.BrandID,
		&i.Name,
		&i.Code,
		&i.VmsServerID,
		&i.Edition,
		&i.VmsVersion,
		&i.CameraChannels,
		&i.TpvChannels,
		&i.LprChannels,
		&i.IntegrationConnections,
		&i.Model,
		&i.ServiceTag,
		&i.ServiceCode,
		&i.Processor,
		&i.RamGb,
		&i.OsName,
		&i.SystemType,
		&i.IpAddress,
		&i.SubnetMask,
		&i.Gateway,
		&i.MacAddress,
		&i.TotalStorageTb,
		&i.RecordingDays,
		&i.LaunchDate,
		&i.WarrantyExpiryDate,
		&i.InstallationDate,
		&i.Status,
		&i.AdminUsername,
		&i.AdminPasswordEncrypted,
		&i.HardwareSpecs,
		&i.NetworkConfig,
		&i.Metadata,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateNvrServerStatus = `-- name: UpdateNvrServerStatus :exec
UPDATE inventory.nvr_servers
SET 
    status = $3,
    updated_by = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) UpdateNvrServerStatus(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, status NullInventoryEquipmentStatus, updatedBy pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateNvrServerStatus,
		iD,
		tenantID,
		status,
		updatedBy,
	)
	return err
}

const updateNvrStorageUnit = `-- name: UpdateNvrStorageUnit :one
UPDATE inventory.nvr_storage_units
SET 
    disk_type = COALESCE($3, disk_type),
    brand = COALESCE($4, brand),
    model = COALESCE($5, model),
    serial_number = COALESCE($6, serial_number),
    capacity_tb = COALESCE($7, capacity_tb),
    status = COALESCE($8, status),
    health_percentage = COALESCE($9, health_percentage),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, nvr_server_id, slot_number, disk_type, brand, model, serial_number, capacity_tb, status, health_percentage, installation_date, created_at, updated_at
`

func (q *Queries) UpdateNvrStorageUnit(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, diskType *string, brand *string, model *string, serialNumber *string, capacityTb pgtype.Numeric, status *string, healthPercentage *int32) (InventoryNvrStorageUnit, error) {
	row := q.db.QueryRow(ctx, updateNvrStorageUnit,
		iD,
		tenantID,
		diskType,
		brand,
		model,
		serialNumber,
		capacityTb,
		status,
		healthPercentage,
	)
	var i InventoryNvrStorageUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NvrServerID,
		&i.SlotNumber,
		&i.DiskType,
		&i.Brand,
		&i.Model,
		&i.SerialNumber,
		&i.CapacityTb,
		&i.Status,
		&i.HealthPercentage,
		&i.InstallationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
