// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_import.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateImportBatchItemsStatus = `-- name: BulkUpdateImportBatchItemsStatus :exec
UPDATE inventory.import_batch_items
SET 
    status = $3,
    processed_at = CURRENT_TIMESTAMP
WHERE batch_id = $1 AND tenant_id = $2 AND id = ANY($4::UUID[])
`

func (q *Queries) BulkUpdateImportBatchItemsStatus(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID, status *string, column4 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bulkUpdateImportBatchItemsStatus,
		batchID,
		tenantID,
		status,
		column4,
	)
	return err
}

const checkCameraCodeExists = `-- name: CheckCameraCodeExists :one

SELECT EXISTS(
    SELECT 1 FROM inventory.cameras 
    WHERE tenant_id = $1 AND code = $2
) as exists
`

// =============================================
// HELPER QUERIES FOR IMPORT VALIDATION
// =============================================
func (q *Queries) CheckCameraCodeExists(ctx context.Context, tenantID pgtype.UUID, code *string) (bool, error) {
	row := q.db.QueryRow(ctx, checkCameraCodeExists, tenantID, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkCameraIPExists = `-- name: CheckCameraIPExists :one
SELECT EXISTS(
    SELECT 1 FROM inventory.cameras 
    WHERE tenant_id = $1 AND ip_address = $2
) as exists
`

func (q *Queries) CheckCameraIPExists(ctx context.Context, tenantID pgtype.UUID, ipAddress *netip.Addr) (bool, error) {
	row := q.db.QueryRow(ctx, checkCameraIPExists, tenantID, ipAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkNvrCodeExists = `-- name: CheckNvrCodeExists :one
SELECT EXISTS(
    SELECT 1 FROM inventory.nvr_servers 
    WHERE tenant_id = $1 AND code = $2
) as exists
`

func (q *Queries) CheckNvrCodeExists(ctx context.Context, tenantID pgtype.UUID, code *string) (bool, error) {
	row := q.db.QueryRow(ctx, checkNvrCodeExists, tenantID, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkNvrIPExists = `-- name: CheckNvrIPExists :one
SELECT EXISTS(
    SELECT 1 FROM inventory.nvr_servers 
    WHERE tenant_id = $1 AND ip_address = $2
) as exists
`

func (q *Queries) CheckNvrIPExists(ctx context.Context, tenantID pgtype.UUID, ipAddress *netip.Addr) (bool, error) {
	row := q.db.QueryRow(ctx, checkNvrIPExists, tenantID, ipAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countImportBatchItemsByStatus = `-- name: CountImportBatchItemsByStatus :one
SELECT 
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE status = 'pending') as pending,
    COUNT(*) FILTER (WHERE status = 'success') as success,
    COUNT(*) FILTER (WHERE status = 'error') as error,
    COUNT(*) FILTER (WHERE status = 'skipped') as skipped
FROM inventory.import_batch_items
WHERE batch_id = $1 AND tenant_id = $2
`

type CountImportBatchItemsByStatusRow struct {
	Total   int64 `db:"total" json:"total"`
	Pending int64 `db:"pending" json:"pending"`
	Success int64 `db:"success" json:"success"`
	Error   int64 `db:"error" json:"error"`
	Skipped int64 `db:"skipped" json:"skipped"`
}

func (q *Queries) CountImportBatchItemsByStatus(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID) (CountImportBatchItemsByStatusRow, error) {
	row := q.db.QueryRow(ctx, countImportBatchItemsByStatus, batchID, tenantID)
	var i CountImportBatchItemsByStatusRow
	err := row.Scan(
		&i.Total,
		&i.Pending,
		&i.Success,
		&i.Error,
		&i.Skipped,
	)
	return i, err
}

const createImportBatch = `-- name: CreateImportBatch :one


INSERT INTO inventory.import_batches (
    tenant_id, batch_name, source_type, source_filename, target_table,
    column_mapping, total_rows, source_file_id, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, batch_name, source_type, source_filename, target_table, column_mapping, total_rows, processed_rows, success_rows, error_rows, skipped_rows, status, error_message, source_file_id, started_at, completed_at, created_at, created_by
`

// internal/database/queries/inventory_import.sql
// Queries SQLC para importación masiva de inventario
// =============================================
// IMPORT BATCHES
// =============================================
func (q *Queries) CreateImportBatch(ctx context.Context, tenantID pgtype.UUID, batchName string, sourceType InventoryImportSourceType, sourceFilename *string, targetTable string, columnMapping []byte, totalRows *int32, sourceFileID pgtype.UUID, createdBy pgtype.UUID) (InventoryImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		tenantID,
		batchName,
		sourceType,
		sourceFilename,
		targetTable,
		columnMapping,
		totalRows,
		sourceFileID,
		createdBy,
	)
	var i InventoryImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchName,
		&i.SourceType,
		&i.SourceFilename,
		&i.TargetTable,
		&i.ColumnMapping,
		&i.TotalRows,
		&i.ProcessedRows,
		&i.SuccessRows,
		&i.ErrorRows,
		&i.SkippedRows,
		&i.Status,
		&i.ErrorMessage,
		&i.SourceFileID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createImportBatchItem = `-- name: CreateImportBatchItem :one

INSERT INTO inventory.import_batch_items (
    tenant_id, batch_id, row_number, raw_data, status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, tenant_id, batch_id, row_number, raw_data, status, error_message, created_record_id, created_record_table, processed_at, created_at
`

// =============================================
// IMPORT BATCH ITEMS
// =============================================
func (q *Queries) CreateImportBatchItem(ctx context.Context, tenantID pgtype.UUID, batchID pgtype.UUID, rowNumber int32, rawData []byte, status *string) (InventoryImportBatchItem, error) {
	row := q.db.QueryRow(ctx, createImportBatchItem,
		tenantID,
		batchID,
		rowNumber,
		rawData,
		status,
	)
	var i InventoryImportBatchItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchID,
		&i.RowNumber,
		&i.RawData,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedRecordID,
		&i.CreatedRecordTable,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

type CreateImportBatchItemsBulkParams struct {
	TenantID  pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	BatchID   pgtype.UUID `db:"batch_id" json:"batch_id"`
	RowNumber int32       `db:"row_number" json:"row_number"`
	RawData   []byte      `db:"raw_data" json:"raw_data"`
	Status    *string     `db:"status" json:"status"`
}

const deleteImportBatch = `-- name: DeleteImportBatch :exec
DELETE FROM inventory.import_batches
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) DeleteImportBatch(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteImportBatch, iD, tenantID)
	return err
}

const deleteImportBatchItems = `-- name: DeleteImportBatchItems :exec
DELETE FROM inventory.import_batch_items
WHERE batch_id = $1 AND tenant_id = $2
`

func (q *Queries) DeleteImportBatchItems(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteImportBatchItems, batchID, tenantID)
	return err
}

const getAreaByName = `-- name: GetAreaByName :one
SELECT id, name
FROM policies.areas
WHERE tenant_id = $1 AND name ILIKE $2
LIMIT 1
`

type GetAreaByNameRow struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

func (q *Queries) GetAreaByName(ctx context.Context, tenantID pgtype.UUID, name string) (GetAreaByNameRow, error) {
	row := q.db.QueryRow(ctx, getAreaByName, tenantID, name)
	var i GetAreaByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getBrandByName = `-- name: GetBrandByName :one
SELECT id, name
FROM inventory.brands
WHERE name ILIKE $1
LIMIT 1
`

type GetBrandByNameRow struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

func (q *Queries) GetBrandByName(ctx context.Context, name string) (GetBrandByNameRow, error) {
	row := q.db.QueryRow(ctx, getBrandByName, name)
	var i GetBrandByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getImportBatchByID = `-- name: GetImportBatchByID :one
SELECT 
    ib.id, ib.tenant_id, ib.batch_name, ib.source_type, ib.source_filename, ib.target_table, ib.column_mapping, ib.total_rows, ib.processed_rows, ib.success_rows, ib.error_rows, ib.skipped_rows, ib.status, ib.error_message, ib.source_file_id, ib.started_at, ib.completed_at, ib.created_at, ib.created_by,
    u.first_name || ' ' || u.last_name as created_by_name
FROM inventory.import_batches ib
    LEFT JOIN auth.users u ON ib.created_by = u.id
WHERE ib.id = $1 AND ib.tenant_id = $2
LIMIT 1
`

type GetImportBatchByIDRow struct {
	ID             pgtype.UUID               `db:"id" json:"id"`
	TenantID       pgtype.UUID               `db:"tenant_id" json:"tenant_id"`
	BatchName      string                    `db:"batch_name" json:"batch_name"`
	SourceType     InventoryImportSourceType `db:"source_type" json:"source_type"`
	SourceFilename *string                   `db:"source_filename" json:"source_filename"`
	TargetTable    string                    `db:"target_table" json:"target_table"`
	ColumnMapping  []byte                    `db:"column_mapping" json:"column_mapping"`
	TotalRows      *int32                    `db:"total_rows" json:"total_rows"`
	ProcessedRows  *int32                    `db:"processed_rows" json:"processed_rows"`
	SuccessRows    *int32                    `db:"success_rows" json:"success_rows"`
	ErrorRows      *int32                    `db:"error_rows" json:"error_rows"`
	SkippedRows    *int32                    `db:"skipped_rows" json:"skipped_rows"`
	Status         NullInventoryImportStatus `db:"status" json:"status"`
	ErrorMessage   *string                   `db:"error_message" json:"error_message"`
	SourceFileID   pgtype.UUID               `db:"source_file_id" json:"source_file_id"`
	StartedAt      pgtype.Timestamptz        `db:"started_at" json:"started_at"`
	CompletedAt    pgtype.Timestamptz        `db:"completed_at" json:"completed_at"`
	CreatedAt      pgtype.Timestamptz        `db:"created_at" json:"created_at"`
	CreatedBy      pgtype.UUID               `db:"created_by" json:"created_by"`
	CreatedByName  interface{}               `db:"created_by_name" json:"created_by_name"`
}

func (q *Queries) GetImportBatchByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetImportBatchByIDRow, error) {
	row := q.db.QueryRow(ctx, getImportBatchByID, iD, tenantID)
	var i GetImportBatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchName,
		&i.SourceType,
		&i.SourceFilename,
		&i.TargetTable,
		&i.ColumnMapping,
		&i.TotalRows,
		&i.ProcessedRows,
		&i.SuccessRows,
		&i.ErrorRows,
		&i.SkippedRows,
		&i.Status,
		&i.ErrorMessage,
		&i.SourceFileID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.CreatedByName,
	)
	return i, err
}

const getImportBatchItemByID = `-- name: GetImportBatchItemByID :one
SELECT id, tenant_id, batch_id, row_number, raw_data, status, error_message, created_record_id, created_record_table, processed_at, created_at
FROM inventory.import_batch_items
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

func (q *Queries) GetImportBatchItemByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (InventoryImportBatchItem, error) {
	row := q.db.QueryRow(ctx, getImportBatchItemByID, iD, tenantID)
	var i InventoryImportBatchItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchID,
		&i.RowNumber,
		&i.RawData,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedRecordID,
		&i.CreatedRecordTable,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getImportBatchItemErrors = `-- name: GetImportBatchItemErrors :many
SELECT id, tenant_id, batch_id, row_number, raw_data, status, error_message, created_record_id, created_record_table, processed_at, created_at
FROM inventory.import_batch_items
WHERE batch_id = $1 AND tenant_id = $2 AND status = 'error'
ORDER BY row_number ASC
`

func (q *Queries) GetImportBatchItemErrors(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID) ([]InventoryImportBatchItem, error) {
	rows, err := q.db.Query(ctx, getImportBatchItemErrors, batchID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryImportBatchItem{}
	for rows.Next() {
		var i InventoryImportBatchItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BatchID,
			&i.RowNumber,
			&i.RawData,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedRecordID,
			&i.CreatedRecordTable,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImportBatchStats = `-- name: GetImportBatchStats :one
SELECT 
    COUNT(*) as total_batches,
    COUNT(*) FILTER (WHERE status = 'pending') as pending,
    COUNT(*) FILTER (WHERE status = 'processing') as processing,
    COUNT(*) FILTER (WHERE status = 'completed') as completed,
    COUNT(*) FILTER (WHERE status = 'completed_with_errors') as completed_with_errors,
    COUNT(*) FILTER (WHERE status = 'failed') as failed,
    COALESCE(SUM(total_rows), 0) as total_rows_imported,
    COALESCE(SUM(success_rows), 0) as total_success_rows
FROM inventory.import_batches
WHERE tenant_id = $1
`

type GetImportBatchStatsRow struct {
	TotalBatches        int64       `db:"total_batches" json:"total_batches"`
	Pending             int64       `db:"pending" json:"pending"`
	Processing          int64       `db:"processing" json:"processing"`
	Completed           int64       `db:"completed" json:"completed"`
	CompletedWithErrors int64       `db:"completed_with_errors" json:"completed_with_errors"`
	Failed              int64       `db:"failed" json:"failed"`
	TotalRowsImported   interface{} `db:"total_rows_imported" json:"total_rows_imported"`
	TotalSuccessRows    interface{} `db:"total_success_rows" json:"total_success_rows"`
}

func (q *Queries) GetImportBatchStats(ctx context.Context, tenantID pgtype.UUID) (GetImportBatchStatsRow, error) {
	row := q.db.QueryRow(ctx, getImportBatchStats, tenantID)
	var i GetImportBatchStatsRow
	err := row.Scan(
		&i.TotalBatches,
		&i.Pending,
		&i.Processing,
		&i.Completed,
		&i.CompletedWithErrors,
		&i.Failed,
		&i.TotalRowsImported,
		&i.TotalSuccessRows,
	)
	return i, err
}

const getModelByNameAndBrand = `-- name: GetModelByNameAndBrand :one
SELECT m.id, m.name, b.name as brand_name
FROM inventory.models m
    JOIN inventory.brands b ON m.brand_id = b.id
WHERE m.name ILIKE $1 AND b.name ILIKE $2
LIMIT 1
`

type GetModelByNameAndBrandRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	BrandName string      `db:"brand_name" json:"brand_name"`
}

func (q *Queries) GetModelByNameAndBrand(ctx context.Context, name string, name_2 string) (GetModelByNameAndBrandRow, error) {
	row := q.db.QueryRow(ctx, getModelByNameAndBrand, name, name_2)
	var i GetModelByNameAndBrandRow
	err := row.Scan(&i.ID, &i.Name, &i.BrandName)
	return i, err
}

const getNvrServerByName = `-- name: GetNvrServerByName :one
SELECT id, name
FROM inventory.nvr_servers
WHERE tenant_id = $1 AND name ILIKE $2
LIMIT 1
`

type GetNvrServerByNameRow struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

func (q *Queries) GetNvrServerByName(ctx context.Context, tenantID pgtype.UUID, name string) (GetNvrServerByNameRow, error) {
	row := q.db.QueryRow(ctx, getNvrServerByName, tenantID, name)
	var i GetNvrServerByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSiteByName = `-- name: GetSiteByName :one
SELECT id, name
FROM policies.sites
WHERE tenant_id = $1 AND name ILIKE $2
LIMIT 1
`

type GetSiteByNameRow struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

func (q *Queries) GetSiteByName(ctx context.Context, tenantID pgtype.UUID, name string) (GetSiteByNameRow, error) {
	row := q.db.QueryRow(ctx, getSiteByName, tenantID, name)
	var i GetSiteByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const incrementImportBatchProgress = `-- name: IncrementImportBatchProgress :exec
UPDATE inventory.import_batches
SET 
    processed_rows = processed_rows + 1,
    success_rows = success_rows + $3,
    error_rows = error_rows + $4,
    skipped_rows = skipped_rows + $5
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) IncrementImportBatchProgress(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, successRows *int32, errorRows *int32, skippedRows *int32) error {
	_, err := q.db.Exec(ctx, incrementImportBatchProgress,
		iD,
		tenantID,
		successRows,
		errorRows,
		skippedRows,
	)
	return err
}

const listImportBatchItems = `-- name: ListImportBatchItems :many
SELECT id, tenant_id, batch_id, row_number, raw_data, status, error_message, created_record_id, created_record_table, processed_at, created_at
FROM inventory.import_batch_items
WHERE batch_id = $1 AND tenant_id = $2
ORDER BY row_number ASC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListImportBatchItems(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID, limit int32, offset int32) ([]InventoryImportBatchItem, error) {
	rows, err := q.db.Query(ctx, listImportBatchItems,
		batchID,
		tenantID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryImportBatchItem{}
	for rows.Next() {
		var i InventoryImportBatchItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BatchID,
			&i.RowNumber,
			&i.RawData,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedRecordID,
			&i.CreatedRecordTable,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportBatchItemsByStatus = `-- name: ListImportBatchItemsByStatus :many
SELECT id, tenant_id, batch_id, row_number, raw_data, status, error_message, created_record_id, created_record_table, processed_at, created_at
FROM inventory.import_batch_items
WHERE batch_id = $1 AND tenant_id = $2 AND status = $3
ORDER BY row_number ASC
LIMIT $4 OFFSET $5
`

func (q *Queries) ListImportBatchItemsByStatus(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID, status *string, limit int32, offset int32) ([]InventoryImportBatchItem, error) {
	rows, err := q.db.Query(ctx, listImportBatchItemsByStatus,
		batchID,
		tenantID,
		status,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryImportBatchItem{}
	for rows.Next() {
		var i InventoryImportBatchItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BatchID,
			&i.RowNumber,
			&i.RawData,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedRecordID,
			&i.CreatedRecordTable,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportBatchesByStatus = `-- name: ListImportBatchesByStatus :many
SELECT 
    ib.id, ib.tenant_id, ib.batch_name, ib.source_type, ib.source_filename, ib.target_table, ib.column_mapping, ib.total_rows, ib.processed_rows, ib.success_rows, ib.error_rows, ib.skipped_rows, ib.status, ib.error_message, ib.source_file_id, ib.started_at, ib.completed_at, ib.created_at, ib.created_by,
    u.first_name || ' ' || u.last_name as created_by_name
FROM inventory.import_batches ib
    LEFT JOIN auth.users u ON ib.created_by = u.id
WHERE ib.tenant_id = $1 AND ib.status = $2
ORDER BY ib.created_at DESC
`

type ListImportBatchesByStatusRow struct {
	ID             pgtype.UUID               `db:"id" json:"id"`
	TenantID       pgtype.UUID               `db:"tenant_id" json:"tenant_id"`
	BatchName      string                    `db:"batch_name" json:"batch_name"`
	SourceType     InventoryImportSourceType `db:"source_type" json:"source_type"`
	SourceFilename *string                   `db:"source_filename" json:"source_filename"`
	TargetTable    string                    `db:"target_table" json:"target_table"`
	ColumnMapping  []byte                    `db:"column_mapping" json:"column_mapping"`
	TotalRows      *int32                    `db:"total_rows" json:"total_rows"`
	ProcessedRows  *int32                    `db:"processed_rows" json:"processed_rows"`
	SuccessRows    *int32                    `db:"success_rows" json:"success_rows"`
	ErrorRows      *int32                    `db:"error_rows" json:"error_rows"`
	SkippedRows    *int32                    `db:"skipped_rows" json:"skipped_rows"`
	Status         NullInventoryImportStatus `db:"status" json:"status"`
	ErrorMessage   *string                   `db:"error_message" json:"error_message"`
	SourceFileID   pgtype.UUID               `db:"source_file_id" json:"source_file_id"`
	StartedAt      pgtype.Timestamptz        `db:"started_at" json:"started_at"`
	CompletedAt    pgtype.Timestamptz        `db:"completed_at" json:"completed_at"`
	CreatedAt      pgtype.Timestamptz        `db:"created_at" json:"created_at"`
	CreatedBy      pgtype.UUID               `db:"created_by" json:"created_by"`
	CreatedByName  interface{}               `db:"created_by_name" json:"created_by_name"`
}

func (q *Queries) ListImportBatchesByStatus(ctx context.Context, tenantID pgtype.UUID, status NullInventoryImportStatus) ([]ListImportBatchesByStatusRow, error) {
	rows, err := q.db.Query(ctx, listImportBatchesByStatus, tenantID, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportBatchesByStatusRow{}
	for rows.Next() {
		var i ListImportBatchesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BatchName,
			&i.SourceType,
			&i.SourceFilename,
			&i.TargetTable,
			&i.ColumnMapping,
			&i.TotalRows,
			&i.ProcessedRows,
			&i.SuccessRows,
			&i.ErrorRows,
			&i.SkippedRows,
			&i.Status,
			&i.ErrorMessage,
			&i.SourceFileID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportBatchesByTenant = `-- name: ListImportBatchesByTenant :many
SELECT 
    ib.id, ib.tenant_id, ib.batch_name, ib.source_type, ib.source_filename, ib.target_table, ib.column_mapping, ib.total_rows, ib.processed_rows, ib.success_rows, ib.error_rows, ib.skipped_rows, ib.status, ib.error_message, ib.source_file_id, ib.started_at, ib.completed_at, ib.created_at, ib.created_by,
    u.first_name || ' ' || u.last_name as created_by_name
FROM inventory.import_batches ib
    LEFT JOIN auth.users u ON ib.created_by = u.id
WHERE ib.tenant_id = $1
ORDER BY ib.created_at DESC
LIMIT $2 OFFSET $3
`

type ListImportBatchesByTenantRow struct {
	ID             pgtype.UUID               `db:"id" json:"id"`
	TenantID       pgtype.UUID               `db:"tenant_id" json:"tenant_id"`
	BatchName      string                    `db:"batch_name" json:"batch_name"`
	SourceType     InventoryImportSourceType `db:"source_type" json:"source_type"`
	SourceFilename *string                   `db:"source_filename" json:"source_filename"`
	TargetTable    string                    `db:"target_table" json:"target_table"`
	ColumnMapping  []byte                    `db:"column_mapping" json:"column_mapping"`
	TotalRows      *int32                    `db:"total_rows" json:"total_rows"`
	ProcessedRows  *int32                    `db:"processed_rows" json:"processed_rows"`
	SuccessRows    *int32                    `db:"success_rows" json:"success_rows"`
	ErrorRows      *int32                    `db:"error_rows" json:"error_rows"`
	SkippedRows    *int32                    `db:"skipped_rows" json:"skipped_rows"`
	Status         NullInventoryImportStatus `db:"status" json:"status"`
	ErrorMessage   *string                   `db:"error_message" json:"error_message"`
	SourceFileID   pgtype.UUID               `db:"source_file_id" json:"source_file_id"`
	StartedAt      pgtype.Timestamptz        `db:"started_at" json:"started_at"`
	CompletedAt    pgtype.Timestamptz        `db:"completed_at" json:"completed_at"`
	CreatedAt      pgtype.Timestamptz        `db:"created_at" json:"created_at"`
	CreatedBy      pgtype.UUID               `db:"created_by" json:"created_by"`
	CreatedByName  interface{}               `db:"created_by_name" json:"created_by_name"`
}

func (q *Queries) ListImportBatchesByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]ListImportBatchesByTenantRow, error) {
	rows, err := q.db.Query(ctx, listImportBatchesByTenant, tenantID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportBatchesByTenantRow{}
	for rows.Next() {
		var i ListImportBatchesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BatchName,
			&i.SourceType,
			&i.SourceFilename,
			&i.TargetTable,
			&i.ColumnMapping,
			&i.TotalRows,
			&i.ProcessedRows,
			&i.SuccessRows,
			&i.ErrorRows,
			&i.SkippedRows,
			&i.Status,
			&i.ErrorMessage,
			&i.SourceFileID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingImportBatchItems = `-- name: ListPendingImportBatchItems :many
SELECT id, tenant_id, batch_id, row_number, raw_data, status, error_message, created_record_id, created_record_table, processed_at, created_at
FROM inventory.import_batch_items
WHERE batch_id = $1 AND tenant_id = $2 AND status = 'pending'
ORDER BY row_number ASC
LIMIT $3
`

func (q *Queries) ListPendingImportBatchItems(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID, limit int32) ([]InventoryImportBatchItem, error) {
	rows, err := q.db.Query(ctx, listPendingImportBatchItems, batchID, tenantID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryImportBatchItem{}
	for rows.Next() {
		var i InventoryImportBatchItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BatchID,
			&i.RowNumber,
			&i.RawData,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedRecordID,
			&i.CreatedRecordTable,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportBatchItemStatus = `-- name: UpdateImportBatchItemStatus :exec
UPDATE inventory.import_batch_items
SET 
    status = $3,
    error_message = $4,
    created_record_id = $5,
    created_record_table = $6,
    processed_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) UpdateImportBatchItemStatus(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, status *string, errorMessage *string, createdRecordID pgtype.UUID, createdRecordTable *string) error {
	_, err := q.db.Exec(ctx, updateImportBatchItemStatus,
		iD,
		tenantID,
		status,
		errorMessage,
		createdRecordID,
		createdRecordTable,
	)
	return err
}

const updateImportBatchProgress = `-- name: UpdateImportBatchProgress :exec
UPDATE inventory.import_batches
SET 
    processed_rows = $3,
    success_rows = $4,
    error_rows = $5,
    skipped_rows = $6
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) UpdateImportBatchProgress(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, processedRows *int32, successRows *int32, errorRows *int32, skippedRows *int32) error {
	_, err := q.db.Exec(ctx, updateImportBatchProgress,
		iD,
		tenantID,
		processedRows,
		successRows,
		errorRows,
		skippedRows,
	)
	return err
}

const updateImportBatchStatus = `-- name: UpdateImportBatchStatus :exec
UPDATE inventory.import_batches
SET 
    status = $3,
    error_message = $4,
    started_at = CASE WHEN $3 = 'processing' THEN CURRENT_TIMESTAMP ELSE started_at END,
    completed_at = CASE WHEN $3 IN ('completed', 'completed_with_errors', 'failed', 'cancelled') THEN CURRENT_TIMESTAMP ELSE completed_at END
WHERE id = $1 AND tenant_id = $2
`

func (q *Queries) UpdateImportBatchStatus(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, status NullInventoryImportStatus, errorMessage *string) error {
	_, err := q.db.Exec(ctx, updateImportBatchStatus,
		iD,
		tenantID,
		status,
		errorMessage,
	)
	return err
}
