// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"net"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type BillingInvoiceStatus string

const (
	BillingInvoiceStatusDraft     BillingInvoiceStatus = "draft"
	BillingInvoiceStatusPending   BillingInvoiceStatus = "pending"
	BillingInvoiceStatusSent      BillingInvoiceStatus = "sent"
	BillingInvoiceStatusStamped   BillingInvoiceStatus = "stamped"
	BillingInvoiceStatusPaid      BillingInvoiceStatus = "paid"
	BillingInvoiceStatusPartial   BillingInvoiceStatus = "partial"
	BillingInvoiceStatusOverdue   BillingInvoiceStatus = "overdue"
	BillingInvoiceStatusCancelled BillingInvoiceStatus = "cancelled"
)

func (e *BillingInvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingInvoiceStatus(s)
	case string:
		*e = BillingInvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingInvoiceStatus: %T", src)
	}
	return nil
}

type NullBillingInvoiceStatus struct {
	BillingInvoiceStatus BillingInvoiceStatus `json:"billing_invoice_status"`
	Valid                bool                 `json:"valid"` // Valid is true if BillingInvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BillingInvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingInvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingInvoiceStatus), nil
}

type CollectionPaymentMethod string

const (
	CollectionPaymentMethodCash       CollectionPaymentMethod = "cash"
	CollectionPaymentMethodTransfer   CollectionPaymentMethod = "transfer"
	CollectionPaymentMethodCheck      CollectionPaymentMethod = "check"
	CollectionPaymentMethodCreditCard CollectionPaymentMethod = "credit_card"
	CollectionPaymentMethodDebitCard  CollectionPaymentMethod = "debit_card"
	CollectionPaymentMethodPaypal     CollectionPaymentMethod = "paypal"
	CollectionPaymentMethodStripe     CollectionPaymentMethod = "stripe"
	CollectionPaymentMethodOther      CollectionPaymentMethod = "other"
)

func (e *CollectionPaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CollectionPaymentMethod(s)
	case string:
		*e = CollectionPaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for CollectionPaymentMethod: %T", src)
	}
	return nil
}

type NullCollectionPaymentMethod struct {
	CollectionPaymentMethod CollectionPaymentMethod `json:"collection_payment_method"`
	Valid                   bool                    `json:"valid"` // Valid is true if CollectionPaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCollectionPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.CollectionPaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CollectionPaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCollectionPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CollectionPaymentMethod), nil
}

type CollectionPaymentStatus string

const (
	CollectionPaymentStatusPending    CollectionPaymentStatus = "pending"
	CollectionPaymentStatusProcessing CollectionPaymentStatus = "processing"
	CollectionPaymentStatusCompleted  CollectionPaymentStatus = "completed"
	CollectionPaymentStatusFailed     CollectionPaymentStatus = "failed"
	CollectionPaymentStatusRefunded   CollectionPaymentStatus = "refunded"
	CollectionPaymentStatusCancelled  CollectionPaymentStatus = "cancelled"
)

func (e *CollectionPaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CollectionPaymentStatus(s)
	case string:
		*e = CollectionPaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CollectionPaymentStatus: %T", src)
	}
	return nil
}

type NullCollectionPaymentStatus struct {
	CollectionPaymentStatus CollectionPaymentStatus `json:"collection_payment_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if CollectionPaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCollectionPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CollectionPaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CollectionPaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCollectionPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CollectionPaymentStatus), nil
}

type InventoryCameraType string

const (
	InventoryCameraTypeMicroDome   InventoryCameraType = "micro_dome"
	InventoryCameraTypeDome        InventoryCameraType = "dome"
	InventoryCameraTypeDome360     InventoryCameraType = "dome_360"
	InventoryCameraTypePtz         InventoryCameraType = "ptz"
	InventoryCameraTypeBullet      InventoryCameraType = "bullet"
	InventoryCameraTypeBox         InventoryCameraType = "box"
	InventoryCameraTypeFisheye     InventoryCameraType = "fisheye"
	InventoryCameraTypeMultisensor InventoryCameraType = "multisensor"
	InventoryCameraTypeThermal     InventoryCameraType = "thermal"
	InventoryCameraTypeEncoder     InventoryCameraType = "encoder"
	InventoryCameraTypeOther       InventoryCameraType = "other"
)

func (e *InventoryCameraType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryCameraType(s)
	case string:
		*e = InventoryCameraType(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryCameraType: %T", src)
	}
	return nil
}

type NullInventoryCameraType struct {
	InventoryCameraType InventoryCameraType `json:"inventory_camera_type"`
	Valid               bool                `json:"valid"` // Valid is true if InventoryCameraType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryCameraType) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryCameraType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryCameraType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryCameraType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryCameraType), nil
}

type InventoryEquipmentStatus string

const (
	InventoryEquipmentStatusActive              InventoryEquipmentStatus = "active"
	InventoryEquipmentStatusInactive            InventoryEquipmentStatus = "inactive"
	InventoryEquipmentStatusFaulty              InventoryEquipmentStatus = "faulty"
	InventoryEquipmentStatusUnderMaintenance    InventoryEquipmentStatus = "under_maintenance"
	InventoryEquipmentStatusRetired             InventoryEquipmentStatus = "retired"
	InventoryEquipmentStatusPendingInstallation InventoryEquipmentStatus = "pending_installation"
)

func (e *InventoryEquipmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryEquipmentStatus(s)
	case string:
		*e = InventoryEquipmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryEquipmentStatus: %T", src)
	}
	return nil
}

type NullInventoryEquipmentStatus struct {
	InventoryEquipmentStatus InventoryEquipmentStatus `json:"inventory_equipment_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if InventoryEquipmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryEquipmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryEquipmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryEquipmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryEquipmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryEquipmentStatus), nil
}

type InventoryImportSourceType string

const (
	InventoryImportSourceTypeExcel    InventoryImportSourceType = "excel"
	InventoryImportSourceTypeCsv      InventoryImportSourceType = "csv"
	InventoryImportSourceTypeOcrImage InventoryImportSourceType = "ocr_image"
	InventoryImportSourceTypeApi      InventoryImportSourceType = "api"
	InventoryImportSourceTypeManual   InventoryImportSourceType = "manual"
)

func (e *InventoryImportSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryImportSourceType(s)
	case string:
		*e = InventoryImportSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryImportSourceType: %T", src)
	}
	return nil
}

type NullInventoryImportSourceType struct {
	InventoryImportSourceType InventoryImportSourceType `json:"inventory_import_source_type"`
	Valid                     bool                      `json:"valid"` // Valid is true if InventoryImportSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryImportSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryImportSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryImportSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryImportSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryImportSourceType), nil
}

type InventoryImportStatus string

const (
	InventoryImportStatusPending             InventoryImportStatus = "pending"
	InventoryImportStatusProcessing          InventoryImportStatus = "processing"
	InventoryImportStatusCompleted           InventoryImportStatus = "completed"
	InventoryImportStatusCompletedWithErrors InventoryImportStatus = "completed_with_errors"
	InventoryImportStatusFailed              InventoryImportStatus = "failed"
	InventoryImportStatusCancelled           InventoryImportStatus = "cancelled"
)

func (e *InventoryImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryImportStatus(s)
	case string:
		*e = InventoryImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryImportStatus: %T", src)
	}
	return nil
}

type NullInventoryImportStatus struct {
	InventoryImportStatus InventoryImportStatus `json:"inventory_import_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if InventoryImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryImportStatus), nil
}

type InventoryLicenseType string

const (
	InventoryLicenseTypeEnterprise    InventoryLicenseType = "enterprise"
	InventoryLicenseTypeStandard      InventoryLicenseType = "standard"
	InventoryLicenseTypeProfessional  InventoryLicenseType = "professional"
	InventoryLicenseTypeCameraChannel InventoryLicenseType = "camera_channel"
	InventoryLicenseTypeLprChannel    InventoryLicenseType = "lpr_channel"
	InventoryLicenseTypeTpvChannel    InventoryLicenseType = "tpv_channel"
	InventoryLicenseTypeAnalytics     InventoryLicenseType = "analytics"
	InventoryLicenseTypeIntegration   InventoryLicenseType = "integration"
	InventoryLicenseTypeOther         InventoryLicenseType = "other"
)

func (e *InventoryLicenseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryLicenseType(s)
	case string:
		*e = InventoryLicenseType(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryLicenseType: %T", src)
	}
	return nil
}

type NullInventoryLicenseType struct {
	InventoryLicenseType InventoryLicenseType `json:"inventory_license_type"`
	Valid                bool                 `json:"valid"` // Valid is true if InventoryLicenseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryLicenseType) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryLicenseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryLicenseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryLicenseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryLicenseType), nil
}

type PoliciesPolicyStatus string

const (
	PoliciesPolicyStatusDraft          PoliciesPolicyStatus = "draft"
	PoliciesPolicyStatusActive         PoliciesPolicyStatus = "active"
	PoliciesPolicyStatusSuspended      PoliciesPolicyStatus = "suspended"
	PoliciesPolicyStatusExpired        PoliciesPolicyStatus = "expired"
	PoliciesPolicyStatusCancelled      PoliciesPolicyStatus = "cancelled"
	PoliciesPolicyStatusPendingRenewal PoliciesPolicyStatus = "pending_renewal"
)

func (e *PoliciesPolicyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PoliciesPolicyStatus(s)
	case string:
		*e = PoliciesPolicyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PoliciesPolicyStatus: %T", src)
	}
	return nil
}

type NullPoliciesPolicyStatus struct {
	PoliciesPolicyStatus PoliciesPolicyStatus `json:"policies_policy_status"`
	Valid                bool                 `json:"valid"` // Valid is true if PoliciesPolicyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPoliciesPolicyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PoliciesPolicyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PoliciesPolicyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPoliciesPolicyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PoliciesPolicyStatus), nil
}

type TicketsCoverageStatus string

const (
	TicketsCoverageStatusUnknown    TicketsCoverageStatus = "unknown"
	TicketsCoverageStatusCovered    TicketsCoverageStatus = "covered"
	TicketsCoverageStatusPartial    TicketsCoverageStatus = "partial"
	TicketsCoverageStatusNotCovered TicketsCoverageStatus = "not_covered"
)

func (e *TicketsCoverageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsCoverageStatus(s)
	case string:
		*e = TicketsCoverageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsCoverageStatus: %T", src)
	}
	return nil
}

type NullTicketsCoverageStatus struct {
	TicketsCoverageStatus TicketsCoverageStatus `json:"tickets_coverage_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if TicketsCoverageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsCoverageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsCoverageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsCoverageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsCoverageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsCoverageStatus), nil
}

type TicketsSlaStatus string

const (
	TicketsSlaStatusUnknown  TicketsSlaStatus = "unknown"
	TicketsSlaStatusOk       TicketsSlaStatus = "ok"
	TicketsSlaStatusAtRisk   TicketsSlaStatus = "at_risk"
	TicketsSlaStatusBreached TicketsSlaStatus = "breached"
)

func (e *TicketsSlaStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsSlaStatus(s)
	case string:
		*e = TicketsSlaStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsSlaStatus: %T", src)
	}
	return nil
}

type NullTicketsSlaStatus struct {
	TicketsSlaStatus TicketsSlaStatus `json:"tickets_sla_status"`
	Valid            bool             `json:"valid"` // Valid is true if TicketsSlaStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsSlaStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsSlaStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsSlaStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsSlaStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsSlaStatus), nil
}

type TicketsTicketPriority string

const (
	TicketsTicketPriorityLow      TicketsTicketPriority = "low"
	TicketsTicketPriorityMedium   TicketsTicketPriority = "medium"
	TicketsTicketPriorityHigh     TicketsTicketPriority = "high"
	TicketsTicketPriorityCritical TicketsTicketPriority = "critical"
)

func (e *TicketsTicketPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsTicketPriority(s)
	case string:
		*e = TicketsTicketPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsTicketPriority: %T", src)
	}
	return nil
}

type NullTicketsTicketPriority struct {
	TicketsTicketPriority TicketsTicketPriority `json:"tickets_ticket_priority"`
	Valid                 bool                  `json:"valid"` // Valid is true if TicketsTicketPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsTicketPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsTicketPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsTicketPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsTicketPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsTicketPriority), nil
}

type TicketsTicketStatus string

const (
	TicketsTicketStatusOpen            TicketsTicketStatus = "open"
	TicketsTicketStatusAssigned        TicketsTicketStatus = "assigned"
	TicketsTicketStatusInProgress      TicketsTicketStatus = "in_progress"
	TicketsTicketStatusOnHold          TicketsTicketStatus = "on_hold"
	TicketsTicketStatusPendingParts    TicketsTicketStatus = "pending_parts"
	TicketsTicketStatusPendingApproval TicketsTicketStatus = "pending_approval"
	TicketsTicketStatusCompleted       TicketsTicketStatus = "completed"
	TicketsTicketStatusCancelled       TicketsTicketStatus = "cancelled"
)

func (e *TicketsTicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsTicketStatus(s)
	case string:
		*e = TicketsTicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsTicketStatus: %T", src)
	}
	return nil
}

type NullTicketsTicketStatus struct {
	TicketsTicketStatus TicketsTicketStatus `json:"tickets_ticket_status"`
	Valid               bool                `json:"valid"` // Valid is true if TicketsTicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsTicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsTicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsTicketStatus), nil
}

type TicketsTicketType string

const (
	TicketsTicketTypePreventive     TicketsTicketType = "preventive"
	TicketsTicketTypeCorrective     TicketsTicketType = "corrective"
	TicketsTicketTypeEmergency      TicketsTicketType = "emergency"
	TicketsTicketTypeInstallation   TicketsTicketType = "installation"
	TicketsTicketTypeUninstallation TicketsTicketType = "uninstallation"
	TicketsTicketTypeInspection     TicketsTicketType = "inspection"
)

func (e *TicketsTicketType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketsTicketType(s)
	case string:
		*e = TicketsTicketType(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketsTicketType: %T", src)
	}
	return nil
}

type NullTicketsTicketType struct {
	TicketsTicketType TicketsTicketType `json:"tickets_ticket_type"`
	Valid             bool              `json:"valid"` // Valid is true if TicketsTicketType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketsTicketType) Scan(value interface{}) error {
	if value == nil {
		ns.TicketsTicketType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketsTicketType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketsTicketType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketsTicketType), nil
}

// Items de menú dinámicos y configurables por tenant
type AuthMenuItem struct {
	ID pgtype.UUID `db:"id" json:"id"`
	// NULL = menú global disponible para todos los tenants
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Code     string      `db:"code" json:"code"`
	Label    string      `db:"label" json:"label"`
	Icon     *string     `db:"icon" json:"icon"`
	Route    *string     `db:"route" json:"route"`
	// ID del item padre para crear submenús
	ParentID pgtype.UUID `db:"parent_id" json:"parent_id"`
	// Permiso requerido para ver este item
	RequiredPermission *string            `db:"required_permission" json:"required_permission"`
	DisplayOrder       *int32             `db:"display_order" json:"display_order"`
	IsActive           *bool              `db:"is_active" json:"is_active"`
	IsVisible          *bool              `db:"is_visible" json:"is_visible"`
	BadgeText          *string            `db:"badge_text" json:"badge_text"`
	BadgeColor         *string            `db:"badge_color" json:"badge_color"`
	Description        *string            `db:"description" json:"description"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	// Plantilla a la que pertenece este item
	TemplateID pgtype.UUID `db:"template_id" json:"template_id"`
}

// Plantillas de menú reutilizables
type AuthMenuTemplate struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	IsDefault   *bool              `db:"is_default" json:"is_default"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Relación N:N entre items de menú y templates. Un item puede estar en múltiples templates.
type AuthMenuTemplateItem struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	TemplateID pgtype.UUID `db:"template_id" json:"template_id"`
	MenuItemID pgtype.UUID `db:"menu_item_id" json:"menu_item_id"`
	// Orden de visualización específico para este item en este template
	DisplayOrder *int32 `db:"display_order" json:"display_order"`
	// Si el item es visible en este template específico
	IsVisible *bool              `db:"is_visible" json:"is_visible"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Permisos globales del sistema
type AuthPermission struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Description *string            `db:"description" json:"description"`
	Module      *string            `db:"module" json:"module"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// Scope del permiso: own (propio tenant), all (global), none (sin scope)
	Scope *string `db:"scope" json:"scope"`
}

type AuthRefreshToken struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Token      string             `db:"token" json:"token"`
	DeviceInfo []byte             `db:"device_info" json:"device_info"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Roles de usuario (NULL tenant_id = rol de sistema)
type AuthRole struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	IsSystem    *bool              `db:"is_system" json:"is_system"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthRolePermission struct {
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
}

type AuthSession struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TokenHash      string             `db:"token_hash" json:"token_hash"`
	DeviceInfo     []byte             `db:"device_info" json:"device_info"`
	IpAddress      *netip.Addr        `db:"ip_address" json:"ip_address"`
	LastActivityAt pgtype.Timestamptz `db:"last_activity_at" json:"last_activity_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Asignación de plantilla de menú por tenant
type AuthTenantMenuAssignment struct {
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TemplateID pgtype.UUID        `db:"template_id" json:"template_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Usuarios del sistema por tenant
type AuthUser struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	TenantID      pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Email         string             `db:"email" json:"email"`
	PasswordHash  string             `db:"password_hash" json:"password_hash"`
	FirstName     string             `db:"first_name" json:"first_name"`
	LastName      string             `db:"last_name" json:"last_name"`
	Phone         *string            `db:"phone" json:"phone"`
	AvatarUrl     *string            `db:"avatar_url" json:"avatar_url"`
	IsActive      *bool              `db:"is_active" json:"is_active"`
	EmailVerified *bool              `db:"email_verified" json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Usuario que creó este registro
	CreatedBy pgtype.UUID `db:"created_by" json:"created_by"`
	// Último usuario que modificó este registro
	UpdatedBy pgtype.UUID `db:"updated_by" json:"updated_by"`
}

type AuthUserRole struct {
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	RoleID     pgtype.UUID        `db:"role_id" json:"role_id"`
	AssignedAt pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
}

// Facturas por tenant
type BillingInvoice struct {
	ID            pgtype.UUID              `db:"id" json:"id"`
	TenantID      pgtype.UUID              `db:"tenant_id" json:"tenant_id"`
	InvoiceNumber string                   `db:"invoice_number" json:"invoice_number"`
	Folio         *string                  `db:"folio" json:"folio"`
	Serie         *string                  `db:"serie" json:"serie"`
	ClientID      pgtype.UUID              `db:"client_id" json:"client_id"`
	PolicyID      pgtype.UUID              `db:"policy_id" json:"policy_id"`
	Status        NullBillingInvoiceStatus `db:"status" json:"status"`
	IssueDate     pgtype.Date              `db:"issue_date" json:"issue_date"`
	DueDate       pgtype.Date              `db:"due_date" json:"due_date"`
	Subtotal      pgtype.Numeric           `db:"subtotal" json:"subtotal"`
	Discount      pgtype.Numeric           `db:"discount" json:"discount"`
	TaxRate       pgtype.Numeric           `db:"tax_rate" json:"tax_rate"`
	TaxAmount     pgtype.Numeric           `db:"tax_amount" json:"tax_amount"`
	Total         pgtype.Numeric           `db:"total" json:"total"`
	PaidAmount    pgtype.Numeric           `db:"paid_amount" json:"paid_amount"`
	Balance       pgtype.Numeric           `db:"balance" json:"balance"`
	Currency      *string                  `db:"currency" json:"currency"`
	CfdiUuid      *string                  `db:"cfdi_uuid" json:"cfdi_uuid"`
	CfdiStatus    *string                  `db:"cfdi_status" json:"cfdi_status"`
	UsoCfdi       *string                  `db:"uso_cfdi" json:"uso_cfdi"`
	FormaPago     *string                  `db:"forma_pago" json:"forma_pago"`
	MetodoPago    *string                  `db:"metodo_pago" json:"metodo_pago"`
	XmlUrl        *string                  `db:"xml_url" json:"xml_url"`
	PdfUrl        *string                  `db:"pdf_url" json:"pdf_url"`
	Notes         *string                  `db:"notes" json:"notes"`
	InternalNotes *string                  `db:"internal_notes" json:"internal_notes"`
	CreatedBy     pgtype.UUID              `db:"created_by" json:"created_by"`
	StampedAt     pgtype.Timestamptz       `db:"stamped_at" json:"stamped_at"`
	CancelledAt   pgtype.Timestamptz       `db:"cancelled_at" json:"cancelled_at"`
	CreatedAt     pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
}

type BillingInvoiceItem struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	InvoiceID   pgtype.UUID        `db:"invoice_id" json:"invoice_id"`
	ProductKey  *string            `db:"product_key" json:"product_key"`
	UnitKey     *string            `db:"unit_key" json:"unit_key"`
	Description string             `db:"description" json:"description"`
	Quantity    pgtype.Numeric     `db:"quantity" json:"quantity"`
	UnitPrice   pgtype.Numeric     `db:"unit_price" json:"unit_price"`
	Discount    pgtype.Numeric     `db:"discount" json:"discount"`
	TaxRate     pgtype.Numeric     `db:"tax_rate" json:"tax_rate"`
	Amount      pgtype.Numeric     `db:"amount" json:"amount"`
	SortOrder   *int32             `db:"sort_order" json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Complementos de pago CFDI 4.0
type BillingPaymentComplement struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ComplementNumber string             `db:"complement_number" json:"complement_number"`
	InvoiceID        pgtype.UUID        `db:"invoice_id" json:"invoice_id"`
	PaymentDate      pgtype.Date        `db:"payment_date" json:"payment_date"`
	PaymentAmount    pgtype.Numeric     `db:"payment_amount" json:"payment_amount"`
	PaymentMethod    *string            `db:"payment_method" json:"payment_method"`
	CfdiUuid         *string            `db:"cfdi_uuid" json:"cfdi_uuid"`
	XmlUrl           *string            `db:"xml_url" json:"xml_url"`
	PdfUrl           *string            `db:"pdf_url" json:"pdf_url"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Estados de cuenta mensuales
type CollectionAccountStatement struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ClientID         pgtype.UUID        `db:"client_id" json:"client_id"`
	StatementNumber  string             `db:"statement_number" json:"statement_number"`
	PeriodStart      pgtype.Date        `db:"period_start" json:"period_start"`
	PeriodEnd        pgtype.Date        `db:"period_end" json:"period_end"`
	OpeningBalance   pgtype.Numeric     `db:"opening_balance" json:"opening_balance"`
	Charges          pgtype.Numeric     `db:"charges" json:"charges"`
	PaymentsReceived pgtype.Numeric     `db:"payments_received" json:"payments_received"`
	Adjustments      pgtype.Numeric     `db:"adjustments" json:"adjustments"`
	ClosingBalance   pgtype.Numeric     `db:"closing_balance" json:"closing_balance"`
	PdfUrl           *string            `db:"pdf_url" json:"pdf_url"`
	SentAt           pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	GeneratedAt      pgtype.Timestamptz `db:"generated_at" json:"generated_at"`
}

type CollectionCreditNote struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	TenantID           pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	CreditNoteNumber   string             `db:"credit_note_number" json:"credit_note_number"`
	InvoiceID          pgtype.UUID        `db:"invoice_id" json:"invoice_id"`
	ClientID           pgtype.UUID        `db:"client_id" json:"client_id"`
	Amount             pgtype.Numeric     `db:"amount" json:"amount"`
	Reason             string             `db:"reason" json:"reason"`
	AppliedToInvoiceID pgtype.UUID        `db:"applied_to_invoice_id" json:"applied_to_invoice_id"`
	CfdiUuid           *string            `db:"cfdi_uuid" json:"cfdi_uuid"`
	XmlUrl             *string            `db:"xml_url" json:"xml_url"`
	PdfUrl             *string            `db:"pdf_url" json:"pdf_url"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Pagos recibidos por tenant
type CollectionPayment struct {
	ID                pgtype.UUID                 `db:"id" json:"id"`
	TenantID          pgtype.UUID                 `db:"tenant_id" json:"tenant_id"`
	PaymentReference  string                      `db:"payment_reference" json:"payment_reference"`
	InvoiceID         pgtype.UUID                 `db:"invoice_id" json:"invoice_id"`
	ClientID          pgtype.UUID                 `db:"client_id" json:"client_id"`
	Amount            pgtype.Numeric              `db:"amount" json:"amount"`
	PaymentMethod     CollectionPaymentMethod     `db:"payment_method" json:"payment_method"`
	Status            NullCollectionPaymentStatus `db:"status" json:"status"`
	TransactionID     *string                     `db:"transaction_id" json:"transaction_id"`
	AuthorizationCode *string                     `db:"authorization_code" json:"authorization_code"`
	BankName          *string                     `db:"bank_name" json:"bank_name"`
	AccountLastFour   *string                     `db:"account_last_four" json:"account_last_four"`
	PaymentDate       pgtype.Date                 `db:"payment_date" json:"payment_date"`
	ProcessedAt       pgtype.Timestamptz          `db:"processed_at" json:"processed_at"`
	ReceiptUrl        *string                     `db:"receipt_url" json:"receipt_url"`
	Notes             *string                     `db:"notes" json:"notes"`
	CreatedBy         pgtype.UUID                 `db:"created_by" json:"created_by"`
	CreatedAt         pgtype.Timestamptz          `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz          `db:"updated_at" json:"updated_at"`
}

type CollectionPaymentReminder struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	TenantID     pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	InvoiceID    pgtype.UUID        `db:"invoice_id" json:"invoice_id"`
	ClientID     pgtype.UUID        `db:"client_id" json:"client_id"`
	ReminderType string             `db:"reminder_type" json:"reminder_type"`
	Channel      string             `db:"channel" json:"channel"`
	SentAt       pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	DeliveredAt  pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	OpenedAt     pgtype.Timestamptz `db:"opened_at" json:"opened_at"`
	Response     *string            `db:"response" json:"response"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Resultados de análisis generados por IA
type IntelligenceAnalysis struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	TenantID       pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	AnalysisType   string      `db:"analysis_type" json:"analysis_type"`
	InputType      string      `db:"input_type" json:"input_type"`
	InputReference pgtype.UUID `db:"input_reference" json:"input_reference"`
	InputData      []byte      `db:"input_data" json:"input_data"`
	Result         []byte      `db:"result" json:"result"`
	// Score de confianza del modelo (0.0 a 1.0)
	ConfidenceScore   pgtype.Numeric     `db:"confidence_score" json:"confidence_score"`
	ApiCallID         pgtype.UUID        `db:"api_call_id" json:"api_call_id"`
	ModelUsed         *string            `db:"model_used" json:"model_used"`
	ProcessingTimeMs  *int32             `db:"processing_time_ms" json:"processing_time_ms"`
	IsVerified        *bool              `db:"is_verified" json:"is_verified"`
	VerifiedBy        pgtype.UUID        `db:"verified_by" json:"verified_by"`
	VerifiedAt        pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	VerificationNotes *string            `db:"verification_notes" json:"verification_notes"`
	IsCorrect         *bool              `db:"is_correct" json:"is_correct"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Historial completo de llamadas a APIs de IA
type IntelligenceApiCall struct {
	ID               pgtype.UUID    `db:"id" json:"id"`
	TenantID         pgtype.UUID    `db:"tenant_id" json:"tenant_id"`
	ModelConfigID    pgtype.UUID    `db:"model_config_id" json:"model_config_id"`
	PromptTemplateID pgtype.UUID    `db:"prompt_template_id" json:"prompt_template_id"`
	Provider         string         `db:"provider" json:"provider"`
	Model            string         `db:"model" json:"model"`
	PromptText       string         `db:"prompt_text" json:"prompt_text"`
	SystemPrompt     *string        `db:"system_prompt" json:"system_prompt"`
	Temperature      pgtype.Numeric `db:"temperature" json:"temperature"`
	MaxTokens        *int32         `db:"max_tokens" json:"max_tokens"`
	Parameters       []byte         `db:"parameters" json:"parameters"`
	ResponseText     *string        `db:"response_text" json:"response_text"`
	FinishReason     *string        `db:"finish_reason" json:"finish_reason"`
	PromptTokens     *int32         `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens *int32         `db:"completion_tokens" json:"completion_tokens"`
	TotalTokens      *int32         `db:"total_tokens" json:"total_tokens"`
	// Costo estimado basado en tokens y pricing del proveedor
	EstimatedCostUsd  pgtype.Numeric     `db:"estimated_cost_usd" json:"estimated_cost_usd"`
	LatencyMs         *int32             `db:"latency_ms" json:"latency_ms"`
	StartedAt         pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	Status            string             `db:"status" json:"status"`
	ErrorMessage      *string            `db:"error_message" json:"error_message"`
	RelatedEntityType *string            `db:"related_entity_type" json:"related_entity_type"`
	RelatedEntityID   pgtype.UUID        `db:"related_entity_id" json:"related_entity_id"`
	TriggeredBy       pgtype.UUID        `db:"triggered_by" json:"triggered_by"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Configuración de modelos de IA por tenant
type IntelligenceModelConfig struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	TenantID  pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Name      string      `db:"name" json:"name"`
	Provider  string      `db:"provider" json:"provider"`
	ModelName string      `db:"model_name" json:"model_name"`
	// API key encriptada - nunca guardar en texto plano
	ApiKeyEncrypted     *string            `db:"api_key_encrypted" json:"api_key_encrypted"`
	ApiEndpoint         *string            `db:"api_endpoint" json:"api_endpoint"`
	ApiVersion          *string            `db:"api_version" json:"api_version"`
	DefaultTemperature  pgtype.Numeric     `db:"default_temperature" json:"default_temperature"`
	DefaultMaxTokens    *int32             `db:"default_max_tokens" json:"default_max_tokens"`
	DefaultTopP         pgtype.Numeric     `db:"default_top_p" json:"default_top_p"`
	DefaultTopK         *int32             `db:"default_top_k" json:"default_top_k"`
	MaxTokensPerRequest *int32             `db:"max_tokens_per_request" json:"max_tokens_per_request"`
	MaxRequestsPerDay   *int32             `db:"max_requests_per_day" json:"max_requests_per_day"`
	MaxRequestsPerHour  *int32             `db:"max_requests_per_hour" json:"max_requests_per_hour"`
	MonthlyBudgetUsd    pgtype.Numeric     `db:"monthly_budget_usd" json:"monthly_budget_usd"`
	IsActive            *bool              `db:"is_active" json:"is_active"`
	IsDefault           *bool              `db:"is_default" json:"is_default"`
	Description         *string            `db:"description" json:"description"`
	Capabilities        []byte             `db:"capabilities" json:"capabilities"`
	Settings            []byte             `db:"settings" json:"settings"`
	CreatedBy           pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Plantillas de prompts pre-configuradas para casos de uso comunes
type IntelligencePromptTemplate struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	TenantID           pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Name               string             `db:"name" json:"name"`
	Category           string             `db:"category" json:"category"`
	SystemPrompt       *string            `db:"system_prompt" json:"system_prompt"`
	UserPromptTemplate string             `db:"user_prompt_template" json:"user_prompt_template"`
	ModelConfigID      pgtype.UUID        `db:"model_config_id" json:"model_config_id"`
	Temperature        pgtype.Numeric     `db:"temperature" json:"temperature"`
	MaxTokens          *int32             `db:"max_tokens" json:"max_tokens"`
	ResponseFormat     *string            `db:"response_format" json:"response_format"`
	Description        *string            `db:"description" json:"description"`
	Variables          []byte             `db:"variables" json:"variables"`
	ExampleInput       []byte             `db:"example_input" json:"example_input"`
	ExampleOutput      *string            `db:"example_output" json:"example_output"`
	IsActive           *bool              `db:"is_active" json:"is_active"`
	Version            *int32             `db:"version" json:"version"`
	ParentTemplateID   pgtype.UUID        `db:"parent_template_id" json:"parent_template_id"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Resúmenes de uso y costos por período
type IntelligenceUsageSummary struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	TenantID              pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	PeriodType            string             `db:"period_type" json:"period_type"`
	PeriodStart           pgtype.Date        `db:"period_start" json:"period_start"`
	PeriodEnd             pgtype.Date        `db:"period_end" json:"period_end"`
	TotalApiCalls         *int32             `db:"total_api_calls" json:"total_api_calls"`
	SuccessfulCalls       *int32             `db:"successful_calls" json:"successful_calls"`
	FailedCalls           *int32             `db:"failed_calls" json:"failed_calls"`
	TotalTokens           *int32             `db:"total_tokens" json:"total_tokens"`
	TotalPromptTokens     *int32             `db:"total_prompt_tokens" json:"total_prompt_tokens"`
	TotalCompletionTokens *int32             `db:"total_completion_tokens" json:"total_completion_tokens"`
	TotalCostUsd          pgtype.Numeric     `db:"total_cost_usd" json:"total_cost_usd"`
	UsageByProvider       []byte             `db:"usage_by_provider" json:"usage_by_provider"`
	UsageByModel          []byte             `db:"usage_by_model" json:"usage_by_model"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Catálogo global de marcas
type InventoryBrand struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	LogoUrl   *string            `db:"logo_url" json:"logo_url"`
	Website   *string            `db:"website" json:"website"`
	Country   *string            `db:"country" json:"country"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Cámaras multi-marca (Avigilon, Hikvision, Dahua, Axis, etc.)
type InventoryCamera struct {
	ID          pgtype.UUID             `db:"id" json:"id"`
	TenantID    pgtype.UUID             `db:"tenant_id" json:"tenant_id"`
	NvrServerID pgtype.UUID             `db:"nvr_server_id" json:"nvr_server_id"`
	SiteID      pgtype.UUID             `db:"site_id" json:"site_id"`
	AreaID      pgtype.UUID             `db:"area_id" json:"area_id"`
	ModelID     pgtype.UUID             `db:"model_id" json:"model_id"`
	Consecutive *int32                  `db:"consecutive" json:"consecutive"`
	Name        string                  `db:"name" json:"name"`
	Code        *string                 `db:"code" json:"code"`
	CameraType  NullInventoryCameraType `db:"camera_type" json:"camera_type"`
	// Nombre completo del modelo (ej: Avigilon (ONVIF) 2.0-H3M-DO1)
	CameraModelName     *string                      `db:"camera_model_name" json:"camera_model_name"`
	Generation          *string                      `db:"generation" json:"generation"`
	IpAddress           *netip.Addr                  `db:"ip_address" json:"ip_address"`
	MacAddress          net.HardwareAddr             `db:"mac_address" json:"mac_address"`
	Resolution          *string                      `db:"resolution" json:"resolution"`
	Megapixels          pgtype.Numeric               `db:"megapixels" json:"megapixels"`
	Ips                 *int32                       `db:"ips" json:"ips"`
	BitrateKbps         *int32                       `db:"bitrate_kbps" json:"bitrate_kbps"`
	Quality             *int32                       `db:"quality" json:"quality"`
	FirmwareVersion     *string                      `db:"firmware_version" json:"firmware_version"`
	SerialNumber        *string                      `db:"serial_number" json:"serial_number"`
	Area                *string                      `db:"area" json:"area"`
	Zone                *string                      `db:"zone" json:"zone"`
	LocationDescription *string                      `db:"location_description" json:"location_description"`
	Project             *string                      `db:"project" json:"project"`
	HasCounting         *bool                        `db:"has_counting" json:"has_counting"`
	CountingEnabled     *bool                        `db:"counting_enabled" json:"counting_enabled"`
	Status              NullInventoryEquipmentStatus `db:"status" json:"status"`
	InstallationDate    pgtype.Date                  `db:"installation_date" json:"installation_date"`
	WarrantyExpiryDate  pgtype.Date                  `db:"warranty_expiry_date" json:"warranty_expiry_date"`
	// Especificaciones técnicas flexibles por marca en JSON
	Specifications  []byte             `db:"specifications" json:"specifications"`
	AnalyticsConfig []byte             `db:"analytics_config" json:"analytics_config"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	Notes           *string            `db:"notes" json:"notes"`
	Comments        *string            `db:"comments" json:"comments"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy       pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedBy       pgtype.UUID        `db:"updated_by" json:"updated_by"`
}

// Histórico de asignaciones cámara-NVR
type InventoryCameraNvrHistory struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	CameraID       pgtype.UUID        `db:"camera_id" json:"camera_id"`
	OldNvrServerID pgtype.UUID        `db:"old_nvr_server_id" json:"old_nvr_server_id"`
	NewNvrServerID pgtype.UUID        `db:"new_nvr_server_id" json:"new_nvr_server_id"`
	Reason         *string            `db:"reason" json:"reason"`
	ChangedAt      pgtype.Timestamptz `db:"changed_at" json:"changed_at"`
	ChangedBy      pgtype.UUID        `db:"changed_by" json:"changed_by"`
}

// Equipos instalados por tenant
type InventoryEquipment struct {
	ID                  pgtype.UUID                  `db:"id" json:"id"`
	TenantID            pgtype.UUID                  `db:"tenant_id" json:"tenant_id"`
	ClientID            pgtype.UUID                  `db:"client_id" json:"client_id"`
	SiteID              pgtype.UUID                  `db:"site_id" json:"site_id"`
	AreaID              pgtype.UUID                  `db:"area_id" json:"area_id"`
	ModelID             pgtype.UUID                  `db:"model_id" json:"model_id"`
	EquipmentTypeID     pgtype.UUID                  `db:"equipment_type_id" json:"equipment_type_id"`
	SerialNumber        *string                      `db:"serial_number" json:"serial_number"`
	AssetTag            *string                      `db:"asset_tag" json:"asset_tag"`
	IpAddress           *netip.Addr                  `db:"ip_address" json:"ip_address"`
	MacAddress          net.HardwareAddr             `db:"mac_address" json:"mac_address"`
	Status              NullInventoryEquipmentStatus `db:"status" json:"status"`
	InstallationDate    pgtype.Date                  `db:"installation_date" json:"installation_date"`
	WarrantyExpiryDate  pgtype.Date                  `db:"warranty_expiry_date" json:"warranty_expiry_date"`
	LocationDescription *string                      `db:"location_description" json:"location_description"`
	Latitude            pgtype.Numeric               `db:"latitude" json:"latitude"`
	Longitude           pgtype.Numeric               `db:"longitude" json:"longitude"`
	Notes               *string                      `db:"notes" json:"notes"`
	Metadata            []byte                       `db:"metadata" json:"metadata"`
	LastMaintenanceAt   pgtype.Timestamptz           `db:"last_maintenance_at" json:"last_maintenance_at"`
	NextMaintenanceAt   pgtype.Timestamptz           `db:"next_maintenance_at" json:"next_maintenance_at"`
	CreatedAt           pgtype.Timestamptz           `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz           `db:"updated_at" json:"updated_at"`
}

// Catálogo global de tipos de equipo
type InventoryEquipmentType struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Icon        *string            `db:"icon" json:"icon"`
	Category    *string            `db:"category" json:"category"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Lotes de importación masiva (Excel, CSV, OCR)
type InventoryImportBatch struct {
	ID             pgtype.UUID               `db:"id" json:"id"`
	TenantID       pgtype.UUID               `db:"tenant_id" json:"tenant_id"`
	BatchName      string                    `db:"batch_name" json:"batch_name"`
	SourceType     InventoryImportSourceType `db:"source_type" json:"source_type"`
	SourceFilename *string                   `db:"source_filename" json:"source_filename"`
	TargetTable    string                    `db:"target_table" json:"target_table"`
	ColumnMapping  []byte                    `db:"column_mapping" json:"column_mapping"`
	TotalRows      *int32                    `db:"total_rows" json:"total_rows"`
	ProcessedRows  *int32                    `db:"processed_rows" json:"processed_rows"`
	SuccessRows    *int32                    `db:"success_rows" json:"success_rows"`
	ErrorRows      *int32                    `db:"error_rows" json:"error_rows"`
	SkippedRows    *int32                    `db:"skipped_rows" json:"skipped_rows"`
	Status         NullInventoryImportStatus `db:"status" json:"status"`
	ErrorMessage   *string                   `db:"error_message" json:"error_message"`
	SourceFileID   pgtype.UUID               `db:"source_file_id" json:"source_file_id"`
	StartedAt      pgtype.Timestamptz        `db:"started_at" json:"started_at"`
	CompletedAt    pgtype.Timestamptz        `db:"completed_at" json:"completed_at"`
	CreatedAt      pgtype.Timestamptz        `db:"created_at" json:"created_at"`
	CreatedBy      pgtype.UUID               `db:"created_by" json:"created_by"`
}

// Items individuales de cada lote de importación
type InventoryImportBatchItem struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	TenantID           pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	BatchID            pgtype.UUID        `db:"batch_id" json:"batch_id"`
	RowNumber          int32              `db:"row_number" json:"row_number"`
	RawData            []byte             `db:"raw_data" json:"raw_data"`
	Status             *string            `db:"status" json:"status"`
	ErrorMessage       *string            `db:"error_message" json:"error_message"`
	CreatedRecordID    pgtype.UUID        `db:"created_record_id" json:"created_record_id"`
	CreatedRecordTable *string            `db:"created_record_table" json:"created_record_table"`
	ProcessedAt        pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type InventoryMaintenanceHistory struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	TenantID        pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	EquipmentID     pgtype.UUID        `db:"equipment_id" json:"equipment_id"`
	TicketID        pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	ServiceDate     pgtype.Date        `db:"service_date" json:"service_date"`
	ServiceType     string             `db:"service_type" json:"service_type"`
	PerformedBy     pgtype.UUID        `db:"performed_by" json:"performed_by"`
	Description     *string            `db:"description" json:"description"`
	Findings        *string            `db:"findings" json:"findings"`
	PartsReplaced   []byte             `db:"parts_replaced" json:"parts_replaced"`
	LaborHours      pgtype.Numeric     `db:"labor_hours" json:"labor_hours"`
	NextServiceDate pgtype.Date        `db:"next_service_date" json:"next_service_date"`
	Photos          []byte             `db:"photos" json:"photos"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Catálogo global de modelos por marca
type InventoryModel struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	BrandID         pgtype.UUID        `db:"brand_id" json:"brand_id"`
	EquipmentTypeID pgtype.UUID        `db:"equipment_type_id" json:"equipment_type_id"`
	Name            string             `db:"name" json:"name"`
	PartNumber      *string            `db:"part_number" json:"part_number"`
	Specifications  []byte             `db:"specifications" json:"specifications"`
	DatasheetUrl    *string            `db:"datasheet_url" json:"datasheet_url"`
	ImageUrl        *string            `db:"image_url" json:"image_url"`
	IsActive        *bool              `db:"is_active" json:"is_active"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Licencias activas por servidor NVR
type InventoryNvrLicense struct {
	ID            pgtype.UUID          `db:"id" json:"id"`
	TenantID      pgtype.UUID          `db:"tenant_id" json:"tenant_id"`
	NvrServerID   pgtype.UUID          `db:"nvr_server_id" json:"nvr_server_id"`
	LicenseKey    *string              `db:"license_key" json:"license_key"`
	LicenseType   InventoryLicenseType `db:"license_type" json:"license_type"`
	Edition       *string              `db:"edition" json:"edition"`
	TotalLicenses int32                `db:"total_licenses" json:"total_licenses"`
	UsedLicenses  int32                `db:"used_licenses" json:"used_licenses"`
	IssueDate     pgtype.Date          `db:"issue_date" json:"issue_date"`
	ExpiryDate    pgtype.Date          `db:"expiry_date" json:"expiry_date"`
	IsPerpetual   *bool                `db:"is_perpetual" json:"is_perpetual"`
	IsActive      *bool                `db:"is_active" json:"is_active"`
	Metadata      []byte               `db:"metadata" json:"metadata"`
	CreatedAt     pgtype.Timestamptz   `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz   `db:"updated_at" json:"updated_at"`
}

// Histórico de cambios en licencias para auditoría
type InventoryNvrLicenseHistory struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	TenantID     pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	NvrLicenseID pgtype.UUID        `db:"nvr_license_id" json:"nvr_license_id"`
	NvrServerID  pgtype.UUID        `db:"nvr_server_id" json:"nvr_server_id"`
	ChangeType   string             `db:"change_type" json:"change_type"`
	FieldChanged *string            `db:"field_changed" json:"field_changed"`
	OldValue     *string            `db:"old_value" json:"old_value"`
	NewValue     *string            `db:"new_value" json:"new_value"`
	Description  *string            `db:"description" json:"description"`
	ChangedAt    pgtype.Timestamptz `db:"changed_at" json:"changed_at"`
	ChangedBy    pgtype.UUID        `db:"changed_by" json:"changed_by"`
}

// Servidores NVR/VMS (multi-marca: Avigilon, Milestone, Genetec, etc.)
type InventoryNvrServer struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	SiteID   pgtype.UUID `db:"site_id" json:"site_id"`
	BrandID  pgtype.UUID `db:"brand_id" json:"brand_id"`
	Name     string      `db:"name" json:"name"`
	Code     *string     `db:"code" json:"code"`
	// ID del servidor en el VMS (genérico para cualquier marca)
	VmsServerID            *string                      `db:"vms_server_id" json:"vms_server_id"`
	Edition                *string                      `db:"edition" json:"edition"`
	VmsVersion             *string                      `db:"vms_version" json:"vms_version"`
	CameraChannels         *int32                       `db:"camera_channels" json:"camera_channels"`
	TpvChannels            *int32                       `db:"tpv_channels" json:"tpv_channels"`
	LprChannels            *int32                       `db:"lpr_channels" json:"lpr_channels"`
	IntegrationConnections *int32                       `db:"integration_connections" json:"integration_connections"`
	Model                  *string                      `db:"model" json:"model"`
	ServiceTag             *string                      `db:"service_tag" json:"service_tag"`
	ServiceCode            *string                      `db:"service_code" json:"service_code"`
	Processor              *string                      `db:"processor" json:"processor"`
	RamGb                  *int32                       `db:"ram_gb" json:"ram_gb"`
	OsName                 *string                      `db:"os_name" json:"os_name"`
	SystemType             *string                      `db:"system_type" json:"system_type"`
	IpAddress              *netip.Addr                  `db:"ip_address" json:"ip_address"`
	SubnetMask             *netip.Addr                  `db:"subnet_mask" json:"subnet_mask"`
	Gateway                *netip.Addr                  `db:"gateway" json:"gateway"`
	MacAddress             net.HardwareAddr             `db:"mac_address" json:"mac_address"`
	TotalStorageTb         pgtype.Numeric               `db:"total_storage_tb" json:"total_storage_tb"`
	RecordingDays          *int32                       `db:"recording_days" json:"recording_days"`
	LaunchDate             pgtype.Date                  `db:"launch_date" json:"launch_date"`
	WarrantyExpiryDate     pgtype.Date                  `db:"warranty_expiry_date" json:"warranty_expiry_date"`
	InstallationDate       pgtype.Date                  `db:"installation_date" json:"installation_date"`
	Status                 NullInventoryEquipmentStatus `db:"status" json:"status"`
	AdminUsername          *string                      `db:"admin_username" json:"admin_username"`
	AdminPasswordEncrypted *string                      `db:"admin_password_encrypted" json:"admin_password_encrypted"`
	// Especificaciones de hardware adicionales en formato JSON
	HardwareSpecs []byte             `db:"hardware_specs" json:"hardware_specs"`
	NetworkConfig []byte             `db:"network_config" json:"network_config"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Notes         *string            `db:"notes" json:"notes"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CreatedBy     pgtype.UUID        `db:"created_by" json:"created_by"`
	UpdatedBy     pgtype.UUID        `db:"updated_by" json:"updated_by"`
}

// Unidades de almacenamiento (discos) por NVR
type InventoryNvrStorageUnit struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	NvrServerID      pgtype.UUID        `db:"nvr_server_id" json:"nvr_server_id"`
	SlotNumber       *int32             `db:"slot_number" json:"slot_number"`
	DiskType         *string            `db:"disk_type" json:"disk_type"`
	Brand            *string            `db:"brand" json:"brand"`
	Model            *string            `db:"model" json:"model"`
	SerialNumber     *string            `db:"serial_number" json:"serial_number"`
	CapacityTb       pgtype.Numeric     `db:"capacity_tb" json:"capacity_tb"`
	Status           *string            `db:"status" json:"status"`
	HealthPercentage *int32             `db:"health_percentage" json:"health_percentage"`
	InstallationDate pgtype.Date        `db:"installation_date" json:"installation_date"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PoliciesArea struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	SiteID      pgtype.UUID        `db:"site_id" json:"site_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	Floor       *string            `db:"floor" json:"floor"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Empresas cliente con servicios CCTV
type PoliciesClient struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	CompanyName string             `db:"company_name" json:"company_name"`
	LegalName   *string            `db:"legal_name" json:"legal_name"`
	Rfc         *string            `db:"rfc" json:"rfc"`
	Address     *string            `db:"address" json:"address"`
	City        *string            `db:"city" json:"city"`
	State       *string            `db:"state" json:"state"`
	PostalCode  *string            `db:"postal_code" json:"postal_code"`
	Country     *string            `db:"country" json:"country"`
	Email       *string            `db:"email" json:"email"`
	Phone       *string            `db:"phone" json:"phone"`
	IsActive    *bool              `db:"is_active" json:"is_active"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PoliciesClientContact struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	TenantID  pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ClientID  pgtype.UUID        `db:"client_id" json:"client_id"`
	Name      string             `db:"name" json:"name"`
	Position  *string            `db:"position" json:"position"`
	Email     *string            `db:"email" json:"email"`
	Phone     *string            `db:"phone" json:"phone"`
	Mobile    *string            `db:"mobile" json:"mobile"`
	IsPrimary *bool              `db:"is_primary" json:"is_primary"`
	Notes     *string            `db:"notes" json:"notes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PoliciesCoveragePlan struct {
	ID                         pgtype.UUID        `db:"id" json:"id"`
	TenantID                   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Name                       string             `db:"name" json:"name"`
	Description                *string            `db:"description" json:"description"`
	PreventiveVisitsPerYear    *int32             `db:"preventive_visits_per_year" json:"preventive_visits_per_year"`
	EmergencyResponseTimeHours *int32             `db:"emergency_response_time_hours" json:"emergency_response_time_hours"`
	IncludesParts              *bool              `db:"includes_parts" json:"includes_parts"`
	IncludesLabor              *bool              `db:"includes_labor" json:"includes_labor"`
	MonthlyPrice               pgtype.Numeric     `db:"monthly_price" json:"monthly_price"`
	IsActive                   *bool              `db:"is_active" json:"is_active"`
	Features                   []byte             `db:"features" json:"features"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Contratos de servicio activos
type PoliciesPolicy struct {
	ID             pgtype.UUID              `db:"id" json:"id"`
	TenantID       pgtype.UUID              `db:"tenant_id" json:"tenant_id"`
	PolicyNumber   string                   `db:"policy_number" json:"policy_number"`
	ClientID       pgtype.UUID              `db:"client_id" json:"client_id"`
	SiteID         pgtype.UUID              `db:"site_id" json:"site_id"`
	CoveragePlanID pgtype.UUID              `db:"coverage_plan_id" json:"coverage_plan_id"`
	Status         NullPoliciesPolicyStatus `db:"status" json:"status"`
	StartDate      pgtype.Date              `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date              `db:"end_date" json:"end_date"`
	MonthlyPayment pgtype.Numeric           `db:"monthly_payment" json:"monthly_payment"`
	PaymentDay     *int32                   `db:"payment_day" json:"payment_day"`
	Notes          *string                  `db:"notes" json:"notes"`
	TermsAccepted  *bool                    `db:"terms_accepted" json:"terms_accepted"`
	ContractUrl    *string                  `db:"contract_url" json:"contract_url"`
	CreatedBy      pgtype.UUID              `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	Vendor         *string                  `db:"vendor" json:"vendor"`
	ContractType   *string                  `db:"contract_type" json:"contract_type"`
	AnnualValue    pgtype.Numeric           `db:"annual_value" json:"annual_value"`
	CoverageJson   []byte                   `db:"coverage_json" json:"coverage_json"`
	Metadata       []byte                   `db:"metadata" json:"metadata"`
}

type PoliciesPolicyAsset struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	PolicyID    pgtype.UUID        `db:"policy_id" json:"policy_id"`
	EquipmentID pgtype.UUID        `db:"equipment_id" json:"equipment_id"`
	NvrServerID pgtype.UUID        `db:"nvr_server_id" json:"nvr_server_id"`
	CameraID    pgtype.UUID        `db:"camera_id" json:"camera_id"`
	Notes       *string            `db:"notes" json:"notes"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PoliciesPolicyHistory struct {
	ID             pgtype.UUID              `db:"id" json:"id"`
	TenantID       pgtype.UUID              `db:"tenant_id" json:"tenant_id"`
	PolicyID       pgtype.UUID              `db:"policy_id" json:"policy_id"`
	Action         string                   `db:"action" json:"action"`
	PreviousStatus NullPoliciesPolicyStatus `db:"previous_status" json:"previous_status"`
	NewStatus      NullPoliciesPolicyStatus `db:"new_status" json:"new_status"`
	Notes          *string                  `db:"notes" json:"notes"`
	Metadata       []byte                   `db:"metadata" json:"metadata"`
	CreatedBy      pgtype.UUID              `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz       `db:"created_at" json:"created_at"`
}

// Ubicaciones físicas de los clientes
type PoliciesSite struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	TenantID     pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ClientID     pgtype.UUID        `db:"client_id" json:"client_id"`
	Name         string             `db:"name" json:"name"`
	Address      *string            `db:"address" json:"address"`
	City         *string            `db:"city" json:"city"`
	State        *string            `db:"state" json:"state"`
	PostalCode   *string            `db:"postal_code" json:"postal_code"`
	Latitude     pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude    pgtype.Numeric     `db:"longitude" json:"longitude"`
	ContactName  *string            `db:"contact_name" json:"contact_name"`
	ContactPhone *string            `db:"contact_phone" json:"contact_phone"`
	IsActive     *bool              `db:"is_active" json:"is_active"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Tabla principal de archivos subidos al sistema
type StorageFile struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	TenantID         pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Filename         string      `db:"filename" json:"filename"`
	OriginalFilename string      `db:"original_filename" json:"original_filename"`
	MimeType         string      `db:"mime_type" json:"mime_type"`
	FileSize         int64       `db:"file_size" json:"file_size"`
	// SHA256 hash para detectar duplicados
	FileHash          *string            `db:"file_hash" json:"file_hash"`
	StorageProvider   *string            `db:"storage_provider" json:"storage_provider"`
	StorageBucket     *string            `db:"storage_bucket" json:"storage_bucket"`
	StoragePath       string             `db:"storage_path" json:"storage_path"`
	StorageUrl        *string            `db:"storage_url" json:"storage_url"`
	Category          *string            `db:"category" json:"category"`
	RelatedEntityType *string            `db:"related_entity_type" json:"related_entity_type"`
	RelatedEntityID   pgtype.UUID        `db:"related_entity_id" json:"related_entity_id"`
	IsProcessed       *bool              `db:"is_processed" json:"is_processed"`
	ProcessedAt       pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	// EXIF, dimensiones, duración, etc. en formato JSON
	Metadata   []byte             `db:"metadata" json:"metadata"`
	UploadedBy pgtype.UUID        `db:"uploaded_by" json:"uploaded_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Auditoría de acceso a archivos
type StorageFileAccessLog struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	FileID     pgtype.UUID        `db:"file_id" json:"file_id"`
	AccessType string             `db:"access_type" json:"access_type"`
	AccessedBy pgtype.UUID        `db:"accessed_by" json:"accessed_by"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent  *string            `db:"user_agent" json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Cola de procesamiento de archivos (IA, OCR, thumbnails)
type StorageFileProcessing struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	FileID           pgtype.UUID        `db:"file_id" json:"file_id"`
	ProcessingType   string             `db:"processing_type" json:"processing_type"`
	Status           *string            `db:"status" json:"status"`
	Result           []byte             `db:"result" json:"result"`
	ErrorMessage     *string            `db:"error_message" json:"error_message"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ProcessingTimeMs *int32             `db:"processing_time_ms" json:"processing_time_ms"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StorageModuleStorageMapping struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ModuleName       string             `db:"module_name" json:"module_name"`
	CollectionName   string             `db:"collection_name" json:"collection_name"`
	ConfigID         pgtype.UUID        `db:"config_id" json:"config_id"`
	IsActive         *bool              `db:"is_active" json:"is_active"`
	MaxFileSizeMb    *int32             `db:"max_file_size_mb" json:"max_file_size_mb"`
	AllowedFileTypes []string           `db:"allowed_file_types" json:"allowed_file_types"`
	AutoResize       *bool              `db:"auto_resize" json:"auto_resize"`
	ThumbnailSizes   []int32            `db:"thumbnail_sizes" json:"thumbnail_sizes"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StorageStorageConfiguration struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ProviderID       int32              `db:"provider_id" json:"provider_id"`
	ConfigName       string             `db:"config_name" json:"config_name"`
	IsDefault        *bool              `db:"is_default" json:"is_default"`
	IsActive         *bool              `db:"is_active" json:"is_active"`
	Host             *string            `db:"host" json:"host"`
	Port             *int32             `db:"port" json:"port"`
	DatabaseName     *string            `db:"database_name" json:"database_name"`
	Username         *string            `db:"username" json:"username"`
	PasswordText     *string            `db:"password_text" json:"password_text"`
	ApiKey           *string            `db:"api_key" json:"api_key"`
	SecretKey        *string            `db:"secret_key" json:"secret_key"`
	BaseUrl          *string            `db:"base_url" json:"base_url"`
	BucketName       *string            `db:"bucket_name" json:"bucket_name"`
	Region           *string            `db:"region" json:"region"`
	ProjectID        *string            `db:"project_id" json:"project_id"`
	AdditionalConfig []byte             `db:"additional_config" json:"additional_config"`
	ModuleMappings   []byte             `db:"module_mappings" json:"module_mappings"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StorageStorageProvider struct {
	ID                     int32              `db:"id" json:"id"`
	ProviderName           string             `db:"provider_name" json:"provider_name"`
	DisplayName            string             `db:"display_name" json:"display_name"`
	Description            *string            `db:"description" json:"description"`
	ProviderType           string             `db:"provider_type" json:"provider_type"`
	IsActive               *bool              `db:"is_active" json:"is_active"`
	SupportsCollections    *bool              `db:"supports_collections" json:"supports_collections"`
	SupportsAuthentication *bool              `db:"supports_authentication" json:"supports_authentication"`
	SupportsDirectUpload   *bool              `db:"supports_direct_upload" json:"supports_direct_upload"`
	MaxFileSizeMb          *int32             `db:"max_file_size_mb" json:"max_file_size_mb"`
	AllowedFileTypes       []string           `db:"allowed_file_types" json:"allowed_file_types"`
	ConfigurationSchema    []byte             `db:"configuration_schema" json:"configuration_schema"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Proveedores de servicios CCTV (multi-tenant principal)
type Tenant struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	// Identificador URL-friendly para subdominios
	Slug         string  `db:"slug" json:"slug"`
	Domain       *string `db:"domain" json:"domain"`
	LogoUrl      *string `db:"logo_url" json:"logo_url"`
	PrimaryColor *string `db:"primary_color" json:"primary_color"`
	IsActive     *bool   `db:"is_active" json:"is_active"`
	// Configuración personalizada en JSON
	Settings         []byte             `db:"settings" json:"settings"`
	SubscriptionPlan *string            `db:"subscription_plan" json:"subscription_plan"`
	MaxUsers         *int32             `db:"max_users" json:"max_users"`
	MaxClients       *int32             `db:"max_clients" json:"max_clients"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// Secondary theme color extracted from logo
	SecondaryColor *string `db:"secondary_color" json:"secondary_color"`
	// Tertiary/accent theme color extracted from logo
	TertiaryColor *string `db:"tertiary_color" json:"tertiary_color"`
}

type TicketsSlaPolicy struct {
	ID                  pgtype.UUID               `db:"id" json:"id"`
	TenantID            pgtype.UUID               `db:"tenant_id" json:"tenant_id"`
	Name                string                    `db:"name" json:"name"`
	TicketPriority      NullTicketsTicketPriority `db:"ticket_priority" json:"ticket_priority"`
	TicketType          NullTicketsTicketType     `db:"ticket_type" json:"ticket_type"`
	ResponseTimeHours   int32                     `db:"response_time_hours" json:"response_time_hours"`
	ResolutionTimeHours int32                     `db:"resolution_time_hours" json:"resolution_time_hours"`
	IsDefault           bool                      `db:"is_default" json:"is_default"`
	IsActive            bool                      `db:"is_active" json:"is_active"`
	BusinessHours       []byte                    `db:"business_hours" json:"business_hours"`
	CreatedBy           pgtype.UUID               `db:"created_by" json:"created_by"`
	UpdatedBy           pgtype.UUID               `db:"updated_by" json:"updated_by"`
	CreatedAt           pgtype.Timestamptz        `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz        `db:"updated_at" json:"updated_at"`
}

// Tickets de servicio por tenant
type TicketsTicket struct {
	ID                   pgtype.UUID               `db:"id" json:"id"`
	TenantID             pgtype.UUID               `db:"tenant_id" json:"tenant_id"`
	TicketNumber         string                    `db:"ticket_number" json:"ticket_number"`
	ClientID             pgtype.UUID               `db:"client_id" json:"client_id"`
	SiteID               pgtype.UUID               `db:"site_id" json:"site_id"`
	PolicyID             pgtype.UUID               `db:"policy_id" json:"policy_id"`
	EquipmentID          pgtype.UUID               `db:"equipment_id" json:"equipment_id"`
	Type                 TicketsTicketType         `db:"type" json:"type"`
	Priority             NullTicketsTicketPriority `db:"priority" json:"priority"`
	Status               NullTicketsTicketStatus   `db:"status" json:"status"`
	Title                string                    `db:"title" json:"title"`
	Description          *string                   `db:"description" json:"description"`
	ReportedBy           pgtype.UUID               `db:"reported_by" json:"reported_by"`
	AssignedTo           pgtype.UUID               `db:"assigned_to" json:"assigned_to"`
	ScheduledDate        pgtype.Timestamptz        `db:"scheduled_date" json:"scheduled_date"`
	StartedAt            pgtype.Timestamptz        `db:"started_at" json:"started_at"`
	CompletedAt          pgtype.Timestamptz        `db:"completed_at" json:"completed_at"`
	SlaHours             *int32                    `db:"sla_hours" json:"sla_hours"`
	SlaDeadline          pgtype.Timestamptz        `db:"sla_deadline" json:"sla_deadline"`
	SlaMet               *bool                     `db:"sla_met" json:"sla_met"`
	Resolution           *string                   `db:"resolution" json:"resolution"`
	CustomerSignatureUrl *string                   `db:"customer_signature_url" json:"customer_signature_url"`
	Rating               *int32                    `db:"rating" json:"rating"`
	RatingComment        *string                   `db:"rating_comment" json:"rating_comment"`
	Metadata             []byte                    `db:"metadata" json:"metadata"`
	CreatedAt            pgtype.Timestamptz        `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz        `db:"updated_at" json:"updated_at"`
}

type TicketsTicketAssignment struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	TenantID     pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TicketID     pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	TechnicianID pgtype.UUID        `db:"technician_id" json:"technician_id"`
	AssignedBy   pgtype.UUID        `db:"assigned_by" json:"assigned_by"`
	AssignedAt   pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	AcceptedAt   pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	IsActive     *bool              `db:"is_active" json:"is_active"`
	Notes        *string            `db:"notes" json:"notes"`
}

type TicketsTicketComment struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TicketID   pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Comment    string             `db:"comment" json:"comment"`
	IsInternal *bool              `db:"is_internal" json:"is_internal"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TicketsTicketEvidence struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	TenantID     pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TicketID     pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	FileUrl      string             `db:"file_url" json:"file_url"`
	FileName     *string            `db:"file_name" json:"file_name"`
	FileType     *string            `db:"file_type" json:"file_type"`
	FileSize     *int32             `db:"file_size" json:"file_size"`
	Description  *string            `db:"description" json:"description"`
	EvidenceType *string            `db:"evidence_type" json:"evidence_type"`
	UploadedBy   pgtype.UUID        `db:"uploaded_by" json:"uploaded_by"`
	Latitude     pgtype.Numeric     `db:"latitude" json:"latitude"`
	Longitude    pgtype.Numeric     `db:"longitude" json:"longitude"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TicketsTicketPolicyLink struct {
	ID             pgtype.UUID           `db:"id" json:"id"`
	TenantID       pgtype.UUID           `db:"tenant_id" json:"tenant_id"`
	TicketID       pgtype.UUID           `db:"ticket_id" json:"ticket_id"`
	PolicyID       pgtype.UUID           `db:"policy_id" json:"policy_id"`
	CoverageStatus TicketsCoverageStatus `db:"coverage_status" json:"coverage_status"`
	Notes          *string               `db:"notes" json:"notes"`
	CreatedAt      pgtype.Timestamptz    `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz    `db:"updated_at" json:"updated_at"`
}

type TicketsTicketSlaInstance struct {
	ID                  pgtype.UUID               `db:"id" json:"id"`
	TenantID            pgtype.UUID               `db:"tenant_id" json:"tenant_id"`
	TicketID            pgtype.UUID               `db:"ticket_id" json:"ticket_id"`
	SlaPolicyID         pgtype.UUID               `db:"sla_policy_id" json:"sla_policy_id"`
	PrioritySnapshot    NullTicketsTicketPriority `db:"priority_snapshot" json:"priority_snapshot"`
	TypeSnapshot        NullTicketsTicketType     `db:"type_snapshot" json:"type_snapshot"`
	ResponseTimeHours   *int32                    `db:"response_time_hours" json:"response_time_hours"`
	ResolutionTimeHours *int32                    `db:"resolution_time_hours" json:"resolution_time_hours"`
	DueResponseAt       pgtype.Timestamptz        `db:"due_response_at" json:"due_response_at"`
	DueResolutionAt     pgtype.Timestamptz        `db:"due_resolution_at" json:"due_resolution_at"`
	RespondedAt         pgtype.Timestamptz        `db:"responded_at" json:"responded_at"`
	ResolvedAt          pgtype.Timestamptz        `db:"resolved_at" json:"resolved_at"`
	BreachedResponse    bool                      `db:"breached_response" json:"breached_response"`
	BreachedResolution  bool                      `db:"breached_resolution" json:"breached_resolution"`
	Status              TicketsSlaStatus          `db:"status" json:"status"`
	CreatedAt           pgtype.Timestamptz        `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz        `db:"updated_at" json:"updated_at"`
}

type TicketsTicketTimeline struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TicketID    pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	EventType   string             `db:"event_type" json:"event_type"`
	Description *string            `db:"description" json:"description"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	OldValue    *string            `db:"old_value" json:"old_value"`
	NewValue    *string            `db:"new_value" json:"new_value"`
	Metadata    []byte             `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Registro de trabajo realizado en tickets
type TicketsWorklog struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	TenantID          pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TicketID          pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	TechnicianID      pgtype.UUID        `db:"technician_id" json:"technician_id"`
	StartTime         pgtype.Timestamptz `db:"start_time" json:"start_time"`
	EndTime           pgtype.Timestamptz `db:"end_time" json:"end_time"`
	DurationMinutes   *int32             `db:"duration_minutes" json:"duration_minutes"`
	WorkDescription   string             `db:"work_description" json:"work_description"`
	TravelTimeMinutes *int32             `db:"travel_time_minutes" json:"travel_time_minutes"`
	TravelDistanceKm  pgtype.Numeric     `db:"travel_distance_km" json:"travel_distance_km"`
	PartsUsed         []byte             `db:"parts_used" json:"parts_used"`
	LaborType         *string            `db:"labor_type" json:"labor_type"`
	IsBillable        *bool              `db:"is_billable" json:"is_billable"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
