// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPolicyAssetCamera = `-- name: AddPolicyAssetCamera :one
INSERT INTO policies.policy_assets (
    tenant_id,
    policy_id,
    camera_id,
    notes
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (policy_id, camera_id) WHERE camera_id IS NOT NULL
DO UPDATE SET
    notes = EXCLUDED.notes,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, tenant_id, policy_id, equipment_id, nvr_server_id, camera_id, notes, created_at, updated_at
`

func (q *Queries) AddPolicyAssetCamera(ctx context.Context, tenantID pgtype.UUID, policyID pgtype.UUID, cameraID pgtype.UUID, notes *string) (PoliciesPolicyAsset, error) {
	row := q.db.QueryRow(ctx, addPolicyAssetCamera,
		tenantID,
		policyID,
		cameraID,
		notes,
	)
	var i PoliciesPolicyAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyID,
		&i.EquipmentID,
		&i.NvrServerID,
		&i.CameraID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addPolicyAssetEquipment = `-- name: AddPolicyAssetEquipment :one
INSERT INTO policies.policy_assets (
    tenant_id,
    policy_id,
    equipment_id,
    notes
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (policy_id, equipment_id) WHERE equipment_id IS NOT NULL
DO UPDATE SET
    notes = EXCLUDED.notes,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, tenant_id, policy_id, equipment_id, nvr_server_id, camera_id, notes, created_at, updated_at
`

func (q *Queries) AddPolicyAssetEquipment(ctx context.Context, tenantID pgtype.UUID, policyID pgtype.UUID, equipmentID pgtype.UUID, notes *string) (PoliciesPolicyAsset, error) {
	row := q.db.QueryRow(ctx, addPolicyAssetEquipment,
		tenantID,
		policyID,
		equipmentID,
		notes,
	)
	var i PoliciesPolicyAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyID,
		&i.EquipmentID,
		&i.NvrServerID,
		&i.CameraID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addPolicyAssetNvr = `-- name: AddPolicyAssetNvr :one
INSERT INTO policies.policy_assets (
    tenant_id,
    policy_id,
    nvr_server_id,
    notes
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (policy_id, nvr_server_id) WHERE nvr_server_id IS NOT NULL
DO UPDATE SET
    notes = EXCLUDED.notes,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, tenant_id, policy_id, equipment_id, nvr_server_id, camera_id, notes, created_at, updated_at
`

func (q *Queries) AddPolicyAssetNvr(ctx context.Context, tenantID pgtype.UUID, policyID pgtype.UUID, nvrServerID pgtype.UUID, notes *string) (PoliciesPolicyAsset, error) {
	row := q.db.QueryRow(ctx, addPolicyAssetNvr,
		tenantID,
		policyID,
		nvrServerID,
		notes,
	)
	var i PoliciesPolicyAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyID,
		&i.EquipmentID,
		&i.NvrServerID,
		&i.CameraID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies.policies (
    tenant_id,
    policy_number,
    client_id,
    site_id,
    coverage_plan_id,
    status,
    start_date,
    end_date,
    monthly_payment,
    payment_day,
    notes,
    terms_accepted,
    contract_url,
    vendor,
    contract_type,
    annual_value,
    coverage_json,
    metadata,
    created_by
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
RETURNING id, tenant_id, policy_number, client_id, site_id, coverage_plan_id, status, start_date, end_date, monthly_payment, payment_day, notes, terms_accepted, contract_url, created_by, created_at, updated_at, vendor, contract_type, annual_value, coverage_json, metadata
`

type CreatePolicyParams struct {
	TenantID       pgtype.UUID              `db:"tenant_id" json:"tenant_id"`
	PolicyNumber   string                   `db:"policy_number" json:"policy_number"`
	ClientID       pgtype.UUID              `db:"client_id" json:"client_id"`
	SiteID         pgtype.UUID              `db:"site_id" json:"site_id"`
	CoveragePlanID pgtype.UUID              `db:"coverage_plan_id" json:"coverage_plan_id"`
	Status         NullPoliciesPolicyStatus `db:"status" json:"status"`
	StartDate      pgtype.Date              `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date              `db:"end_date" json:"end_date"`
	MonthlyPayment pgtype.Numeric           `db:"monthly_payment" json:"monthly_payment"`
	PaymentDay     *int32                   `db:"payment_day" json:"payment_day"`
	Notes          *string                  `db:"notes" json:"notes"`
	TermsAccepted  *bool                    `db:"terms_accepted" json:"terms_accepted"`
	ContractUrl    *string                  `db:"contract_url" json:"contract_url"`
	Vendor         *string                  `db:"vendor" json:"vendor"`
	ContractType   *string                  `db:"contract_type" json:"contract_type"`
	AnnualValue    pgtype.Numeric           `db:"annual_value" json:"annual_value"`
	CoverageJson   []byte                   `db:"coverage_json" json:"coverage_json"`
	Metadata       []byte                   `db:"metadata" json:"metadata"`
	CreatedBy      pgtype.UUID              `db:"created_by" json:"created_by"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (PoliciesPolicy, error) {
	row := q.db.QueryRow(ctx, createPolicy,
		arg.TenantID,
		arg.PolicyNumber,
		arg.ClientID,
		arg.SiteID,
		arg.CoveragePlanID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.MonthlyPayment,
		arg.PaymentDay,
		arg.Notes,
		arg.TermsAccepted,
		arg.ContractUrl,
		arg.Vendor,
		arg.ContractType,
		arg.AnnualValue,
		arg.CoverageJson,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i PoliciesPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyNumber,
		&i.ClientID,
		&i.SiteID,
		&i.CoveragePlanID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.MonthlyPayment,
		&i.PaymentDay,
		&i.Notes,
		&i.TermsAccepted,
		&i.ContractUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Vendor,
		&i.ContractType,
		&i.AnnualValue,
		&i.CoverageJson,
		&i.Metadata,
	)
	return i, err
}

const getActivePolicyForClientSite = `-- name: GetActivePolicyForClientSite :one
SELECT p.id, p.tenant_id, p.policy_number, p.client_id, p.site_id, p.coverage_plan_id, p.status, p.start_date, p.end_date, p.monthly_payment, p.payment_day, p.notes, p.terms_accepted, p.contract_url, p.created_by, p.created_at, p.updated_at, p.vendor, p.contract_type, p.annual_value, p.coverage_json, p.metadata,
    c.company_name AS client_name,
    s.name AS site_name
FROM policies.policies p
INNER JOIN policies.clients c ON c.id = p.client_id
LEFT JOIN policies.sites s ON s.id = p.site_id
WHERE p.tenant_id = $1
    AND p.client_id = $2
    AND ($3::uuid IS NULL OR p.site_id = $3 OR p.site_id IS NULL)
    AND p.status = 'active'
    AND CURRENT_DATE BETWEEN p.start_date AND p.end_date
ORDER BY
    CASE WHEN p.site_id = $3 THEN 0 ELSE 1 END,
    p.created_at DESC
LIMIT 1
`

type GetActivePolicyForClientSiteRow struct {
	ID             pgtype.UUID              `db:"id" json:"id"`
	TenantID       pgtype.UUID              `db:"tenant_id" json:"tenant_id"`
	PolicyNumber   string                   `db:"policy_number" json:"policy_number"`
	ClientID       pgtype.UUID              `db:"client_id" json:"client_id"`
	SiteID         pgtype.UUID              `db:"site_id" json:"site_id"`
	CoveragePlanID pgtype.UUID              `db:"coverage_plan_id" json:"coverage_plan_id"`
	Status         NullPoliciesPolicyStatus `db:"status" json:"status"`
	StartDate      pgtype.Date              `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date              `db:"end_date" json:"end_date"`
	MonthlyPayment pgtype.Numeric           `db:"monthly_payment" json:"monthly_payment"`
	PaymentDay     *int32                   `db:"payment_day" json:"payment_day"`
	Notes          *string                  `db:"notes" json:"notes"`
	TermsAccepted  *bool                    `db:"terms_accepted" json:"terms_accepted"`
	ContractUrl    *string                  `db:"contract_url" json:"contract_url"`
	CreatedBy      pgtype.UUID              `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	Vendor         *string                  `db:"vendor" json:"vendor"`
	ContractType   *string                  `db:"contract_type" json:"contract_type"`
	AnnualValue    pgtype.Numeric           `db:"annual_value" json:"annual_value"`
	CoverageJson   []byte                   `db:"coverage_json" json:"coverage_json"`
	Metadata       []byte                   `db:"metadata" json:"metadata"`
	ClientName     string                   `db:"client_name" json:"client_name"`
	SiteName       *string                  `db:"site_name" json:"site_name"`
}

func (q *Queries) GetActivePolicyForClientSite(ctx context.Context, tenantID pgtype.UUID, clientID pgtype.UUID, column3 pgtype.UUID) (GetActivePolicyForClientSiteRow, error) {
	row := q.db.QueryRow(ctx, getActivePolicyForClientSite, tenantID, clientID, column3)
	var i GetActivePolicyForClientSiteRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyNumber,
		&i.ClientID,
		&i.SiteID,
		&i.CoveragePlanID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.MonthlyPayment,
		&i.PaymentDay,
		&i.Notes,
		&i.TermsAccepted,
		&i.ContractUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Vendor,
		&i.ContractType,
		&i.AnnualValue,
		&i.CoverageJson,
		&i.Metadata,
		&i.ClientName,
		&i.SiteName,
	)
	return i, err
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT p.id, p.tenant_id, p.policy_number, p.client_id, p.site_id, p.coverage_plan_id, p.status, p.start_date, p.end_date, p.monthly_payment, p.payment_day, p.notes, p.terms_accepted, p.contract_url, p.created_by, p.created_at, p.updated_at, p.vendor, p.contract_type, p.annual_value, p.coverage_json, p.metadata,
    c.company_name AS client_name,
    s.name AS site_name
FROM policies.policies p
INNER JOIN policies.clients c ON c.id = p.client_id
LEFT JOIN policies.sites s ON s.id = p.site_id
WHERE p.id = $1
    AND p.tenant_id = $2
LIMIT 1
`

type GetPolicyByIDRow struct {
	ID             pgtype.UUID              `db:"id" json:"id"`
	TenantID       pgtype.UUID              `db:"tenant_id" json:"tenant_id"`
	PolicyNumber   string                   `db:"policy_number" json:"policy_number"`
	ClientID       pgtype.UUID              `db:"client_id" json:"client_id"`
	SiteID         pgtype.UUID              `db:"site_id" json:"site_id"`
	CoveragePlanID pgtype.UUID              `db:"coverage_plan_id" json:"coverage_plan_id"`
	Status         NullPoliciesPolicyStatus `db:"status" json:"status"`
	StartDate      pgtype.Date              `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date              `db:"end_date" json:"end_date"`
	MonthlyPayment pgtype.Numeric           `db:"monthly_payment" json:"monthly_payment"`
	PaymentDay     *int32                   `db:"payment_day" json:"payment_day"`
	Notes          *string                  `db:"notes" json:"notes"`
	TermsAccepted  *bool                    `db:"terms_accepted" json:"terms_accepted"`
	ContractUrl    *string                  `db:"contract_url" json:"contract_url"`
	CreatedBy      pgtype.UUID              `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	Vendor         *string                  `db:"vendor" json:"vendor"`
	ContractType   *string                  `db:"contract_type" json:"contract_type"`
	AnnualValue    pgtype.Numeric           `db:"annual_value" json:"annual_value"`
	CoverageJson   []byte                   `db:"coverage_json" json:"coverage_json"`
	Metadata       []byte                   `db:"metadata" json:"metadata"`
	ClientName     string                   `db:"client_name" json:"client_name"`
	SiteName       *string                  `db:"site_name" json:"site_name"`
}

func (q *Queries) GetPolicyByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetPolicyByIDRow, error) {
	row := q.db.QueryRow(ctx, getPolicyByID, iD, tenantID)
	var i GetPolicyByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyNumber,
		&i.ClientID,
		&i.SiteID,
		&i.CoveragePlanID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.MonthlyPayment,
		&i.PaymentDay,
		&i.Notes,
		&i.TermsAccepted,
		&i.ContractUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Vendor,
		&i.ContractType,
		&i.AnnualValue,
		&i.CoverageJson,
		&i.Metadata,
		&i.ClientName,
		&i.SiteName,
	)
	return i, err
}

const listPoliciesByTenant = `-- name: ListPoliciesByTenant :many

SELECT p.id, p.tenant_id, p.policy_number, p.client_id, p.site_id, p.coverage_plan_id, p.status, p.start_date, p.end_date, p.monthly_payment, p.payment_day, p.notes, p.terms_accepted, p.contract_url, p.created_by, p.created_at, p.updated_at, p.vendor, p.contract_type, p.annual_value, p.coverage_json, p.metadata,
    c.company_name AS client_name,
    s.name AS site_name
FROM policies.policies p
INNER JOIN policies.clients c ON c.id = p.client_id
LEFT JOIN policies.sites s ON s.id = p.site_id
WHERE p.tenant_id = $1
    AND ($2 = '' OR p.status::text = $2)
    AND ($3 = '' OR p.vendor ILIKE '%' || $3 || '%')
    AND ($4 = '' OR p.client_id::text = $4)
ORDER BY p.created_at DESC
LIMIT $5 OFFSET $6
`

type ListPoliciesByTenantRow struct {
	ID             pgtype.UUID              `db:"id" json:"id"`
	TenantID       pgtype.UUID              `db:"tenant_id" json:"tenant_id"`
	PolicyNumber   string                   `db:"policy_number" json:"policy_number"`
	ClientID       pgtype.UUID              `db:"client_id" json:"client_id"`
	SiteID         pgtype.UUID              `db:"site_id" json:"site_id"`
	CoveragePlanID pgtype.UUID              `db:"coverage_plan_id" json:"coverage_plan_id"`
	Status         NullPoliciesPolicyStatus `db:"status" json:"status"`
	StartDate      pgtype.Date              `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date              `db:"end_date" json:"end_date"`
	MonthlyPayment pgtype.Numeric           `db:"monthly_payment" json:"monthly_payment"`
	PaymentDay     *int32                   `db:"payment_day" json:"payment_day"`
	Notes          *string                  `db:"notes" json:"notes"`
	TermsAccepted  *bool                    `db:"terms_accepted" json:"terms_accepted"`
	ContractUrl    *string                  `db:"contract_url" json:"contract_url"`
	CreatedBy      pgtype.UUID              `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz       `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz       `db:"updated_at" json:"updated_at"`
	Vendor         *string                  `db:"vendor" json:"vendor"`
	ContractType   *string                  `db:"contract_type" json:"contract_type"`
	AnnualValue    pgtype.Numeric           `db:"annual_value" json:"annual_value"`
	CoverageJson   []byte                   `db:"coverage_json" json:"coverage_json"`
	Metadata       []byte                   `db:"metadata" json:"metadata"`
	ClientName     string                   `db:"client_name" json:"client_name"`
	SiteName       *string                  `db:"site_name" json:"site_name"`
}

// internal/database/queries/policies.sql
// Queries para módulo de pólizas y relación con activos
func (q *Queries) ListPoliciesByTenant(ctx context.Context, tenantID pgtype.UUID, column2 interface{}, column3 interface{}, column4 interface{}, limit int32, offset int32) ([]ListPoliciesByTenantRow, error) {
	rows, err := q.db.Query(ctx, listPoliciesByTenant,
		tenantID,
		column2,
		column3,
		column4,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPoliciesByTenantRow{}
	for rows.Next() {
		var i ListPoliciesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyNumber,
			&i.ClientID,
			&i.SiteID,
			&i.CoveragePlanID,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.MonthlyPayment,
			&i.PaymentDay,
			&i.Notes,
			&i.TermsAccepted,
			&i.ContractUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Vendor,
			&i.ContractType,
			&i.AnnualValue,
			&i.CoverageJson,
			&i.Metadata,
			&i.ClientName,
			&i.SiteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyAssets = `-- name: ListPolicyAssets :many
SELECT pa.id, pa.tenant_id, pa.policy_id, pa.equipment_id, pa.nvr_server_id, pa.camera_id, pa.notes, pa.created_at, pa.updated_at,
    e.serial_number AS equipment_serial,
    n.name AS nvr_name,
    cam.name AS camera_name
FROM policies.policy_assets pa
LEFT JOIN inventory.equipment e ON e.id = pa.equipment_id
LEFT JOIN inventory.nvr_servers n ON n.id = pa.nvr_server_id
LEFT JOIN inventory.cameras cam ON cam.id = pa.camera_id
WHERE pa.policy_id = $1
    AND pa.tenant_id = $2
ORDER BY pa.created_at DESC
`

type ListPolicyAssetsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	TenantID        pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	PolicyID        pgtype.UUID        `db:"policy_id" json:"policy_id"`
	EquipmentID     pgtype.UUID        `db:"equipment_id" json:"equipment_id"`
	NvrServerID     pgtype.UUID        `db:"nvr_server_id" json:"nvr_server_id"`
	CameraID        pgtype.UUID        `db:"camera_id" json:"camera_id"`
	Notes           *string            `db:"notes" json:"notes"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EquipmentSerial *string            `db:"equipment_serial" json:"equipment_serial"`
	NvrName         *string            `db:"nvr_name" json:"nvr_name"`
	CameraName      *string            `db:"camera_name" json:"camera_name"`
}

func (q *Queries) ListPolicyAssets(ctx context.Context, policyID pgtype.UUID, tenantID pgtype.UUID) ([]ListPolicyAssetsRow, error) {
	rows, err := q.db.Query(ctx, listPolicyAssets, policyID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPolicyAssetsRow{}
	for rows.Next() {
		var i ListPolicyAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyID,
			&i.EquipmentID,
			&i.NvrServerID,
			&i.CameraID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EquipmentSerial,
			&i.NvrName,
			&i.CameraName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePolicyAsset = `-- name: RemovePolicyAsset :exec
DELETE FROM policies.policy_assets
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) RemovePolicyAsset(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removePolicyAsset, iD, tenantID)
	return err
}

const softDeletePolicy = `-- name: SoftDeletePolicy :exec
UPDATE policies.policies
SET status = 'cancelled',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) SoftDeletePolicy(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePolicy, iD, tenantID)
	return err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies.policies
SET policy_number = COALESCE($3, policy_number),
    client_id = COALESCE($4, client_id),
    site_id = COALESCE($5, site_id),
    coverage_plan_id = COALESCE($6, coverage_plan_id),
    status = COALESCE($7, status),
    start_date = COALESCE($8, start_date),
    end_date = COALESCE($9, end_date),
    monthly_payment = COALESCE($10, monthly_payment),
    payment_day = COALESCE($11, payment_day),
    notes = COALESCE($12, notes),
    terms_accepted = COALESCE($13, terms_accepted),
    contract_url = COALESCE($14, contract_url),
    vendor = COALESCE($15, vendor),
    contract_type = COALESCE($16, contract_type),
    annual_value = COALESCE($17, annual_value),
    coverage_json = COALESCE($18, coverage_json),
    metadata = COALESCE($19, metadata),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
RETURNING id, tenant_id, policy_number, client_id, site_id, coverage_plan_id, status, start_date, end_date, monthly_payment, payment_day, notes, terms_accepted, contract_url, created_by, created_at, updated_at, vendor, contract_type, annual_value, coverage_json, metadata
`

type UpdatePolicyParams struct {
	ID             pgtype.UUID              `db:"id" json:"id"`
	TenantID       pgtype.UUID              `db:"tenant_id" json:"tenant_id"`
	PolicyNumber   string                   `db:"policy_number" json:"policy_number"`
	ClientID       pgtype.UUID              `db:"client_id" json:"client_id"`
	SiteID         pgtype.UUID              `db:"site_id" json:"site_id"`
	CoveragePlanID pgtype.UUID              `db:"coverage_plan_id" json:"coverage_plan_id"`
	Status         NullPoliciesPolicyStatus `db:"status" json:"status"`
	StartDate      pgtype.Date              `db:"start_date" json:"start_date"`
	EndDate        pgtype.Date              `db:"end_date" json:"end_date"`
	MonthlyPayment pgtype.Numeric           `db:"monthly_payment" json:"monthly_payment"`
	PaymentDay     *int32                   `db:"payment_day" json:"payment_day"`
	Notes          *string                  `db:"notes" json:"notes"`
	TermsAccepted  *bool                    `db:"terms_accepted" json:"terms_accepted"`
	ContractUrl    *string                  `db:"contract_url" json:"contract_url"`
	Vendor         *string                  `db:"vendor" json:"vendor"`
	ContractType   *string                  `db:"contract_type" json:"contract_type"`
	AnnualValue    pgtype.Numeric           `db:"annual_value" json:"annual_value"`
	CoverageJson   []byte                   `db:"coverage_json" json:"coverage_json"`
	Metadata       []byte                   `db:"metadata" json:"metadata"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (PoliciesPolicy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.ID,
		arg.TenantID,
		arg.PolicyNumber,
		arg.ClientID,
		arg.SiteID,
		arg.CoveragePlanID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.MonthlyPayment,
		arg.PaymentDay,
		arg.Notes,
		arg.TermsAccepted,
		arg.ContractUrl,
		arg.Vendor,
		arg.ContractType,
		arg.AnnualValue,
		arg.CoverageJson,
		arg.Metadata,
	)
	var i PoliciesPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyNumber,
		&i.ClientID,
		&i.SiteID,
		&i.CoveragePlanID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.MonthlyPayment,
		&i.PaymentDay,
		&i.Notes,
		&i.TermsAccepted,
		&i.ContractUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Vendor,
		&i.ContractType,
		&i.AnnualValue,
		&i.CoverageJson,
		&i.Metadata,
	)
	return i, err
}
