// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	AddPolicyAssetCamera(ctx context.Context, tenantID pgtype.UUID, policyID pgtype.UUID, cameraID pgtype.UUID, notes *string) (PoliciesPolicyAsset, error)
	AddPolicyAssetEquipment(ctx context.Context, tenantID pgtype.UUID, policyID pgtype.UUID, equipmentID pgtype.UUID, notes *string) (PoliciesPolicyAsset, error)
	AddPolicyAssetNvr(ctx context.Context, tenantID pgtype.UUID, policyID pgtype.UUID, nvrServerID pgtype.UUID, notes *string) (PoliciesPolicyAsset, error)
	// Asigna un item a un template (o actualiza si ya existe)
	AssignItemToTemplate(ctx context.Context, templateID pgtype.UUID, menuItemID pgtype.UUID, displayOrder *int32, isVisible *bool) (AuthMenuTemplateItem, error)
	AssignMenuTemplateToTenant(ctx context.Context, tenantID pgtype.UUID, templateID pgtype.UUID) error
	AssignPermissionToRole(ctx context.Context, roleID pgtype.UUID, permissionID pgtype.UUID) error
	AssignRoleToUser(ctx context.Context, userID pgtype.UUID, roleID pgtype.UUID) error
	AssignTicket(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, assignedTo pgtype.UUID) error
	// Asigna múltiples items a un template
	BulkAssignItemsToTemplate(ctx context.Context, column1 pgtype.UUID, column2 []pgtype.UUID) error
	BulkUpdateCamerasNvr(ctx context.Context, tenantID pgtype.UUID, column2 []pgtype.UUID, nvrServerID pgtype.UUID, updatedBy pgtype.UUID) error
	BulkUpdateImportBatchItemsStatus(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID, status *string, column4 []pgtype.UUID) error
	CancelTicket(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, resolution *string) error
	// =============================================
	// HELPER QUERIES FOR IMPORT VALIDATION
	// =============================================
	CheckCameraCodeExists(ctx context.Context, tenantID pgtype.UUID, code *string) (bool, error)
	CheckCameraIPExists(ctx context.Context, tenantID pgtype.UUID, ipAddress *netip.Addr) (bool, error)
	CheckNvrCodeExists(ctx context.Context, tenantID pgtype.UUID, code *string) (bool, error)
	CheckNvrIPExists(ctx context.Context, tenantID pgtype.UUID, ipAddress *netip.Addr) (bool, error)
	// Status transitions
	CloseTicket(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	CompleteTicket(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, resolution *string, slaMet *bool) error
	CountActiveTenants(ctx context.Context) (int64, error)
	CountFileAccess(ctx context.Context, fileID pgtype.UUID, accessType string) (int64, error)
	CountFilesByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountImportBatchItemsByStatus(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID) (CountImportBatchItemsByStatusRow, error)
	CountMenuItems(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CountTickets(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountTicketsByStatus(ctx context.Context, tenantID pgtype.UUID, status NullTicketsTicketStatus) (int64, error)
	// ==================== API CALLS ====================
	CreateAPICall(ctx context.Context, arg CreateAPICallParams) (IntelligenceApiCall, error)
	// ==================== ANALYSES ====================
	CreateAnalysis(ctx context.Context, tenantID pgtype.UUID, analysisType string, inputType string, inputReference pgtype.UUID, inputData []byte, result []byte, confidenceScore pgtype.Numeric, apiCallID pgtype.UUID, modelUsed *string, processingTimeMs *int32) (IntelligenceAnalysis, error)
	// internal/database/queries/inventory_cameras.sql
	// Queries SQLC para cámaras
	// =============================================
	// CAMERAS
	// =============================================
	CreateCamera(ctx context.Context, arg CreateCameraParams) (InventoryCamera, error)
	// internal/database/queries/clients.sql
	// Queries para clientes y sitios
	CreateClient(ctx context.Context, tenantID pgtype.UUID, companyName string, legalName *string, rfc *string, address *string, city *string, state *string, postalCode *string, email *string, phone *string) (PoliciesClient, error)
	// Client Contacts
	CreateClientContact(ctx context.Context, tenantID pgtype.UUID, clientID pgtype.UUID, name string, position *string, email *string, phone *string, isPrimary *bool) (PoliciesClientContact, error)
	// Equipment
	CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (InventoryEquipment, error)
	// internal/database/queries/storage.sql
	// Queries para gestión de archivos y multimedia
	// ==================== FILES ====================
	CreateFile(ctx context.Context, arg CreateFileParams) (StorageFile, error)
	// ==================== FILE ACCESS LOG ====================
	CreateFileAccessLog(ctx context.Context, tenantID pgtype.UUID, fileID pgtype.UUID, accessType string, accessedBy pgtype.UUID, ipAddress *netip.Addr, userAgent *string) (StorageFileAccessLog, error)
	// ==================== FILE PROCESSING ====================
	CreateFileProcessing(ctx context.Context, tenantID pgtype.UUID, fileID pgtype.UUID, processingType string, status *string) (StorageFileProcessing, error)
	// internal/database/queries/inventory_import.sql
	// Queries SQLC para importación masiva de inventario
	// =============================================
	// IMPORT BATCHES
	// =============================================
	CreateImportBatch(ctx context.Context, tenantID pgtype.UUID, batchName string, sourceType InventoryImportSourceType, sourceFilename *string, targetTable string, columnMapping []byte, totalRows *int32, sourceFileID pgtype.UUID, createdBy pgtype.UUID) (InventoryImportBatch, error)
	// =============================================
	// IMPORT BATCH ITEMS
	// =============================================
	CreateImportBatchItem(ctx context.Context, tenantID pgtype.UUID, batchID pgtype.UUID, rowNumber int32, rawData []byte, status *string) (InventoryImportBatchItem, error)
	CreateImportBatchItemsBulk(ctx context.Context, arg []CreateImportBatchItemsBulkParams) (int64, error)
	// Maintenance History
	CreateMaintenanceHistory(ctx context.Context, tenantID pgtype.UUID, equipmentID pgtype.UUID, ticketID pgtype.UUID, serviceDate pgtype.Date, serviceType string, performedBy pgtype.UUID, description *string, findings *string, laborHours pgtype.Numeric, nextServiceDate pgtype.Date) (InventoryMaintenanceHistory, error)
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (AuthMenuItem, error)
	CreateMenuTemplate(ctx context.Context, name string, description *string, isDefault *bool) (AuthMenuTemplate, error)
	// internal/database/queries/intelligence.sql
	// Queries para sistema de inteligencia artificial
	// ==================== MODEL CONFIGS ====================
	CreateModelConfig(ctx context.Context, arg CreateModelConfigParams) (IntelligenceModelConfig, error)
	CreateModuleStorageMapping(ctx context.Context, tenantID pgtype.UUID, moduleName string, collectionName string, configID pgtype.UUID, isActive *bool, maxFileSizeMb *int32, allowedFileTypes []string, autoResize *bool, thumbnailSizes []int32) (StorageModuleStorageMapping, error)
	// =============================================
	// NVR LICENSES
	// =============================================
	CreateNvrLicense(ctx context.Context, arg CreateNvrLicenseParams) (InventoryNvrLicense, error)
	// internal/database/queries/inventory_nvr.sql
	// Queries SQLC para servidores NVR y licencias
	// =============================================
	// NVR SERVERS
	// =============================================
	CreateNvrServer(ctx context.Context, arg CreateNvrServerParams) (InventoryNvrServer, error)
	// =============================================
	// NVR STORAGE UNITS
	// =============================================
	CreateNvrStorageUnit(ctx context.Context, arg CreateNvrStorageUnitParams) (InventoryNvrStorageUnit, error)
	CreatePermission(ctx context.Context, code string, description *string, module *string, scope *string) (AuthPermission, error)
	CreatePolicy(ctx context.Context, arg CreatePolicyParams) (PoliciesPolicy, error)
	// ==================== PROMPT TEMPLATES ====================
	CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (IntelligencePromptTemplate, error)
	// Roles
	CreateRole(ctx context.Context, tenantID pgtype.UUID, name string, description *string) (AuthRole, error)
	// Sessions
	CreateSession(ctx context.Context, userID pgtype.UUID, tenantID pgtype.UUID, tokenHash string, deviceInfo []byte, ipAddress *netip.Addr, expiresAt pgtype.Timestamptz) (AuthSession, error)
	// Sites
	CreateSite(ctx context.Context, arg CreateSiteParams) (PoliciesSite, error)
	CreateSlaPolicy(ctx context.Context, tenantID pgtype.UUID, name string, ticketPriority NullTicketsTicketPriority, ticketType NullTicketsTicketType, responseTimeHours int32, resolutionTimeHours int32, isDefault bool, isActive bool, businessHours []byte, createdBy pgtype.UUID) (TicketsSlaPolicy, error)
	CreateStorageConfiguration(ctx context.Context, arg CreateStorageConfigurationParams) (StorageStorageConfiguration, error)
	CreateSystemRole(ctx context.Context, name string, description *string) (AuthRole, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// internal/database/queries/tickets.sql
	// Queries para tickets y worklogs
	CreateTicket(ctx context.Context, arg CreateTicketParams) (TicketsTicket, error)
	// Comments
	CreateTicketComment(ctx context.Context, tenantID pgtype.UUID, ticketID pgtype.UUID, userID pgtype.UUID, comment string, isInternal *bool) (TicketsTicketComment, error)
	// Evidences
	CreateTicketEvidence(ctx context.Context, tenantID pgtype.UUID, ticketID pgtype.UUID, fileUrl string, fileName *string, fileType *string, fileSize *int32, description *string, uploadedBy pgtype.UUID) (TicketsTicketEvidence, error)
	CreateTicketSlaInstance(ctx context.Context, tenantID pgtype.UUID, ticketID pgtype.UUID, slaPolicyID pgtype.UUID, prioritySnapshot NullTicketsTicketPriority, typeSnapshot NullTicketsTicketType, responseTimeHours *int32, resolutionTimeHours *int32, dueResponseAt pgtype.Timestamptz, dueResolutionAt pgtype.Timestamptz, status TicketsSlaStatus) (TicketsTicketSlaInstance, error)
	// Timeline
	CreateTicketTimeline(ctx context.Context, tenantID pgtype.UUID, ticketID pgtype.UUID, eventType string, description *string, userID pgtype.UUID, oldValue *string, newValue *string, metadata []byte) (TicketsTicketTimeline, error)
	// ==================== USAGE SUMMARY ====================
	CreateUsageSummary(ctx context.Context, arg CreateUsageSummaryParams) (IntelligenceUsageSummary, error)
	// internal/database/queries/auth.sql
	// Queries para autenticación y usuarios
	CreateUser(ctx context.Context, tenantID pgtype.UUID, email string, passwordHash string, firstName string, lastName string, phone *string) (AuthUser, error)
	// Worklogs
	CreateWorklog(ctx context.Context, tenantID pgtype.UUID, ticketID pgtype.UUID, technicianID pgtype.UUID, startTime pgtype.Timestamptz, endTime pgtype.Timestamptz, durationMinutes *int32, workDescription string, travelTimeMinutes *int32, isBillable *bool) (TicketsWorklog, error)
	DeactivateClient(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeactivatePromptTemplate(ctx context.Context, id pgtype.UUID) (IntelligencePromptTemplate, error)
	DeactivateSlaPolicy(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeactivateTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	DeactivateUser(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeactivateUserGlobal(ctx context.Context, id pgtype.UUID) error
	DeleteCamera(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteFile(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeleteImportBatch(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeleteImportBatchItems(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID) error
	DeleteMenuItem(ctx context.Context, id pgtype.UUID) error
	DeleteModelConfig(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeleteNvrLicense(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeleteNvrServer(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeleteNvrStorageUnit(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeleteProcessing(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeletePromptTemplate(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteStorageConfiguration(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	DeleteTenant(ctx context.Context, id pgtype.UUID) error
	// Delete
	DeleteTicket(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	FindFileByHash(ctx context.Context, tenantID pgtype.UUID, fileHash *string) (StorageFile, error)
	GenerateTicketNumber(ctx context.Context, tenantID pgtype.UUID) (int32, error)
	GetAPICall(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (IntelligenceApiCall, error)
	GetActivePolicyForClientSite(ctx context.Context, tenantID pgtype.UUID, clientID pgtype.UUID, column3 pgtype.UUID) (GetActivePolicyForClientSiteRow, error)
	GetAnalysis(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (IntelligenceAnalysis, error)
	GetAnalysisAccuracyRate(ctx context.Context, tenantID pgtype.UUID) (GetAnalysisAccuracyRateRow, error)
	GetAreaByName(ctx context.Context, tenantID pgtype.UUID, name string) (GetAreaByNameRow, error)
	GetBrandByName(ctx context.Context, name string) (GetBrandByNameRow, error)
	GetCameraByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetCameraByIDRow, error)
	GetCameraStats(ctx context.Context, tenantID pgtype.UUID) (GetCameraStatsRow, error)
	GetCameraStatsByModel(ctx context.Context, tenantID pgtype.UUID) ([]GetCameraStatsByModelRow, error)
	GetCameraStatsByNvr(ctx context.Context, tenantID pgtype.UUID) ([]GetCameraStatsByNvrRow, error)
	GetCameraStatsByType(ctx context.Context, tenantID pgtype.UUID) ([]GetCameraStatsByTypeRow, error)
	GetCameraTypesSummary(ctx context.Context, tenantID pgtype.UUID) ([]GetCameraTypesSummaryRow, error)
	GetClientByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (PoliciesClient, error)
	// ==================== ESTADÍSTICAS DE CLIENTES ====================
	// Estadísticas de clientes
	GetClientStats(ctx context.Context, tenantID pgtype.UUID) (GetClientStatsRow, error)
	GetDashboardSlaMetrics(ctx context.Context, tenantID pgtype.UUID) (GetDashboardSlaMetricsRow, error)
	// ==================== RESUMEN EJECUTIVO (DASHBOARD PRINCIPAL) ====================
	// Resumen ejecutivo para el dashboard principal
	GetDashboardSummary(ctx context.Context, tenantID pgtype.UUID) (GetDashboardSummaryRow, error)
	// internal/database/queries/dashboard.sql
	// Queries para el dashboard principal y estadísticas
	// ==================== ESTADÍSTICAS DE TICKETS ====================
	// Obtiene estadísticas generales de tickets por tenant
	GetDashboardTicketStats(ctx context.Context, tenantID pgtype.UUID) (GetDashboardTicketStatsRow, error)
	// Usuarios por rol (para dashboard)
	GetDashboardUsersByRole(ctx context.Context, tenantID pgtype.UUID) ([]GetDashboardUsersByRoleRow, error)
	GetDefaultMenuTemplate(ctx context.Context) (AuthMenuTemplate, error)
	GetDefaultModelConfig(ctx context.Context, tenantID pgtype.UUID) (IntelligenceModelConfig, error)
	GetDefaultStorageConfig(ctx context.Context, tenantID pgtype.UUID, providerID int32) (StorageStorageConfiguration, error)
	GetEquipmentByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetEquipmentByIDRow, error)
	// =============================================
	// EXECUTIVE SUMMARY QUERIES
	// =============================================
	GetExecutiveSummary(ctx context.Context, tenantID pgtype.UUID) (GetExecutiveSummaryRow, error)
	GetFileByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (StorageFile, error)
	GetFileByIDGlobal(ctx context.Context, id pgtype.UUID) (StorageFile, error)
	GetFileProcessing(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (StorageFileProcessing, error)
	GetImportBatchByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetImportBatchByIDRow, error)
	GetImportBatchItemByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (InventoryImportBatchItem, error)
	GetImportBatchItemErrors(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID) ([]InventoryImportBatchItem, error)
	GetImportBatchStats(ctx context.Context, tenantID pgtype.UUID) (GetImportBatchStatsRow, error)
	// ==================== ESTADÍSTICAS DE INVENTARIO ====================
	// Estadísticas de inventario
	GetInventoryStats(ctx context.Context, tenantID pgtype.UUID) (GetInventoryStatsRow, error)
	// ==================== ESTADÍSTICAS DE FACTURACIÓN ====================
	// Estadísticas de facturación
	GetInvoiceStats(ctx context.Context, tenantID pgtype.UUID) (GetInvoiceStatsRow, error)
	GetLatestTemplateVersion(ctx context.Context, name string, tenantID pgtype.UUID) (IntelligencePromptTemplate, error)
	GetLicenseStats(ctx context.Context, tenantID pgtype.UUID) (GetLicenseStatsRow, error)
	GetMenuItem(ctx context.Context, id pgtype.UUID) (AuthMenuItem, error)
	GetMenuItemsByParent(ctx context.Context, parentID pgtype.UUID) ([]AuthMenuItem, error)
	// Usa la tabla N:N menu_template_items para obtener items de un template
	GetMenuItemsByTemplate(ctx context.Context, templateID pgtype.UUID) ([]AuthMenuItem, error)
	GetMenuTemplateForTenant(ctx context.Context, tenantID pgtype.UUID) (AuthMenuTemplate, error)
	GetModelByNameAndBrand(ctx context.Context, name string, name_2 string) (GetModelByNameAndBrandRow, error)
	GetModelConfig(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (IntelligenceModelConfig, error)
	GetModuleStorageMapping(ctx context.Context, tenantID pgtype.UUID, moduleName string) (GetModuleStorageMappingRow, error)
	GetMonthlyUsage(ctx context.Context, tenantID pgtype.UUID, periodStart pgtype.Date) (IntelligenceUsageSummary, error)
	GetNvrLicenseByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetNvrLicenseByIDRow, error)
	GetNvrServerByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetNvrServerByIDRow, error)
	GetNvrServerByName(ctx context.Context, tenantID pgtype.UUID, name string) (GetNvrServerByNameRow, error)
	GetNvrServerStats(ctx context.Context, tenantID pgtype.UUID) (GetNvrServerStatsRow, error)
	GetPermissionByCode(ctx context.Context, code string) (AuthPermission, error)
	GetPolicyByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetPolicyByIDRow, error)
	// ==================== ESTADÍSTICAS DE PÓLIZAS ====================
	// Estadísticas de pólizas
	GetPolicyStats(ctx context.Context, tenantID pgtype.UUID) (GetPolicyStatsRow, error)
	GetPromptTemplate(ctx context.Context, id pgtype.UUID) (IntelligencePromptTemplate, error)
	GetRoleByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (AuthRole, error)
	GetRolePermissions(ctx context.Context, roleID pgtype.UUID) ([]AuthPermission, error)
	GetSessionByToken(ctx context.Context, tokenHash string) (AuthSession, error)
	GetSiteByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (PoliciesSite, error)
	GetSiteByName(ctx context.Context, tenantID pgtype.UUID, name string) (GetSiteByNameRow, error)
	GetSlaPolicyByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (TicketsSlaPolicy, error)
	GetStorageConfigByName(ctx context.Context, tenantID pgtype.UUID, configName string) (StorageStorageConfiguration, error)
	GetStorageConfiguration(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (StorageStorageConfiguration, error)
	GetStorageProviderByName(ctx context.Context, providerName string) (StorageStorageProvider, error)
	GetStorageStatsByServer(ctx context.Context, nvrServerID pgtype.UUID, tenantID pgtype.UUID) (GetStorageStatsByServerRow, error)
	// Technician workload
	GetTechniciansWorkload(ctx context.Context, tenantID pgtype.UUID) ([]GetTechniciansWorkloadRow, error)
	// =====================================================
	// Menu Template Items (N:N relationship)
	// =====================================================
	// Obtiene la asignación de items a un template con info del item
	GetTemplateItemAssignments(ctx context.Context, templateID pgtype.UUID) ([]GetTemplateItemAssignmentsRow, error)
	// Obtiene todos los templates que tienen asignado un item específico
	GetTemplatesForMenuItem(ctx context.Context, menuItemID pgtype.UUID) ([]GetTemplatesForMenuItemRow, error)
	// internal/database/queries/tenants.sql
	// Queries para gestión CRUD de tenants
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTenantsForTemplate(ctx context.Context, templateID pgtype.UUID) ([]GetTenantsForTemplateRow, error)
	GetTicketByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetTicketByIDRow, error)
	GetTicketPolicyLinkByTicketID(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) (GetTicketPolicyLinkByTicketIDRow, error)
	GetTicketSlaInstanceByTicketID(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) (GetTicketSlaInstanceByTicketIDRow, error)
	GetTicketStats(ctx context.Context, tenantID pgtype.UUID) (GetTicketStatsRow, error)
	GetTicketWithFullDetails(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetTicketWithFullDetailsRow, error)
	GetTicketWithSlaAndPolicy(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetTicketWithSlaAndPolicyRow, error)
	// Tickets asignados por técnico
	GetTicketsByTechnician(ctx context.Context, tenantID pgtype.UUID) ([]GetTicketsByTechnicianRow, error)
	// Obtiene tendencia de tickets de los últimos N días
	GetTicketsTrend(ctx context.Context, tenantID pgtype.UUID, column2 int32) ([]GetTicketsTrendRow, error)
	GetTotalCost(ctx context.Context, tenantID pgtype.UUID) (interface{}, error)
	GetTotalStorageSize(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	GetTotalTokensUsed(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	// Obtiene items que NO están asignados a un template específico
	GetUnassignedItemsForTemplate(ctx context.Context, templateID pgtype.UUID) ([]AuthMenuItem, error)
	GetUsageSummary(ctx context.Context, tenantID pgtype.UUID, periodType string, periodStart pgtype.Date, periodEnd pgtype.Date) (IntelligenceUsageSummary, error)
	GetUserByEmail(ctx context.Context, tenantID pgtype.UUID, email string) (AuthUser, error)
	GetUserByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (GetUserByIDRow, error)
	GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]AuthPermission, error)
	GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]AuthRole, error)
	// ==================== ESTADÍSTICAS DE USUARIOS ====================
	// Estadísticas de usuarios
	GetUserStats(ctx context.Context, tenantID pgtype.UUID) (GetUserStatsRow, error)
	GetUsersByEmailGlobal(ctx context.Context, email string) ([]GetUsersByEmailGlobalRow, error)
	IncrementImportBatchProgress(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, successRows *int32, errorRows *int32, skippedRows *int32) error
	ListAPICallsByEntity(ctx context.Context, tenantID pgtype.UUID, relatedEntityType *string, relatedEntityID pgtype.UUID) ([]IntelligenceApiCall, error)
	ListAPICallsByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]IntelligenceApiCall, error)
	ListActiveLicensesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListActiveLicensesByTenantRow, error)
	ListActiveModelConfigs(ctx context.Context, tenantID pgtype.UUID) ([]IntelligenceModelConfig, error)
	ListActiveTenants(ctx context.Context) ([]Tenant, error)
	ListAllMenuItems(ctx context.Context, tenantID pgtype.UUID) ([]AuthMenuItem, error)
	// Lista todos los items de menú para administración (sin filtrar por template)
	ListAllMenuItemsForAdmin(ctx context.Context) ([]ListAllMenuItemsForAdminRow, error)
	// Permissions
	ListAllPermissions(ctx context.Context) ([]AuthPermission, error)
	ListAllTenants(ctx context.Context) ([]ListAllTenantsRow, error)
	// Query for super admin to list all users across all tenants
	ListAllUsersGlobal(ctx context.Context, limit int32, offset int32) ([]ListAllUsersGlobalRow, error)
	ListAnalysesByType(ctx context.Context, tenantID pgtype.UUID, analysisType string, limit int32, offset int32) ([]IntelligenceAnalysis, error)
	// Brands (catálogo global)
	ListBrands(ctx context.Context) ([]InventoryBrand, error)
	// =============================================
	// CAMERA NVR HISTORY
	// =============================================
	ListCameraNvrHistory(ctx context.Context, cameraID pgtype.UUID, tenantID pgtype.UUID, limit int32) ([]ListCameraNvrHistoryRow, error)
	ListCamerasByArea(ctx context.Context, area *string, tenantID pgtype.UUID) ([]ListCamerasByAreaRow, error)
	ListCamerasByModel(ctx context.Context, modelID pgtype.UUID, tenantID pgtype.UUID) ([]ListCamerasByModelRow, error)
	ListCamerasByNvr(ctx context.Context, nvrServerID pgtype.UUID, tenantID pgtype.UUID) ([]ListCamerasByNvrRow, error)
	ListCamerasBySite(ctx context.Context, siteID pgtype.UUID, tenantID pgtype.UUID) ([]ListCamerasBySiteRow, error)
	ListCamerasByStatus(ctx context.Context, tenantID pgtype.UUID, status NullInventoryEquipmentStatus, limit int32, offset int32) ([]ListCamerasByStatusRow, error)
	ListCamerasByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]ListCamerasByTenantRow, error)
	ListCamerasByType(ctx context.Context, tenantID pgtype.UUID, cameraType NullInventoryCameraType) ([]ListCamerasByTypeRow, error)
	ListClientContacts(ctx context.Context, clientID pgtype.UUID, tenantID pgtype.UUID) ([]PoliciesClientContact, error)
	ListClientsByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]PoliciesClient, error)
	ListEquipmentByClient(ctx context.Context, clientID pgtype.UUID, tenantID pgtype.UUID) ([]ListEquipmentByClientRow, error)
	ListEquipmentBySite(ctx context.Context, siteID pgtype.UUID, tenantID pgtype.UUID) ([]ListEquipmentBySiteRow, error)
	ListEquipmentByStatus(ctx context.Context, tenantID pgtype.UUID, status NullInventoryEquipmentStatus, limit int32, offset int32) ([]ListEquipmentByStatusRow, error)
	// internal/database/queries/inventory.sql
	// Queries para inventario de equipos
	// Equipment Types (catálogo global)
	ListEquipmentTypes(ctx context.Context) ([]InventoryEquipmentType, error)
	ListExpiringLicenses(ctx context.Context, tenantID pgtype.UUID, expiryDate pgtype.Date) ([]ListExpiringLicensesRow, error)
	ListFileAccessLog(ctx context.Context, fileID pgtype.UUID, limit int32, offset int32) ([]StorageFileAccessLog, error)
	ListFilesByCategory(ctx context.Context, tenantID pgtype.UUID, category *string, limit int32, offset int32) ([]StorageFile, error)
	ListFilesByEntity(ctx context.Context, tenantID pgtype.UUID, relatedEntityType *string, relatedEntityID pgtype.UUID) ([]StorageFile, error)
	ListFilesByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]StorageFile, error)
	ListImportBatchItems(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID, limit int32, offset int32) ([]InventoryImportBatchItem, error)
	ListImportBatchItemsByStatus(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID, status *string, limit int32, offset int32) ([]InventoryImportBatchItem, error)
	ListImportBatchesByStatus(ctx context.Context, tenantID pgtype.UUID, status NullInventoryImportStatus) ([]ListImportBatchesByStatusRow, error)
	ListImportBatchesByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]ListImportBatchesByTenantRow, error)
	// =============================================
	// NVR LICENSE HISTORY
	// =============================================
	ListLicenseHistoryByLicense(ctx context.Context, nvrLicenseID pgtype.UUID, tenantID pgtype.UUID, limit int32, offset int32) ([]ListLicenseHistoryByLicenseRow, error)
	ListLicenseHistoryByServer(ctx context.Context, nvrServerID pgtype.UUID, tenantID pgtype.UUID, limit int32, offset int32) ([]ListLicenseHistoryByServerRow, error)
	ListMaintenanceByEquipment(ctx context.Context, equipmentID pgtype.UUID, tenantID pgtype.UUID, limit int32) ([]ListMaintenanceByEquipmentRow, error)
	// internal/database/queries/menu.sql
	// Queries para gestión de items de menú
	ListMenuItems(ctx context.Context, tenantID pgtype.UUID) ([]AuthMenuItem, error)
	// Menu Templates
	ListMenuTemplates(ctx context.Context) ([]AuthMenuTemplate, error)
	ListModelConfigs(ctx context.Context, tenantID pgtype.UUID) ([]IntelligenceModelConfig, error)
	// Models
	ListModelsByBrand(ctx context.Context, brandID pgtype.UUID) ([]ListModelsByBrandRow, error)
	ListModuleStorageMappings(ctx context.Context, tenantID pgtype.UUID) ([]ListModuleStorageMappingsRow, error)
	ListNvrLicensesByServer(ctx context.Context, nvrServerID pgtype.UUID, tenantID pgtype.UUID) ([]InventoryNvrLicense, error)
	ListNvrServersBySite(ctx context.Context, siteID pgtype.UUID, tenantID pgtype.UUID) ([]ListNvrServersBySiteRow, error)
	ListNvrServersByStatus(ctx context.Context, tenantID pgtype.UUID, status NullInventoryEquipmentStatus) ([]ListNvrServersByStatusRow, error)
	ListNvrServersByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListNvrServersByTenantRow, error)
	ListPendingImportBatchItems(ctx context.Context, batchID pgtype.UUID, tenantID pgtype.UUID, limit int32) ([]InventoryImportBatchItem, error)
	ListPendingProcessing(ctx context.Context, tenantID pgtype.UUID, limit int32) ([]StorageFileProcessing, error)
	ListPermissionsByModule(ctx context.Context, module *string) ([]AuthPermission, error)
	ListPermissionsByScope(ctx context.Context, scope *string) ([]AuthPermission, error)
	// internal/database/queries/policies.sql
	// Queries para módulo de pólizas y relación con activos
	ListPoliciesByTenant(ctx context.Context, tenantID pgtype.UUID, column2 interface{}, column3 interface{}, column4 interface{}, limit int32, offset int32) ([]ListPoliciesByTenantRow, error)
	ListPolicyAssets(ctx context.Context, policyID pgtype.UUID, tenantID pgtype.UUID) ([]ListPolicyAssetsRow, error)
	ListPromptTemplates(ctx context.Context, tenantID pgtype.UUID) ([]IntelligencePromptTemplate, error)
	ListPromptTemplatesByCategory(ctx context.Context, category string, tenantID pgtype.UUID) ([]IntelligencePromptTemplate, error)
	ListRolesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]AuthRole, error)
	ListSitesByClient(ctx context.Context, clientID pgtype.UUID, tenantID pgtype.UUID) ([]PoliciesSite, error)
	// internal/database/queries/sla.sql
	// Queries para políticas SLA y snapshots por ticket
	ListSlaPoliciesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]TicketsSlaPolicy, error)
	ListStorageConfigurations(ctx context.Context, tenantID pgtype.UUID) ([]ListStorageConfigurationsRow, error)
	// ==================== STORAGE CONFIGURATION ====================
	ListStorageProviders(ctx context.Context) ([]StorageStorageProvider, error)
	ListStorageUnitsByServer(ctx context.Context, nvrServerID pgtype.UUID, tenantID pgtype.UUID) ([]InventoryNvrStorageUnit, error)
	ListTenants(ctx context.Context, limit int32, offset int32) ([]Tenant, error)
	ListTicketComments(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) ([]ListTicketCommentsRow, error)
	ListTicketEvidences(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) ([]TicketsTicketEvidence, error)
	ListTicketTimeline(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) ([]ListTicketTimelineRow, error)
	ListTicketsByCoverageStatus(ctx context.Context, tenantID pgtype.UUID, coverageStatus TicketsCoverageStatus, limit int32, offset int32) ([]ListTicketsByCoverageStatusRow, error)
	ListTicketsByPriority(ctx context.Context, tenantID pgtype.UUID, priority NullTicketsTicketPriority, limit int32, offset int32) ([]ListTicketsByPriorityRow, error)
	ListTicketsBySlaStatus(ctx context.Context, tenantID pgtype.UUID, status TicketsSlaStatus, limit int32, offset int32) ([]ListTicketsBySlaStatusRow, error)
	ListTicketsByStatus(ctx context.Context, tenantID pgtype.UUID, status NullTicketsTicketStatus, limit int32, offset int32) ([]ListTicketsByStatusRow, error)
	ListTicketsByTechnician(ctx context.Context, tenantID pgtype.UUID, assignedTo pgtype.UUID) ([]ListTicketsByTechnicianRow, error)
	ListTicketsByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]ListTicketsByTenantRow, error)
	ListTicketsByType(ctx context.Context, tenantID pgtype.UUID, type_ TicketsTicketType, limit int32, offset int32) ([]ListTicketsByTypeRow, error)
	ListUnverifiedAnalyses(ctx context.Context, tenantID pgtype.UUID, limit int32) ([]IntelligenceAnalysis, error)
	ListUsageSummaries(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]IntelligenceUsageSummary, error)
	ListUsersByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]ListUsersByTenantRow, error)
	// Query for super admin to list users of a specific tenant
	ListUsersByTenantAdmin(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]ListUsersByTenantAdminRow, error)
	ListWorklogsByTicket(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) ([]ListWorklogsByTicketRow, error)
	MarkTicketSlaResolved(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) error
	MarkTicketSlaResponded(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) error
	RefreshTicketSlaStatus(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) error
	// Elimina todos los items de un template
	RemoveAllItemsFromTemplate(ctx context.Context, templateID pgtype.UUID) error
	// Elimina un item de un template
	RemoveItemFromTemplate(ctx context.Context, templateID pgtype.UUID, menuItemID pgtype.UUID) error
	RemovePolicyAsset(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	RemoveRoleFromUser(ctx context.Context, userID pgtype.UUID, roleID pgtype.UUID) error
	RemoveTemplateFromTenant(ctx context.Context, tenantID pgtype.UUID) error
	ReorderMenuItems(ctx context.Context, iD pgtype.UUID, displayOrder *int32) error
	ScheduleMaintenance(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, nextMaintenanceAt pgtype.Timestamptz) error
	SearchCameras(ctx context.Context, tenantID pgtype.UUID, column2 *string, limit int32, offset int32) ([]SearchCamerasRow, error)
	SearchClients(ctx context.Context, tenantID pgtype.UUID, companyName string, limit int32) ([]PoliciesClient, error)
	SelectSlaPolicyForTicket(ctx context.Context, tenantID pgtype.UUID, ticketPriority NullTicketsTicketPriority, ticketType NullTicketsTicketType) (TicketsSlaPolicy, error)
	SetDefaultModelConfig(ctx context.Context, tenantID pgtype.UUID, iD pgtype.UUID) error
	SoftDeletePolicy(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	StartTicket(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
	// Cambia la visibilidad de un item en un template
	ToggleItemVisibilityInTemplate(ctx context.Context, templateID pgtype.UUID, menuItemID pgtype.UUID, isVisible *bool) (AuthMenuTemplateItem, error)
	ToggleMenuItem(ctx context.Context, iD pgtype.UUID, isActive *bool) (AuthMenuItem, error)
	ToggleModelConfigActive(ctx context.Context, iD pgtype.UUID, isActive *bool) (IntelligenceModelConfig, error)
	UpdateAPICallResponse(ctx context.Context, arg UpdateAPICallResponseParams) (IntelligenceApiCall, error)
	UpdateCamera(ctx context.Context, arg UpdateCameraParams) (InventoryCamera, error)
	UpdateCameraNvr(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, nvrServerID pgtype.UUID, updatedBy pgtype.UUID) error
	UpdateCameraStatus(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, status NullInventoryEquipmentStatus, updatedBy pgtype.UUID) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) (PoliciesClient, error)
	UpdateEquipmentLocation(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, siteID pgtype.UUID, areaID pgtype.UUID, locationDescription *string, latitude pgtype.Numeric, longitude pgtype.Numeric) error
	UpdateEquipmentStatus(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, status NullInventoryEquipmentStatus) error
	UpdateFileProcessed(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (StorageFile, error)
	UpdateImportBatchItemStatus(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, status *string, errorMessage *string, createdRecordID pgtype.UUID, createdRecordTable *string) error
	UpdateImportBatchProgress(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, processedRows *int32, successRows *int32, errorRows *int32, skippedRows *int32) error
	UpdateImportBatchStatus(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, status NullInventoryImportStatus, errorMessage *string) error
	// Actualiza el orden de un item en un template
	UpdateItemOrderInTemplate(ctx context.Context, templateID pgtype.UUID, menuItemID pgtype.UUID, displayOrder *int32) error
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateLicenseUsage(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, usedLicenses int32) error
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (AuthMenuItem, error)
	UpdateModelConfig(ctx context.Context, iD pgtype.UUID, name string, apiEndpoint *string, defaultTemperature pgtype.Numeric, defaultMaxTokens *int32, maxRequestsPerDay *int32, monthlyBudgetUsd pgtype.Numeric, description *string, settings []byte) (IntelligenceModelConfig, error)
	UpdateNvrLicense(ctx context.Context, arg UpdateNvrLicenseParams) (InventoryNvrLicense, error)
	UpdateNvrServer(ctx context.Context, arg UpdateNvrServerParams) (InventoryNvrServer, error)
	UpdateNvrServerStatus(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, status NullInventoryEquipmentStatus, updatedBy pgtype.UUID) error
	UpdateNvrStorageUnit(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, diskType *string, brand *string, model *string, serialNumber *string, capacityTb pgtype.Numeric, status *string, healthPercentage *int32) (InventoryNvrStorageUnit, error)
	UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (PoliciesPolicy, error)
	UpdateProcessingResult(ctx context.Context, iD pgtype.UUID, status *string, result []byte, errorMessage *string, processingTimeMs *int32) (StorageFileProcessing, error)
	UpdateProcessingStatus(ctx context.Context, iD pgtype.UUID, status *string, processingTimeMs *int32) (StorageFileProcessing, error)
	UpdatePromptTemplate(ctx context.Context, iD pgtype.UUID, systemPrompt *string, userPromptTemplate string, temperature pgtype.Numeric, maxTokens *int32, description *string) (IntelligencePromptTemplate, error)
	UpdateRole(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, name string, description *string) (AuthRole, error)
	UpdateRoleGlobal(ctx context.Context, iD pgtype.UUID, name string, description *string) (AuthRole, error)
	UpdateSite(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, name string, address *string, city *string, state *string, latitude pgtype.Numeric, longitude pgtype.Numeric, contactName *string, contactPhone *string) (PoliciesSite, error)
	UpdateSlaPolicy(ctx context.Context, arg UpdateSlaPolicyParams) (TicketsSlaPolicy, error)
	UpdateStorageConfiguration(ctx context.Context, arg UpdateStorageConfigurationParams) (StorageStorageConfiguration, error)
	UpdateTenant(ctx context.Context, iD pgtype.UUID, name string, domain *string, logoUrl *string, primaryColor *string, secondaryColor *string, tertiaryColor *string, subscriptionPlan *string, maxUsers *int32, maxClients *int32) (Tenant, error)
	UpdateTenantSettings(ctx context.Context, iD pgtype.UUID, settings []byte) (Tenant, error)
	UpdateTenantTheme(ctx context.Context, iD pgtype.UUID, primaryColor *string, secondaryColor *string, tertiaryColor *string, logoUrl *string) (Tenant, error)
	// ============================================
	// EXTENDED QUERIES FOR TICKET MODULE
	// ============================================
	UpdateTicket(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, title string, description *string, priority NullTicketsTicketPriority, type_ TicketsTicketType, siteID pgtype.UUID, equipmentID pgtype.UUID, scheduledDate pgtype.Timestamptz) error
	UpdateTicketSlaFields(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, slaHours *int32, slaDeadline pgtype.Timestamptz) error
	UpdateTicketStatus(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, status NullTicketsTicketStatus) error
	UpdateUsageSummary(ctx context.Context, arg UpdateUsageSummaryParams) (IntelligenceUsageSummary, error)
	UpdateUser(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, firstName string, lastName string, phone *string) (AuthUser, error)
	UpdateUserAvatar(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, avatarUrl *string) (AuthUser, error)
	UpdateUserPassword(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID, passwordHash string) error
	UpsertTicketPolicyLink(ctx context.Context, tenantID pgtype.UUID, ticketID pgtype.UUID, policyID pgtype.UUID, coverageStatus TicketsCoverageStatus, notes *string) (TicketsTicketPolicyLink, error)
	VerifyAnalysis(ctx context.Context, iD pgtype.UUID, verifiedBy pgtype.UUID, verificationNotes *string, isCorrect *bool) (IntelligenceAnalysis, error)
	VerifyUserEmail(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
