// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sla.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSlaPolicy = `-- name: CreateSlaPolicy :one
INSERT INTO tickets.sla_policies (
    tenant_id,
    name,
    ticket_priority,
    ticket_type,
    response_time_hours,
    resolution_time_hours,
    is_default,
    is_active,
    business_hours,
    created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, name, ticket_priority, ticket_type, response_time_hours, resolution_time_hours, is_default, is_active, business_hours, created_by, updated_by, created_at, updated_at
`

func (q *Queries) CreateSlaPolicy(ctx context.Context, tenantID pgtype.UUID, name string, ticketPriority NullTicketsTicketPriority, ticketType NullTicketsTicketType, responseTimeHours int32, resolutionTimeHours int32, isDefault bool, isActive bool, businessHours []byte, createdBy pgtype.UUID) (TicketsSlaPolicy, error) {
	row := q.db.QueryRow(ctx, createSlaPolicy,
		tenantID,
		name,
		ticketPriority,
		ticketType,
		responseTimeHours,
		resolutionTimeHours,
		isDefault,
		isActive,
		businessHours,
		createdBy,
	)
	var i TicketsSlaPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TicketPriority,
		&i.TicketType,
		&i.ResponseTimeHours,
		&i.ResolutionTimeHours,
		&i.IsDefault,
		&i.IsActive,
		&i.BusinessHours,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketSlaInstance = `-- name: CreateTicketSlaInstance :one
INSERT INTO tickets.ticket_sla_instances (
    tenant_id,
    ticket_id,
    sla_policy_id,
    priority_snapshot,
    type_snapshot,
    response_time_hours,
    resolution_time_hours,
    due_response_at,
    due_resolution_at,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, ticket_id, sla_policy_id, priority_snapshot, type_snapshot, response_time_hours, resolution_time_hours, due_response_at, due_resolution_at, responded_at, resolved_at, breached_response, breached_resolution, status, created_at, updated_at
`

func (q *Queries) CreateTicketSlaInstance(ctx context.Context, tenantID pgtype.UUID, ticketID pgtype.UUID, slaPolicyID pgtype.UUID, prioritySnapshot NullTicketsTicketPriority, typeSnapshot NullTicketsTicketType, responseTimeHours *int32, resolutionTimeHours *int32, dueResponseAt pgtype.Timestamptz, dueResolutionAt pgtype.Timestamptz, status TicketsSlaStatus) (TicketsTicketSlaInstance, error) {
	row := q.db.QueryRow(ctx, createTicketSlaInstance,
		tenantID,
		ticketID,
		slaPolicyID,
		prioritySnapshot,
		typeSnapshot,
		responseTimeHours,
		resolutionTimeHours,
		dueResponseAt,
		dueResolutionAt,
		status,
	)
	var i TicketsTicketSlaInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TicketID,
		&i.SlaPolicyID,
		&i.PrioritySnapshot,
		&i.TypeSnapshot,
		&i.ResponseTimeHours,
		&i.ResolutionTimeHours,
		&i.DueResponseAt,
		&i.DueResolutionAt,
		&i.RespondedAt,
		&i.ResolvedAt,
		&i.BreachedResponse,
		&i.BreachedResolution,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateSlaPolicy = `-- name: DeactivateSlaPolicy :exec
UPDATE tickets.sla_policies
SET is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) DeactivateSlaPolicy(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateSlaPolicy, iD, tenantID)
	return err
}

const getSlaPolicyByID = `-- name: GetSlaPolicyByID :one
SELECT id, tenant_id, name, ticket_priority, ticket_type, response_time_hours, resolution_time_hours, is_default, is_active, business_hours, created_by, updated_by, created_at, updated_at
FROM tickets.sla_policies
WHERE id = $1
    AND tenant_id = $2
LIMIT 1
`

func (q *Queries) GetSlaPolicyByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (TicketsSlaPolicy, error) {
	row := q.db.QueryRow(ctx, getSlaPolicyByID, iD, tenantID)
	var i TicketsSlaPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TicketPriority,
		&i.TicketType,
		&i.ResponseTimeHours,
		&i.ResolutionTimeHours,
		&i.IsDefault,
		&i.IsActive,
		&i.BusinessHours,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketPolicyLinkByTicketID = `-- name: GetTicketPolicyLinkByTicketID :one
SELECT tpl.id, tpl.tenant_id, tpl.ticket_id, tpl.policy_id, tpl.coverage_status, tpl.notes, tpl.created_at, tpl.updated_at,
    p.policy_number,
    p.vendor,
    p.contract_type
FROM tickets.ticket_policy_links tpl
LEFT JOIN policies.policies p ON p.id = tpl.policy_id
WHERE tpl.ticket_id = $1
    AND tpl.tenant_id = $2
LIMIT 1
`

type GetTicketPolicyLinkByTicketIDRow struct {
	ID             pgtype.UUID           `db:"id" json:"id"`
	TenantID       pgtype.UUID           `db:"tenant_id" json:"tenant_id"`
	TicketID       pgtype.UUID           `db:"ticket_id" json:"ticket_id"`
	PolicyID       pgtype.UUID           `db:"policy_id" json:"policy_id"`
	CoverageStatus TicketsCoverageStatus `db:"coverage_status" json:"coverage_status"`
	Notes          *string               `db:"notes" json:"notes"`
	CreatedAt      pgtype.Timestamptz    `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz    `db:"updated_at" json:"updated_at"`
	PolicyNumber   *string               `db:"policy_number" json:"policy_number"`
	Vendor         *string               `db:"vendor" json:"vendor"`
	ContractType   *string               `db:"contract_type" json:"contract_type"`
}

func (q *Queries) GetTicketPolicyLinkByTicketID(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) (GetTicketPolicyLinkByTicketIDRow, error) {
	row := q.db.QueryRow(ctx, getTicketPolicyLinkByTicketID, ticketID, tenantID)
	var i GetTicketPolicyLinkByTicketIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TicketID,
		&i.PolicyID,
		&i.CoverageStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolicyNumber,
		&i.Vendor,
		&i.ContractType,
	)
	return i, err
}

const getTicketSlaInstanceByTicketID = `-- name: GetTicketSlaInstanceByTicketID :one
SELECT tsi.id, tsi.tenant_id, tsi.ticket_id, tsi.sla_policy_id, tsi.priority_snapshot, tsi.type_snapshot, tsi.response_time_hours, tsi.resolution_time_hours, tsi.due_response_at, tsi.due_resolution_at, tsi.responded_at, tsi.resolved_at, tsi.breached_response, tsi.breached_resolution, tsi.status, tsi.created_at, tsi.updated_at,
    sp.name AS sla_policy_name
FROM tickets.ticket_sla_instances tsi
LEFT JOIN tickets.sla_policies sp ON sp.id = tsi.sla_policy_id
WHERE tsi.ticket_id = $1
    AND tsi.tenant_id = $2
LIMIT 1
`

type GetTicketSlaInstanceByTicketIDRow struct {
	ID                  pgtype.UUID               `db:"id" json:"id"`
	TenantID            pgtype.UUID               `db:"tenant_id" json:"tenant_id"`
	TicketID            pgtype.UUID               `db:"ticket_id" json:"ticket_id"`
	SlaPolicyID         pgtype.UUID               `db:"sla_policy_id" json:"sla_policy_id"`
	PrioritySnapshot    NullTicketsTicketPriority `db:"priority_snapshot" json:"priority_snapshot"`
	TypeSnapshot        NullTicketsTicketType     `db:"type_snapshot" json:"type_snapshot"`
	ResponseTimeHours   *int32                    `db:"response_time_hours" json:"response_time_hours"`
	ResolutionTimeHours *int32                    `db:"resolution_time_hours" json:"resolution_time_hours"`
	DueResponseAt       pgtype.Timestamptz        `db:"due_response_at" json:"due_response_at"`
	DueResolutionAt     pgtype.Timestamptz        `db:"due_resolution_at" json:"due_resolution_at"`
	RespondedAt         pgtype.Timestamptz        `db:"responded_at" json:"responded_at"`
	ResolvedAt          pgtype.Timestamptz        `db:"resolved_at" json:"resolved_at"`
	BreachedResponse    bool                      `db:"breached_response" json:"breached_response"`
	BreachedResolution  bool                      `db:"breached_resolution" json:"breached_resolution"`
	Status              TicketsSlaStatus          `db:"status" json:"status"`
	CreatedAt           pgtype.Timestamptz        `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz        `db:"updated_at" json:"updated_at"`
	SlaPolicyName       *string                   `db:"sla_policy_name" json:"sla_policy_name"`
}

func (q *Queries) GetTicketSlaInstanceByTicketID(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) (GetTicketSlaInstanceByTicketIDRow, error) {
	row := q.db.QueryRow(ctx, getTicketSlaInstanceByTicketID, ticketID, tenantID)
	var i GetTicketSlaInstanceByTicketIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TicketID,
		&i.SlaPolicyID,
		&i.PrioritySnapshot,
		&i.TypeSnapshot,
		&i.ResponseTimeHours,
		&i.ResolutionTimeHours,
		&i.DueResponseAt,
		&i.DueResolutionAt,
		&i.RespondedAt,
		&i.ResolvedAt,
		&i.BreachedResponse,
		&i.BreachedResolution,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlaPolicyName,
	)
	return i, err
}

const listSlaPoliciesByTenant = `-- name: ListSlaPoliciesByTenant :many

SELECT id, tenant_id, name, ticket_priority, ticket_type, response_time_hours, resolution_time_hours, is_default, is_active, business_hours, created_by, updated_by, created_at, updated_at
FROM tickets.sla_policies
WHERE tenant_id = $1
    AND is_active = true
ORDER BY is_default DESC,
    name ASC
`

// internal/database/queries/sla.sql
// Queries para políticas SLA y snapshots por ticket
func (q *Queries) ListSlaPoliciesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]TicketsSlaPolicy, error) {
	rows, err := q.db.Query(ctx, listSlaPoliciesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketsSlaPolicy{}
	for rows.Next() {
		var i TicketsSlaPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TicketPriority,
			&i.TicketType,
			&i.ResponseTimeHours,
			&i.ResolutionTimeHours,
			&i.IsDefault,
			&i.IsActive,
			&i.BusinessHours,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTicketSlaResolved = `-- name: MarkTicketSlaResolved :exec
UPDATE tickets.ticket_sla_instances
SET resolved_at = COALESCE(resolved_at, CURRENT_TIMESTAMP),
    breached_resolution = CASE
        WHEN due_resolution_at IS NOT NULL
             AND COALESCE(resolved_at, CURRENT_TIMESTAMP) > due_resolution_at THEN true
        ELSE breached_resolution
    END,
    status = CASE
        WHEN due_resolution_at IS NOT NULL
             AND COALESCE(resolved_at, CURRENT_TIMESTAMP) > due_resolution_at THEN 'breached'::tickets.sla_status
        ELSE 'ok'::tickets.sla_status
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE ticket_id = $1
    AND tenant_id = $2
`

func (q *Queries) MarkTicketSlaResolved(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markTicketSlaResolved, ticketID, tenantID)
	return err
}

const markTicketSlaResponded = `-- name: MarkTicketSlaResponded :exec
UPDATE tickets.ticket_sla_instances
SET responded_at = COALESCE(responded_at, CURRENT_TIMESTAMP),
    breached_response = CASE
        WHEN due_response_at IS NOT NULL
             AND COALESCE(responded_at, CURRENT_TIMESTAMP) > due_response_at THEN true
        ELSE breached_response
    END,
    status = CASE
        WHEN due_response_at IS NOT NULL
             AND COALESCE(responded_at, CURRENT_TIMESTAMP) > due_response_at THEN 'breached'::tickets.sla_status
        WHEN status = 'unknown' THEN 'ok'::tickets.sla_status
        ELSE status
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE ticket_id = $1
    AND tenant_id = $2
`

func (q *Queries) MarkTicketSlaResponded(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markTicketSlaResponded, ticketID, tenantID)
	return err
}

const refreshTicketSlaStatus = `-- name: RefreshTicketSlaStatus :exec
UPDATE tickets.ticket_sla_instances
SET breached_response = CASE
        WHEN responded_at IS NULL
             AND due_response_at IS NOT NULL
             AND CURRENT_TIMESTAMP > due_response_at THEN true
        ELSE breached_response
    END,
    breached_resolution = CASE
        WHEN resolved_at IS NULL
             AND due_resolution_at IS NOT NULL
             AND CURRENT_TIMESTAMP > due_resolution_at THEN true
        ELSE breached_resolution
    END,
    status = CASE
        WHEN (resolved_at IS NULL AND due_resolution_at IS NOT NULL AND CURRENT_TIMESTAMP > due_resolution_at)
          OR (responded_at IS NULL AND due_response_at IS NOT NULL AND CURRENT_TIMESTAMP > due_response_at)
            THEN 'breached'::tickets.sla_status
        WHEN (resolved_at IS NULL AND due_resolution_at IS NOT NULL AND CURRENT_TIMESTAMP + INTERVAL '2 hour' > due_resolution_at)
          OR (responded_at IS NULL AND due_response_at IS NOT NULL AND CURRENT_TIMESTAMP + INTERVAL '1 hour' > due_response_at)
            THEN 'at_risk'::tickets.sla_status
        ELSE 'ok'::tickets.sla_status
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE ticket_id = $1
    AND tenant_id = $2
`

func (q *Queries) RefreshTicketSlaStatus(ctx context.Context, ticketID pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshTicketSlaStatus, ticketID, tenantID)
	return err
}

const selectSlaPolicyForTicket = `-- name: SelectSlaPolicyForTicket :one
SELECT id, tenant_id, name, ticket_priority, ticket_type, response_time_hours, resolution_time_hours, is_default, is_active, business_hours, created_by, updated_by, created_at, updated_at
FROM tickets.sla_policies
WHERE tenant_id = $1
    AND is_active = true
    AND (ticket_priority::text = $2 OR ticket_priority IS NULL)
    AND (ticket_type::text = $3 OR ticket_type IS NULL)
ORDER BY
    CASE WHEN ticket_priority::text = $2 THEN 0 ELSE 1 END,
    CASE WHEN ticket_type::text = $3 THEN 0 ELSE 1 END,
    CASE WHEN is_default THEN 0 ELSE 1 END,
    created_at ASC
LIMIT 1
`

func (q *Queries) SelectSlaPolicyForTicket(ctx context.Context, tenantID pgtype.UUID, ticketPriority NullTicketsTicketPriority, ticketType NullTicketsTicketType) (TicketsSlaPolicy, error) {
	row := q.db.QueryRow(ctx, selectSlaPolicyForTicket, tenantID, ticketPriority, ticketType)
	var i TicketsSlaPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TicketPriority,
		&i.TicketType,
		&i.ResponseTimeHours,
		&i.ResolutionTimeHours,
		&i.IsDefault,
		&i.IsActive,
		&i.BusinessHours,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSlaPolicy = `-- name: UpdateSlaPolicy :one
UPDATE tickets.sla_policies
SET name = COALESCE($3, name),
    ticket_priority = COALESCE($4, ticket_priority),
    ticket_type = COALESCE($5, ticket_type),
    response_time_hours = COALESCE($6, response_time_hours),
    resolution_time_hours = COALESCE($7, resolution_time_hours),
    is_default = COALESCE($8, is_default),
    is_active = COALESCE($9, is_active),
    business_hours = COALESCE($10, business_hours),
    updated_by = $11,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
RETURNING id, tenant_id, name, ticket_priority, ticket_type, response_time_hours, resolution_time_hours, is_default, is_active, business_hours, created_by, updated_by, created_at, updated_at
`

type UpdateSlaPolicyParams struct {
	ID                  pgtype.UUID               `db:"id" json:"id"`
	TenantID            pgtype.UUID               `db:"tenant_id" json:"tenant_id"`
	Name                string                    `db:"name" json:"name"`
	TicketPriority      NullTicketsTicketPriority `db:"ticket_priority" json:"ticket_priority"`
	TicketType          NullTicketsTicketType     `db:"ticket_type" json:"ticket_type"`
	ResponseTimeHours   int32                     `db:"response_time_hours" json:"response_time_hours"`
	ResolutionTimeHours int32                     `db:"resolution_time_hours" json:"resolution_time_hours"`
	IsDefault           bool                      `db:"is_default" json:"is_default"`
	IsActive            bool                      `db:"is_active" json:"is_active"`
	BusinessHours       []byte                    `db:"business_hours" json:"business_hours"`
	UpdatedBy           pgtype.UUID               `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateSlaPolicy(ctx context.Context, arg UpdateSlaPolicyParams) (TicketsSlaPolicy, error) {
	row := q.db.QueryRow(ctx, updateSlaPolicy,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.TicketPriority,
		arg.TicketType,
		arg.ResponseTimeHours,
		arg.ResolutionTimeHours,
		arg.IsDefault,
		arg.IsActive,
		arg.BusinessHours,
		arg.UpdatedBy,
	)
	var i TicketsSlaPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TicketPriority,
		&i.TicketType,
		&i.ResponseTimeHours,
		&i.ResolutionTimeHours,
		&i.IsDefault,
		&i.IsActive,
		&i.BusinessHours,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTicketPolicyLink = `-- name: UpsertTicketPolicyLink :one
INSERT INTO tickets.ticket_policy_links (
    tenant_id,
    ticket_id,
    policy_id,
    coverage_status,
    notes
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (ticket_id)
DO UPDATE SET
    policy_id = EXCLUDED.policy_id,
    coverage_status = EXCLUDED.coverage_status,
    notes = EXCLUDED.notes,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, tenant_id, ticket_id, policy_id, coverage_status, notes, created_at, updated_at
`

func (q *Queries) UpsertTicketPolicyLink(ctx context.Context, tenantID pgtype.UUID, ticketID pgtype.UUID, policyID pgtype.UUID, coverageStatus TicketsCoverageStatus, notes *string) (TicketsTicketPolicyLink, error) {
	row := q.db.QueryRow(ctx, upsertTicketPolicyLink,
		tenantID,
		ticketID,
		policyID,
		coverageStatus,
		notes,
	)
	var i TicketsTicketPolicyLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TicketID,
		&i.PolicyID,
		&i.CoverageStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
