// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFileAccess = `-- name: CountFileAccess :one
SELECT COUNT(*)
FROM storage.file_access_log
WHERE file_id = $1
    AND access_type = $2
`

func (q *Queries) CountFileAccess(ctx context.Context, fileID pgtype.UUID, accessType string) (int64, error) {
	row := q.db.QueryRow(ctx, countFileAccess, fileID, accessType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilesByTenant = `-- name: CountFilesByTenant :one
SELECT COUNT(*)
FROM storage.files
WHERE tenant_id = $1
`

func (q *Queries) CountFilesByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFilesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO storage.files (
        tenant_id,
        filename,
        original_filename,
        mime_type,
        file_size,
        file_hash,
        storage_provider,
        storage_bucket,
        storage_path,
        storage_url,
        category,
        related_entity_type,
        related_entity_id,
        metadata,
        uploaded_by
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15
    )
RETURNING id, tenant_id, filename, original_filename, mime_type, file_size, file_hash, storage_provider, storage_bucket, storage_path, storage_url, category, related_entity_type, related_entity_id, is_processed, processed_at, metadata, uploaded_by, created_at, updated_at
`

type CreateFileParams struct {
	TenantID          pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Filename          string      `db:"filename" json:"filename"`
	OriginalFilename  string      `db:"original_filename" json:"original_filename"`
	MimeType          string      `db:"mime_type" json:"mime_type"`
	FileSize          int64       `db:"file_size" json:"file_size"`
	FileHash          *string     `db:"file_hash" json:"file_hash"`
	StorageProvider   *string     `db:"storage_provider" json:"storage_provider"`
	StorageBucket     *string     `db:"storage_bucket" json:"storage_bucket"`
	StoragePath       string      `db:"storage_path" json:"storage_path"`
	StorageUrl        *string     `db:"storage_url" json:"storage_url"`
	Category          *string     `db:"category" json:"category"`
	RelatedEntityType *string     `db:"related_entity_type" json:"related_entity_type"`
	RelatedEntityID   pgtype.UUID `db:"related_entity_id" json:"related_entity_id"`
	Metadata          []byte      `db:"metadata" json:"metadata"`
	UploadedBy        pgtype.UUID `db:"uploaded_by" json:"uploaded_by"`
}

// internal/database/queries/storage.sql
// Queries para gestión de archivos y multimedia
// ==================== FILES ====================
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (StorageFile, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.TenantID,
		arg.Filename,
		arg.OriginalFilename,
		arg.MimeType,
		arg.FileSize,
		arg.FileHash,
		arg.StorageProvider,
		arg.StorageBucket,
		arg.StoragePath,
		arg.StorageUrl,
		arg.Category,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
		arg.Metadata,
		arg.UploadedBy,
	)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filename,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.FileHash,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StoragePath,
		&i.StorageUrl,
		&i.Category,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.IsProcessed,
		&i.ProcessedAt,
		&i.Metadata,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFileAccessLog = `-- name: CreateFileAccessLog :one
INSERT INTO storage.file_access_log (
        tenant_id,
        file_id,
        access_type,
        accessed_by,
        ip_address,
        user_agent
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, file_id, access_type, accessed_by, ip_address, user_agent, created_at
`

// ==================== FILE ACCESS LOG ====================
func (q *Queries) CreateFileAccessLog(ctx context.Context, tenantID pgtype.UUID, fileID pgtype.UUID, accessType string, accessedBy pgtype.UUID, ipAddress *netip.Addr, userAgent *string) (StorageFileAccessLog, error) {
	row := q.db.QueryRow(ctx, createFileAccessLog,
		tenantID,
		fileID,
		accessType,
		accessedBy,
		ipAddress,
		userAgent,
	)
	var i StorageFileAccessLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileID,
		&i.AccessType,
		&i.AccessedBy,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createFileProcessing = `-- name: CreateFileProcessing :one
INSERT INTO storage.file_processing (
        tenant_id,
        file_id,
        processing_type,
        status
    )
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, file_id, processing_type, status, result, error_message, started_at, completed_at, processing_time_ms, created_at, updated_at
`

// ==================== FILE PROCESSING ====================
func (q *Queries) CreateFileProcessing(ctx context.Context, tenantID pgtype.UUID, fileID pgtype.UUID, processingType string, status *string) (StorageFileProcessing, error) {
	row := q.db.QueryRow(ctx, createFileProcessing,
		tenantID,
		fileID,
		processingType,
		status,
	)
	var i StorageFileProcessing
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileID,
		&i.ProcessingType,
		&i.Status,
		&i.Result,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProcessingTimeMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createModuleStorageMapping = `-- name: CreateModuleStorageMapping :one
INSERT INTO storage.module_storage_mappings (
        tenant_id,
        module_name,
        collection_name,
        config_id,
        is_active,
        max_file_size_mb,
        allowed_file_types,
        auto_resize,
        thumbnail_sizes
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, module_name, collection_name, config_id, is_active, max_file_size_mb, allowed_file_types, auto_resize, thumbnail_sizes, created_at, updated_at
`

func (q *Queries) CreateModuleStorageMapping(ctx context.Context, tenantID pgtype.UUID, moduleName string, collectionName string, configID pgtype.UUID, isActive *bool, maxFileSizeMb *int32, allowedFileTypes []string, autoResize *bool, thumbnailSizes []int32) (StorageModuleStorageMapping, error) {
	row := q.db.QueryRow(ctx, createModuleStorageMapping,
		tenantID,
		moduleName,
		collectionName,
		configID,
		isActive,
		maxFileSizeMb,
		allowedFileTypes,
		autoResize,
		thumbnailSizes,
	)
	var i StorageModuleStorageMapping
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleName,
		&i.CollectionName,
		&i.ConfigID,
		&i.IsActive,
		&i.MaxFileSizeMb,
		&i.AllowedFileTypes,
		&i.AutoResize,
		&i.ThumbnailSizes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStorageConfiguration = `-- name: CreateStorageConfiguration :one
INSERT INTO storage.storage_configurations (
        tenant_id,
        provider_id,
        config_name,
        is_default,
        is_active,
        host,
        port,
        database_name,
        username,
        password_text,
        api_key,
        secret_key,
        base_url,
        bucket_name,
        region,
        project_id,
        additional_config,
        module_mappings
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18
    )
RETURNING id, tenant_id, provider_id, config_name, is_default, is_active, host, port, database_name, username, password_text, api_key, secret_key, base_url, bucket_name, region, project_id, additional_config, module_mappings, created_at, updated_at
`

type CreateStorageConfigurationParams struct {
	TenantID         pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	ProviderID       int32       `db:"provider_id" json:"provider_id"`
	ConfigName       string      `db:"config_name" json:"config_name"`
	IsDefault        *bool       `db:"is_default" json:"is_default"`
	IsActive         *bool       `db:"is_active" json:"is_active"`
	Host             *string     `db:"host" json:"host"`
	Port             *int32      `db:"port" json:"port"`
	DatabaseName     *string     `db:"database_name" json:"database_name"`
	Username         *string     `db:"username" json:"username"`
	PasswordText     *string     `db:"password_text" json:"password_text"`
	ApiKey           *string     `db:"api_key" json:"api_key"`
	SecretKey        *string     `db:"secret_key" json:"secret_key"`
	BaseUrl          *string     `db:"base_url" json:"base_url"`
	BucketName       *string     `db:"bucket_name" json:"bucket_name"`
	Region           *string     `db:"region" json:"region"`
	ProjectID        *string     `db:"project_id" json:"project_id"`
	AdditionalConfig []byte      `db:"additional_config" json:"additional_config"`
	ModuleMappings   []byte      `db:"module_mappings" json:"module_mappings"`
}

func (q *Queries) CreateStorageConfiguration(ctx context.Context, arg CreateStorageConfigurationParams) (StorageStorageConfiguration, error) {
	row := q.db.QueryRow(ctx, createStorageConfiguration,
		arg.TenantID,
		arg.ProviderID,
		arg.ConfigName,
		arg.IsDefault,
		arg.IsActive,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.Username,
		arg.PasswordText,
		arg.ApiKey,
		arg.SecretKey,
		arg.BaseUrl,
		arg.BucketName,
		arg.Region,
		arg.ProjectID,
		arg.AdditionalConfig,
		arg.ModuleMappings,
	)
	var i StorageStorageConfiguration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.ConfigName,
		&i.IsDefault,
		&i.IsActive,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.PasswordText,
		&i.ApiKey,
		&i.SecretKey,
		&i.BaseUrl,
		&i.BucketName,
		&i.Region,
		&i.ProjectID,
		&i.AdditionalConfig,
		&i.ModuleMappings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM storage.files
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) DeleteFile(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, iD, tenantID)
	return err
}

const deleteProcessing = `-- name: DeleteProcessing :exec
DELETE FROM storage.file_processing
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) DeleteProcessing(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProcessing, iD, tenantID)
	return err
}

const deleteStorageConfiguration = `-- name: DeleteStorageConfiguration :exec
DELETE FROM storage.storage_configurations
WHERE id = $1
    AND tenant_id = $2
`

func (q *Queries) DeleteStorageConfiguration(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStorageConfiguration, iD, tenantID)
	return err
}

const findFileByHash = `-- name: FindFileByHash :one
SELECT id, tenant_id, filename, original_filename, mime_type, file_size, file_hash, storage_provider, storage_bucket, storage_path, storage_url, category, related_entity_type, related_entity_id, is_processed, processed_at, metadata, uploaded_by, created_at, updated_at
FROM storage.files
WHERE tenant_id = $1
    AND file_hash = $2
LIMIT 1
`

func (q *Queries) FindFileByHash(ctx context.Context, tenantID pgtype.UUID, fileHash *string) (StorageFile, error) {
	row := q.db.QueryRow(ctx, findFileByHash, tenantID, fileHash)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filename,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.FileHash,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StoragePath,
		&i.StorageUrl,
		&i.Category,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.IsProcessed,
		&i.ProcessedAt,
		&i.Metadata,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultStorageConfig = `-- name: GetDefaultStorageConfig :one
SELECT id, tenant_id, provider_id, config_name, is_default, is_active, host, port, database_name, username, password_text, api_key, secret_key, base_url, bucket_name, region, project_id, additional_config, module_mappings, created_at, updated_at
FROM storage.storage_configurations
WHERE tenant_id = $1
    AND provider_id = $2
    AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultStorageConfig(ctx context.Context, tenantID pgtype.UUID, providerID int32) (StorageStorageConfiguration, error) {
	row := q.db.QueryRow(ctx, getDefaultStorageConfig, tenantID, providerID)
	var i StorageStorageConfiguration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.ConfigName,
		&i.IsDefault,
		&i.IsActive,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.PasswordText,
		&i.ApiKey,
		&i.SecretKey,
		&i.BaseUrl,
		&i.BucketName,
		&i.Region,
		&i.ProjectID,
		&i.AdditionalConfig,
		&i.ModuleMappings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, tenant_id, filename, original_filename, mime_type, file_size, file_hash, storage_provider, storage_bucket, storage_path, storage_url, category, related_entity_type, related_entity_id, is_processed, processed_at, metadata, uploaded_by, created_at, updated_at
FROM storage.files
WHERE id = $1
    AND tenant_id = $2
LIMIT 1
`

func (q *Queries) GetFileByID(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (StorageFile, error) {
	row := q.db.QueryRow(ctx, getFileByID, iD, tenantID)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filename,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.FileHash,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StoragePath,
		&i.StorageUrl,
		&i.Category,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.IsProcessed,
		&i.ProcessedAt,
		&i.Metadata,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByIDGlobal = `-- name: GetFileByIDGlobal :one
SELECT id, tenant_id, filename, original_filename, mime_type, file_size, file_hash, storage_provider, storage_bucket, storage_path, storage_url, category, related_entity_type, related_entity_id, is_processed, processed_at, metadata, uploaded_by, created_at, updated_at
FROM storage.files
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFileByIDGlobal(ctx context.Context, id pgtype.UUID) (StorageFile, error) {
	row := q.db.QueryRow(ctx, getFileByIDGlobal, id)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filename,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.FileHash,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StoragePath,
		&i.StorageUrl,
		&i.Category,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.IsProcessed,
		&i.ProcessedAt,
		&i.Metadata,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileProcessing = `-- name: GetFileProcessing :one
SELECT id, tenant_id, file_id, processing_type, status, result, error_message, started_at, completed_at, processing_time_ms, created_at, updated_at
FROM storage.file_processing
WHERE id = $1
    AND tenant_id = $2
LIMIT 1
`

func (q *Queries) GetFileProcessing(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (StorageFileProcessing, error) {
	row := q.db.QueryRow(ctx, getFileProcessing, iD, tenantID)
	var i StorageFileProcessing
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileID,
		&i.ProcessingType,
		&i.Status,
		&i.Result,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProcessingTimeMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModuleStorageMapping = `-- name: GetModuleStorageMapping :one
SELECT msm.id, msm.tenant_id, msm.module_name, msm.collection_name, msm.config_id, msm.is_active, msm.max_file_size_mb, msm.allowed_file_types, msm.auto_resize, msm.thumbnail_sizes, msm.created_at, msm.updated_at,
    sc.config_name,
    sp.provider_name
FROM storage.module_storage_mappings msm
    JOIN storage.storage_configurations sc ON msm.config_id = sc.id
    JOIN storage.storage_providers sp ON sc.provider_id = sp.id
WHERE msm.tenant_id = $1
    AND msm.module_name = $2
LIMIT 1
`

type GetModuleStorageMappingRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ModuleName       string             `db:"module_name" json:"module_name"`
	CollectionName   string             `db:"collection_name" json:"collection_name"`
	ConfigID         pgtype.UUID        `db:"config_id" json:"config_id"`
	IsActive         *bool              `db:"is_active" json:"is_active"`
	MaxFileSizeMb    *int32             `db:"max_file_size_mb" json:"max_file_size_mb"`
	AllowedFileTypes []string           `db:"allowed_file_types" json:"allowed_file_types"`
	AutoResize       *bool              `db:"auto_resize" json:"auto_resize"`
	ThumbnailSizes   []int32            `db:"thumbnail_sizes" json:"thumbnail_sizes"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ConfigName       string             `db:"config_name" json:"config_name"`
	ProviderName     string             `db:"provider_name" json:"provider_name"`
}

func (q *Queries) GetModuleStorageMapping(ctx context.Context, tenantID pgtype.UUID, moduleName string) (GetModuleStorageMappingRow, error) {
	row := q.db.QueryRow(ctx, getModuleStorageMapping, tenantID, moduleName)
	var i GetModuleStorageMappingRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModuleName,
		&i.CollectionName,
		&i.ConfigID,
		&i.IsActive,
		&i.MaxFileSizeMb,
		&i.AllowedFileTypes,
		&i.AutoResize,
		&i.ThumbnailSizes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigName,
		&i.ProviderName,
	)
	return i, err
}

const getStorageConfigByName = `-- name: GetStorageConfigByName :one
SELECT id, tenant_id, provider_id, config_name, is_default, is_active, host, port, database_name, username, password_text, api_key, secret_key, base_url, bucket_name, region, project_id, additional_config, module_mappings, created_at, updated_at
FROM storage.storage_configurations
WHERE tenant_id = $1
    AND config_name = $2
LIMIT 1
`

func (q *Queries) GetStorageConfigByName(ctx context.Context, tenantID pgtype.UUID, configName string) (StorageStorageConfiguration, error) {
	row := q.db.QueryRow(ctx, getStorageConfigByName, tenantID, configName)
	var i StorageStorageConfiguration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.ConfigName,
		&i.IsDefault,
		&i.IsActive,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.PasswordText,
		&i.ApiKey,
		&i.SecretKey,
		&i.BaseUrl,
		&i.BucketName,
		&i.Region,
		&i.ProjectID,
		&i.AdditionalConfig,
		&i.ModuleMappings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageConfiguration = `-- name: GetStorageConfiguration :one
SELECT id, tenant_id, provider_id, config_name, is_default, is_active, host, port, database_name, username, password_text, api_key, secret_key, base_url, bucket_name, region, project_id, additional_config, module_mappings, created_at, updated_at
FROM storage.storage_configurations
WHERE id = $1
    AND tenant_id = $2
LIMIT 1
`

func (q *Queries) GetStorageConfiguration(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (StorageStorageConfiguration, error) {
	row := q.db.QueryRow(ctx, getStorageConfiguration, iD, tenantID)
	var i StorageStorageConfiguration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.ConfigName,
		&i.IsDefault,
		&i.IsActive,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.PasswordText,
		&i.ApiKey,
		&i.SecretKey,
		&i.BaseUrl,
		&i.BucketName,
		&i.Region,
		&i.ProjectID,
		&i.AdditionalConfig,
		&i.ModuleMappings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageProviderByName = `-- name: GetStorageProviderByName :one
SELECT id, provider_name, display_name, description, provider_type, is_active, supports_collections, supports_authentication, supports_direct_upload, max_file_size_mb, allowed_file_types, configuration_schema, created_at, updated_at
FROM storage.storage_providers
WHERE provider_name = $1
    AND is_active = true
LIMIT 1
`

func (q *Queries) GetStorageProviderByName(ctx context.Context, providerName string) (StorageStorageProvider, error) {
	row := q.db.QueryRow(ctx, getStorageProviderByName, providerName)
	var i StorageStorageProvider
	err := row.Scan(
		&i.ID,
		&i.ProviderName,
		&i.DisplayName,
		&i.Description,
		&i.ProviderType,
		&i.IsActive,
		&i.SupportsCollections,
		&i.SupportsAuthentication,
		&i.SupportsDirectUpload,
		&i.MaxFileSizeMb,
		&i.AllowedFileTypes,
		&i.ConfigurationSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalStorageSize = `-- name: GetTotalStorageSize :one
SELECT COALESCE(SUM(file_size), 0)::BIGINT
FROM storage.files
WHERE tenant_id = $1
`

func (q *Queries) GetTotalStorageSize(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalStorageSize, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listFileAccessLog = `-- name: ListFileAccessLog :many
SELECT id, tenant_id, file_id, access_type, accessed_by, ip_address, user_agent, created_at
FROM storage.file_access_log
WHERE file_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListFileAccessLog(ctx context.Context, fileID pgtype.UUID, limit int32, offset int32) ([]StorageFileAccessLog, error) {
	rows, err := q.db.Query(ctx, listFileAccessLog, fileID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageFileAccessLog{}
	for rows.Next() {
		var i StorageFileAccessLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FileID,
			&i.AccessType,
			&i.AccessedBy,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByCategory = `-- name: ListFilesByCategory :many
SELECT id, tenant_id, filename, original_filename, mime_type, file_size, file_hash, storage_provider, storage_bucket, storage_path, storage_url, category, related_entity_type, related_entity_id, is_processed, processed_at, metadata, uploaded_by, created_at, updated_at
FROM storage.files
WHERE tenant_id = $1
    AND category = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListFilesByCategory(ctx context.Context, tenantID pgtype.UUID, category *string, limit int32, offset int32) ([]StorageFile, error) {
	rows, err := q.db.Query(ctx, listFilesByCategory,
		tenantID,
		category,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageFile{}
	for rows.Next() {
		var i StorageFile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Filename,
			&i.OriginalFilename,
			&i.MimeType,
			&i.FileSize,
			&i.FileHash,
			&i.StorageProvider,
			&i.StorageBucket,
			&i.StoragePath,
			&i.StorageUrl,
			&i.Category,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.IsProcessed,
			&i.ProcessedAt,
			&i.Metadata,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByEntity = `-- name: ListFilesByEntity :many
SELECT id, tenant_id, filename, original_filename, mime_type, file_size, file_hash, storage_provider, storage_bucket, storage_path, storage_url, category, related_entity_type, related_entity_id, is_processed, processed_at, metadata, uploaded_by, created_at, updated_at
FROM storage.files
WHERE tenant_id = $1
    AND related_entity_type = $2
    AND related_entity_id = $3
ORDER BY created_at DESC
`

func (q *Queries) ListFilesByEntity(ctx context.Context, tenantID pgtype.UUID, relatedEntityType *string, relatedEntityID pgtype.UUID) ([]StorageFile, error) {
	rows, err := q.db.Query(ctx, listFilesByEntity, tenantID, relatedEntityType, relatedEntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageFile{}
	for rows.Next() {
		var i StorageFile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Filename,
			&i.OriginalFilename,
			&i.MimeType,
			&i.FileSize,
			&i.FileHash,
			&i.StorageProvider,
			&i.StorageBucket,
			&i.StoragePath,
			&i.StorageUrl,
			&i.Category,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.IsProcessed,
			&i.ProcessedAt,
			&i.Metadata,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByTenant = `-- name: ListFilesByTenant :many
SELECT id, tenant_id, filename, original_filename, mime_type, file_size, file_hash, storage_provider, storage_bucket, storage_path, storage_url, category, related_entity_type, related_entity_id, is_processed, processed_at, metadata, uploaded_by, created_at, updated_at
FROM storage.files
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListFilesByTenant(ctx context.Context, tenantID pgtype.UUID, limit int32, offset int32) ([]StorageFile, error) {
	rows, err := q.db.Query(ctx, listFilesByTenant, tenantID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageFile{}
	for rows.Next() {
		var i StorageFile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Filename,
			&i.OriginalFilename,
			&i.MimeType,
			&i.FileSize,
			&i.FileHash,
			&i.StorageProvider,
			&i.StorageBucket,
			&i.StoragePath,
			&i.StorageUrl,
			&i.Category,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.IsProcessed,
			&i.ProcessedAt,
			&i.Metadata,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModuleStorageMappings = `-- name: ListModuleStorageMappings :many
SELECT msm.id, msm.tenant_id, msm.module_name, msm.collection_name, msm.config_id, msm.is_active, msm.max_file_size_mb, msm.allowed_file_types, msm.auto_resize, msm.thumbnail_sizes, msm.created_at, msm.updated_at,
    sc.config_name
FROM storage.module_storage_mappings msm
    JOIN storage.storage_configurations sc ON msm.config_id = sc.id
WHERE msm.tenant_id = $1
`

type ListModuleStorageMappingsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ModuleName       string             `db:"module_name" json:"module_name"`
	CollectionName   string             `db:"collection_name" json:"collection_name"`
	ConfigID         pgtype.UUID        `db:"config_id" json:"config_id"`
	IsActive         *bool              `db:"is_active" json:"is_active"`
	MaxFileSizeMb    *int32             `db:"max_file_size_mb" json:"max_file_size_mb"`
	AllowedFileTypes []string           `db:"allowed_file_types" json:"allowed_file_types"`
	AutoResize       *bool              `db:"auto_resize" json:"auto_resize"`
	ThumbnailSizes   []int32            `db:"thumbnail_sizes" json:"thumbnail_sizes"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ConfigName       string             `db:"config_name" json:"config_name"`
}

func (q *Queries) ListModuleStorageMappings(ctx context.Context, tenantID pgtype.UUID) ([]ListModuleStorageMappingsRow, error) {
	rows, err := q.db.Query(ctx, listModuleStorageMappings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModuleStorageMappingsRow{}
	for rows.Next() {
		var i ListModuleStorageMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ModuleName,
			&i.CollectionName,
			&i.ConfigID,
			&i.IsActive,
			&i.MaxFileSizeMb,
			&i.AllowedFileTypes,
			&i.AutoResize,
			&i.ThumbnailSizes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfigName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProcessing = `-- name: ListPendingProcessing :many
SELECT id, tenant_id, file_id, processing_type, status, result, error_message, started_at, completed_at, processing_time_ms, created_at, updated_at
FROM storage.file_processing
WHERE tenant_id = $1
    AND status = 'pending'
ORDER BY created_at ASC
LIMIT $2
`

func (q *Queries) ListPendingProcessing(ctx context.Context, tenantID pgtype.UUID, limit int32) ([]StorageFileProcessing, error) {
	rows, err := q.db.Query(ctx, listPendingProcessing, tenantID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageFileProcessing{}
	for rows.Next() {
		var i StorageFileProcessing
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FileID,
			&i.ProcessingType,
			&i.Status,
			&i.Result,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ProcessingTimeMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageConfigurations = `-- name: ListStorageConfigurations :many
SELECT sc.id, sc.tenant_id, sc.provider_id, sc.config_name, sc.is_default, sc.is_active, sc.host, sc.port, sc.database_name, sc.username, sc.password_text, sc.api_key, sc.secret_key, sc.base_url, sc.bucket_name, sc.region, sc.project_id, sc.additional_config, sc.module_mappings, sc.created_at, sc.updated_at,
    sp.display_name as provider_display_name,
    sp.provider_name
FROM storage.storage_configurations sc
    JOIN storage.storage_providers sp ON sc.provider_id = sp.id
WHERE sc.tenant_id = $1
ORDER BY sc.created_at DESC
`

type ListStorageConfigurationsRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	TenantID            pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ProviderID          int32              `db:"provider_id" json:"provider_id"`
	ConfigName          string             `db:"config_name" json:"config_name"`
	IsDefault           *bool              `db:"is_default" json:"is_default"`
	IsActive            *bool              `db:"is_active" json:"is_active"`
	Host                *string            `db:"host" json:"host"`
	Port                *int32             `db:"port" json:"port"`
	DatabaseName        *string            `db:"database_name" json:"database_name"`
	Username            *string            `db:"username" json:"username"`
	PasswordText        *string            `db:"password_text" json:"password_text"`
	ApiKey              *string            `db:"api_key" json:"api_key"`
	SecretKey           *string            `db:"secret_key" json:"secret_key"`
	BaseUrl             *string            `db:"base_url" json:"base_url"`
	BucketName          *string            `db:"bucket_name" json:"bucket_name"`
	Region              *string            `db:"region" json:"region"`
	ProjectID           *string            `db:"project_id" json:"project_id"`
	AdditionalConfig    []byte             `db:"additional_config" json:"additional_config"`
	ModuleMappings      []byte             `db:"module_mappings" json:"module_mappings"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProviderDisplayName string             `db:"provider_display_name" json:"provider_display_name"`
	ProviderName        string             `db:"provider_name" json:"provider_name"`
}

func (q *Queries) ListStorageConfigurations(ctx context.Context, tenantID pgtype.UUID) ([]ListStorageConfigurationsRow, error) {
	rows, err := q.db.Query(ctx, listStorageConfigurations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorageConfigurationsRow{}
	for rows.Next() {
		var i ListStorageConfigurationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderID,
			&i.ConfigName,
			&i.IsDefault,
			&i.IsActive,
			&i.Host,
			&i.Port,
			&i.DatabaseName,
			&i.Username,
			&i.PasswordText,
			&i.ApiKey,
			&i.SecretKey,
			&i.BaseUrl,
			&i.BucketName,
			&i.Region,
			&i.ProjectID,
			&i.AdditionalConfig,
			&i.ModuleMappings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderDisplayName,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageProviders = `-- name: ListStorageProviders :many
SELECT id, provider_name, display_name, description, provider_type, is_active, supports_collections, supports_authentication, supports_direct_upload, max_file_size_mb, allowed_file_types, configuration_schema, created_at, updated_at
FROM storage.storage_providers
WHERE is_active = true
ORDER BY display_name ASC
`

// ==================== STORAGE CONFIGURATION ====================
func (q *Queries) ListStorageProviders(ctx context.Context) ([]StorageStorageProvider, error) {
	rows, err := q.db.Query(ctx, listStorageProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageStorageProvider{}
	for rows.Next() {
		var i StorageStorageProvider
		if err := rows.Scan(
			&i.ID,
			&i.ProviderName,
			&i.DisplayName,
			&i.Description,
			&i.ProviderType,
			&i.IsActive,
			&i.SupportsCollections,
			&i.SupportsAuthentication,
			&i.SupportsDirectUpload,
			&i.MaxFileSizeMb,
			&i.AllowedFileTypes,
			&i.ConfigurationSchema,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileProcessed = `-- name: UpdateFileProcessed :one
UPDATE storage.files
SET is_processed = true,
    processed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
RETURNING id, tenant_id, filename, original_filename, mime_type, file_size, file_hash, storage_provider, storage_bucket, storage_path, storage_url, category, related_entity_type, related_entity_id, is_processed, processed_at, metadata, uploaded_by, created_at, updated_at
`

func (q *Queries) UpdateFileProcessed(ctx context.Context, iD pgtype.UUID, tenantID pgtype.UUID) (StorageFile, error) {
	row := q.db.QueryRow(ctx, updateFileProcessed, iD, tenantID)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Filename,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.FileHash,
		&i.StorageProvider,
		&i.StorageBucket,
		&i.StoragePath,
		&i.StorageUrl,
		&i.Category,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.IsProcessed,
		&i.ProcessedAt,
		&i.Metadata,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProcessingResult = `-- name: UpdateProcessingResult :one
UPDATE storage.file_processing
SET status = $2,
    result = $3,
    error_message = $4,
    completed_at = CURRENT_TIMESTAMP,
    processing_time_ms = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, tenant_id, file_id, processing_type, status, result, error_message, started_at, completed_at, processing_time_ms, created_at, updated_at
`

func (q *Queries) UpdateProcessingResult(ctx context.Context, iD pgtype.UUID, status *string, result []byte, errorMessage *string, processingTimeMs *int32) (StorageFileProcessing, error) {
	row := q.db.QueryRow(ctx, updateProcessingResult,
		iD,
		status,
		result,
		errorMessage,
		processingTimeMs,
	)
	var i StorageFileProcessing
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileID,
		&i.ProcessingType,
		&i.Status,
		&i.Result,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProcessingTimeMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProcessingStatus = `-- name: UpdateProcessingStatus :one
UPDATE storage.file_processing
SET status = $2,
    started_at = CASE
        WHEN $2 = 'processing' THEN CURRENT_TIMESTAMP
        ELSE started_at
    END,
    completed_at = CASE
        WHEN $2 IN ('completed', 'failed') THEN CURRENT_TIMESTAMP
        ELSE completed_at
    END,
    processing_time_ms = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, tenant_id, file_id, processing_type, status, result, error_message, started_at, completed_at, processing_time_ms, created_at, updated_at
`

func (q *Queries) UpdateProcessingStatus(ctx context.Context, iD pgtype.UUID, status *string, processingTimeMs *int32) (StorageFileProcessing, error) {
	row := q.db.QueryRow(ctx, updateProcessingStatus, iD, status, processingTimeMs)
	var i StorageFileProcessing
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileID,
		&i.ProcessingType,
		&i.Status,
		&i.Result,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProcessingTimeMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStorageConfiguration = `-- name: UpdateStorageConfiguration :one
UPDATE storage.storage_configurations
SET config_name = $3,
    is_default = $4,
    is_active = $5,
    host = $6,
    port = $7,
    database_name = $8,
    username = $9,
    password_text = $10,
    api_key = $11,
    secret_key = $12,
    base_url = $13,
    bucket_name = $14,
    region = $15,
    project_id = $16,
    additional_config = $17,
    module_mappings = $18,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND tenant_id = $2
RETURNING id, tenant_id, provider_id, config_name, is_default, is_active, host, port, database_name, username, password_text, api_key, secret_key, base_url, bucket_name, region, project_id, additional_config, module_mappings, created_at, updated_at
`

type UpdateStorageConfigurationParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	TenantID         pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	ConfigName       string      `db:"config_name" json:"config_name"`
	IsDefault        *bool       `db:"is_default" json:"is_default"`
	IsActive         *bool       `db:"is_active" json:"is_active"`
	Host             *string     `db:"host" json:"host"`
	Port             *int32      `db:"port" json:"port"`
	DatabaseName     *string     `db:"database_name" json:"database_name"`
	Username         *string     `db:"username" json:"username"`
	PasswordText     *string     `db:"password_text" json:"password_text"`
	ApiKey           *string     `db:"api_key" json:"api_key"`
	SecretKey        *string     `db:"secret_key" json:"secret_key"`
	BaseUrl          *string     `db:"base_url" json:"base_url"`
	BucketName       *string     `db:"bucket_name" json:"bucket_name"`
	Region           *string     `db:"region" json:"region"`
	ProjectID        *string     `db:"project_id" json:"project_id"`
	AdditionalConfig []byte      `db:"additional_config" json:"additional_config"`
	ModuleMappings   []byte      `db:"module_mappings" json:"module_mappings"`
}

func (q *Queries) UpdateStorageConfiguration(ctx context.Context, arg UpdateStorageConfigurationParams) (StorageStorageConfiguration, error) {
	row := q.db.QueryRow(ctx, updateStorageConfiguration,
		arg.ID,
		arg.TenantID,
		arg.ConfigName,
		arg.IsDefault,
		arg.IsActive,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.Username,
		arg.PasswordText,
		arg.ApiKey,
		arg.SecretKey,
		arg.BaseUrl,
		arg.BucketName,
		arg.Region,
		arg.ProjectID,
		arg.AdditionalConfig,
		arg.ModuleMappings,
	)
	var i StorageStorageConfiguration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.ConfigName,
		&i.IsDefault,
		&i.IsActive,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.PasswordText,
		&i.ApiKey,
		&i.SecretKey,
		&i.BaseUrl,
		&i.BucketName,
		&i.Region,
		&i.ProjectID,
		&i.AdditionalConfig,
		&i.ModuleMappings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
