// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateTenant = `-- name: ActivateTenant :one
UPDATE public.tenants
SET is_active = true,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
`

func (q *Queries) ActivateTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, activateTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.IsActive,
		&i.Settings,
		&i.SubscriptionPlan,
		&i.MaxUsers,
		&i.MaxClients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecondaryColor,
		&i.TertiaryColor,
	)
	return i, err
}

const countActiveTenants = `-- name: CountActiveTenants :one
SELECT COUNT(*)
FROM public.tenants
WHERE is_active = true
`

func (q *Queries) CountActiveTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*)
FROM public.tenants
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO public.tenants (
        name,
        slug,
        domain,
        logo_url,
        primary_color,
        secondary_color,
        tertiary_color,
        settings,
        subscription_plan,
        max_users,
        max_clients
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
`

type CreateTenantParams struct {
	Name             string  `db:"name" json:"name"`
	Slug             string  `db:"slug" json:"slug"`
	Domain           *string `db:"domain" json:"domain"`
	LogoUrl          *string `db:"logo_url" json:"logo_url"`
	PrimaryColor     *string `db:"primary_color" json:"primary_color"`
	SecondaryColor   *string `db:"secondary_color" json:"secondary_color"`
	TertiaryColor    *string `db:"tertiary_color" json:"tertiary_color"`
	Settings         []byte  `db:"settings" json:"settings"`
	SubscriptionPlan *string `db:"subscription_plan" json:"subscription_plan"`
	MaxUsers         *int32  `db:"max_users" json:"max_users"`
	MaxClients       *int32  `db:"max_clients" json:"max_clients"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.LogoUrl,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.TertiaryColor,
		arg.Settings,
		arg.SubscriptionPlan,
		arg.MaxUsers,
		arg.MaxClients,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.IsActive,
		&i.Settings,
		&i.SubscriptionPlan,
		&i.MaxUsers,
		&i.MaxClients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecondaryColor,
		&i.TertiaryColor,
	)
	return i, err
}

const deactivateTenant = `-- name: DeactivateTenant :one
UPDATE public.tenants
SET is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
`

func (q *Queries) DeactivateTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, deactivateTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.IsActive,
		&i.Settings,
		&i.SubscriptionPlan,
		&i.MaxUsers,
		&i.MaxClients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecondaryColor,
		&i.TertiaryColor,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM public.tenants
WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
FROM public.tenants
WHERE id = $1
LIMIT 1
`

// internal/database/queries/tenants.sql
// Queries para gestión CRUD de tenants
func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.IsActive,
		&i.Settings,
		&i.SubscriptionPlan,
		&i.MaxUsers,
		&i.MaxClients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecondaryColor,
		&i.TertiaryColor,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
FROM public.tenants
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.IsActive,
		&i.Settings,
		&i.SubscriptionPlan,
		&i.MaxUsers,
		&i.MaxClients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecondaryColor,
		&i.TertiaryColor,
	)
	return i, err
}

const listActiveTenants = `-- name: ListActiveTenants :many
SELECT id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
FROM public.tenants
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListActiveTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listActiveTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Domain,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.IsActive,
			&i.Settings,
			&i.SubscriptionPlan,
			&i.MaxUsers,
			&i.MaxClients,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecondaryColor,
			&i.TertiaryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
FROM public.tenants
ORDER BY name
LIMIT $1 OFFSET $2
`

func (q *Queries) ListTenants(ctx context.Context, limit int32, offset int32) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Domain,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.IsActive,
			&i.Settings,
			&i.SubscriptionPlan,
			&i.MaxUsers,
			&i.MaxClients,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecondaryColor,
			&i.TertiaryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE public.tenants
SET name = $2,
    domain = $3,
    logo_url = $4,
    primary_color = $5,
    secondary_color = $6,
    tertiary_color = $7,
    subscription_plan = $8,
    max_users = $9,
    max_clients = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
`

func (q *Queries) UpdateTenant(ctx context.Context, iD pgtype.UUID, name string, domain *string, logoUrl *string, primaryColor *string, secondaryColor *string, tertiaryColor *string, subscriptionPlan *string, maxUsers *int32, maxClients *int32) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		iD,
		name,
		domain,
		logoUrl,
		primaryColor,
		secondaryColor,
		tertiaryColor,
		subscriptionPlan,
		maxUsers,
		maxClients,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.IsActive,
		&i.Settings,
		&i.SubscriptionPlan,
		&i.MaxUsers,
		&i.MaxClients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecondaryColor,
		&i.TertiaryColor,
	)
	return i, err
}

const updateTenantSettings = `-- name: UpdateTenantSettings :one
UPDATE public.tenants
SET settings = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
`

func (q *Queries) UpdateTenantSettings(ctx context.Context, iD pgtype.UUID, settings []byte) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantSettings, iD, settings)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.IsActive,
		&i.Settings,
		&i.SubscriptionPlan,
		&i.MaxUsers,
		&i.MaxClients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecondaryColor,
		&i.TertiaryColor,
	)
	return i, err
}

const updateTenantTheme = `-- name: UpdateTenantTheme :one
UPDATE public.tenants
SET primary_color = $2,
    secondary_color = $3,
    tertiary_color = $4,
    logo_url = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, slug, domain, logo_url, primary_color, is_active, settings, subscription_plan, max_users, max_clients, created_at, updated_at, secondary_color, tertiary_color
`

func (q *Queries) UpdateTenantTheme(ctx context.Context, iD pgtype.UUID, primaryColor *string, secondaryColor *string, tertiaryColor *string, logoUrl *string) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantTheme,
		iD,
		primaryColor,
		secondaryColor,
		tertiaryColor,
		logoUrl,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.IsActive,
		&i.Settings,
		&i.SubscriptionPlan,
		&i.MaxUsers,
		&i.MaxClients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecondaryColor,
		&i.TertiaryColor,
	)
	return i, err
}
